"""Controlled taxonomies for Ayin/external dialogue judgments."""

from enum import StrEnum


class RelationType(StrEnum):
    EMPIRICALLY_RELEVANT_TO = "EMPIRICALLY_RELEVANT_TO"
    SUPPORTS_EMPIRICAL_SUBCLAIM = "SUPPORTS_EMPIRICAL_SUBCLAIM"
    CONCEPTUAL_PARALLEL = "CONCEPTUAL_PARALLEL"
    HISTORICAL_PARALLEL = "HISTORICAL_PARALLEL"
    ILLUSTRATES = "ILLUSTRATES"
    COMPATIBLE_WITH = "COMPATIBLE_WITH"
    TENSION_WITH = "TENSION_WITH"
    CHALLENGES = "CHALLENGES"
    COUNTEREXAMPLE_TO = "COUNTEREXAMPLE_TO"
    ALTERNATIVE_EXPLANATION = "ALTERNATIVE_EXPLANATION"
    NOT_EQUIVALENT_TO = "NOT_EQUIVALENT_TO"
    UNRESOLVED_RELATION = "UNRESOLVED_RELATION"


class RelationScope(StrEnum):
    CONCEPTUAL = "CONCEPTUAL"
    EMPIRICAL = "EMPIRICAL"
    DESCRIPTIVE = "DESCRIPTIVE"
    ETHICAL = "ETHICAL"
    METAPHYSICAL = "METAPHYSICAL"
    HISTORICAL = "HISTORICAL"
    ILLUSTRATIVE = "ILLUSTRATIVE"


class EvidenceRole(StrEnum):
    EMPIRICAL_EVIDENCE = "EMPIRICAL_EVIDENCE"
    EMPIRICAL_COUNTEREVIDENCE = "EMPIRICAL_COUNTEREVIDENCE"
    PHILOSOPHICAL_ARGUMENT = "PHILOSOPHICAL_ARGUMENT"
    CONCEPTUAL_ANALOGY = "CONCEPTUAL_ANALOGY"
    HISTORICAL_CONTEXT = "HISTORICAL_CONTEXT"
    EXAMPLE = "EXAMPLE"
    ANECDOTE = "ANECDOTE"
    COMMENTARY = "COMMENTARY"
    REFERENCE_ONLY = "REFERENCE_ONLY"
    ALTERNATIVE_EXPLANATION = "ALTERNATIVE_EXPLANATION"
    UNKNOWN = "UNKNOWN"


class ClaimTestability(StrEnum):
    CONCEPTUAL = "CONCEPTUAL"
    DESCRIPTIVE_TESTABLE = "DESCRIPTIVE_TESTABLE"
    DESCRIPTIVE_NONTESTABLE = "DESCRIPTIVE_NONTESTABLE"
    ETHICAL = "ETHICAL"
    OPTIONAL_METAPHYSICAL = "OPTIONAL_METAPHYSICAL"
    OPEN_QUESTION = "OPEN_QUESTION"


class AyinTargetKind(StrEnum):
    CONCEPT_VERSION = "CONCEPT_VERSION"
    PRINCIPLE_VERSION = "PRINCIPLE_VERSION"
    DISTINCTION_VERSION = "DISTINCTION_VERSION"
    OPEN_QUESTION_VERSION = "OPEN_QUESTION_VERSION"


class ExternalTargetKind(StrEnum):
    CLAIM = "CLAIM"
    WORK = "WORK"
    CHUNK = "CHUNK"
    EXTERNAL_CONCEPT = "EXTERNAL_CONCEPT"
    PERSON = "PERSON"


class ProposalMethod(StrEnum):
    MODEL_CLASSIFIER = "MODEL_CLASSIFIER"
    MANUAL = "MANUAL"


class ReviewStatus(StrEnum):
    PROPOSED = "PROPOSED"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ReviewPriority(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ReviewReason(StrEnum):
    RELATION_AMBIGUITY = "RELATION_AMBIGUITY"
    DISCOURSE_MISMATCH = "DISCOURSE_MISMATCH"
    EMPIRICAL_SCOPE_UNCLEAR = "EMPIRICAL_SCOPE_UNCLEAR"
    POTENTIAL_FALSE_EQUIVALENCE = "POTENTIAL_FALSE_EQUIVALENCE"
    INSUFFICIENT_EXTERNAL_EVIDENCE = "INSUFFICIENT_EXTERNAL_EVIDENCE"
    CONFLICTING_EXTERNAL_EVIDENCE = "CONFLICTING_EXTERNAL_EVIDENCE"
    METAPHYSICAL_OVERREACH = "METAPHYSICAL_OVERREACH"
    UNSUPPORTED_SCIENTIFIC_FRAMING = "UNSUPPORTED_SCIENTIFIC_FRAMING"
    ALTERNATIVE_EXPLANATION_PRESENT = "ALTERNATIVE_EXPLANATION_PRESENT"
    UNCERTAIN_AYIN_TARGET = "UNCERTAIN_AYIN_TARGET"
    STALE_AFTER_AYIN_REVISION = "STALE_AFTER_AYIN_REVISION"
    STALE_AFTER_EXTERNAL_REVISION = "STALE_AFTER_EXTERNAL_REVISION"


class ProposalRunStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class ReviewAction(StrEnum):
    START_REVIEW = "START_REVIEW"
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    SUPERSEDE = "SUPERSEDE"


NEGATIVE_RELATION_TYPES = frozenset(
    {
        RelationType.TENSION_WITH,
        RelationType.CHALLENGES,
        RelationType.COUNTEREXAMPLE_TO,
        RelationType.ALTERNATIVE_EXPLANATION,
        RelationType.NOT_EQUIVALENT_TO,
        RelationType.UNRESOLVED_RELATION,
    }
)


ALLOWED_SCOPES: dict[RelationType, frozenset[RelationScope]] = {
    RelationType.EMPIRICALLY_RELEVANT_TO: frozenset(
        {RelationScope.EMPIRICAL, RelationScope.DESCRIPTIVE}
    ),
    RelationType.SUPPORTS_EMPIRICAL_SUBCLAIM: frozenset({RelationScope.EMPIRICAL}),
    RelationType.CONCEPTUAL_PARALLEL: frozenset({RelationScope.CONCEPTUAL}),
    RelationType.HISTORICAL_PARALLEL: frozenset({RelationScope.HISTORICAL}),
    RelationType.ILLUSTRATES: frozenset({RelationScope.ILLUSTRATIVE}),
    RelationType.COMPATIBLE_WITH: frozenset(RelationScope),
    RelationType.TENSION_WITH: frozenset(RelationScope),
    RelationType.CHALLENGES: frozenset(RelationScope),
    RelationType.COUNTEREXAMPLE_TO: frozenset(
        {RelationScope.EMPIRICAL, RelationScope.DESCRIPTIVE, RelationScope.CONCEPTUAL}
    ),
    RelationType.ALTERNATIVE_EXPLANATION: frozenset(
        {RelationScope.EMPIRICAL, RelationScope.DESCRIPTIVE, RelationScope.CONCEPTUAL}
    ),
    RelationType.NOT_EQUIVALENT_TO: frozenset({RelationScope.CONCEPTUAL}),
    RelationType.UNRESOLVED_RELATION: frozenset(RelationScope),
}
