"""add lecture source foreign keys

Revision ID: 01376042ceb7
Revises: 621e48994058
Create Date: 2026-09-23 00:57:39.692186
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '01376042ceb7'
down_revision: str | None = '621e48994058'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_lecture_master_versions_manasek_version_id_ritual_versions'), 'lecture_master_versions', 'ritual_versions', ['manasek_version_id'], ['id'], source_schema='content', referent_schema='ritual', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_lecture_master_versions_canon_version_id_canon_versions'), 'lecture_master_versions', 'canon_versions', ['canon_version_id'], ['id'], source_schema='content', referent_schema='core', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_lecture_ritual_links_ritual_version_id_ritual_versions'), 'lecture_ritual_links', 'ritual_versions', ['ritual_version_id'], ['id'], source_schema='content', referent_schema='ritual', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("ALTER TABLE content.lecture_ritual_links DROP CONSTRAINT IF EXISTS fk_lecture_ritual_links_ritual_version_id_ritual_versions")
    op.execute("ALTER TABLE content.lecture_master_versions DROP CONSTRAINT IF EXISTS fk_lecture_master_versions_canon_version_id_canon_versions")
    op.execute("ALTER TABLE content.lecture_master_versions DROP CONSTRAINT IF EXISTS fk_lecture_master_versions_manasek_version_id_ritual_versions")
