"""add ayin research engine

Revision ID: 0551b352aefb
Revises: 26a7bca28432
Create Date: 2026-09-22 23:55:45.832214
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0551b352aefb'
down_revision: str | None = '26a7bca28432'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('human_question', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'READY', 'ARCHIVED', name='research_project_status', schema='content'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_projects')),
    schema='content'
    )
    op.create_table('ayin_spines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('research_project_id', sa.Uuid(), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('central_human_question', sa.Text(), nullable=False),
    sa.Column('canonical_question', sa.Text(), nullable=False),
    sa.Column('discourse_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prohibited_conflations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optional_ritual_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'VALIDATED', 'SUPERSEDED', name='spine_status', schema='content'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("input_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_ayin_spines_valid_input_hash')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_ayin_spines_positive_version')),
    sa.ForeignKeyConstraint(['canon_version_id'], ['core.canon_versions.id'], name=op.f('fk_ayin_spines_canon_version_id_canon_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['research_project_id'], ['content.research_projects.id'], name=op.f('fk_ayin_spines_research_project_id_research_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ayin_spines')),
    sa.UniqueConstraint('research_project_id', 'version_number', name=op.f('uq_ayin_spines_research_project_id_version_number')),
    schema='content'
    )
    op.create_index(op.f('ix_ayin_spines_research_project_id'), 'ayin_spines', ['research_project_id'], unique=False, schema='content')
    op.create_table('research_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ayin_spine_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('manasek_relevant', sa.Boolean(), nullable=False),
    sa.Column('manasek_reason', sa.Text(), nullable=True),
    sa.Column('prohibited_conflations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieval_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'READY', 'SUPERSEDED', name='research_plan_status', schema='content'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("input_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_research_plans_valid_input_hash')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_research_plans_positive_version')),
    sa.ForeignKeyConstraint(['ayin_spine_id'], ['content.ayin_spines.id'], name=op.f('fk_research_plans_ayin_spine_id_ayin_spines'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_plans')),
    sa.UniqueConstraint('ayin_spine_id', 'version_number', name=op.f('uq_research_plans_ayin_spine_id_version_number')),
    schema='content'
    )
    op.create_index(op.f('ix_research_plans_ayin_spine_id'), 'research_plans', ['ayin_spine_id'], unique=False, schema='content')
    op.create_table('research_packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('research_project_id', sa.Uuid(), nullable=False),
    sa.Column('ayin_spine_id', sa.Uuid(), nullable=False),
    sa.Column('research_plan_id', sa.Uuid(), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.Column('retrieval_configuration_id', sa.Uuid(), nullable=False),
    sa.Column('package_version', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('BUILDING', 'FROZEN', 'SUPERSEDED', name='research_package_status', schema='content'), nullable=False),
    sa.Column('retrieval_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unresolved_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("content_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_research_packages_valid_content_hash')),
    sa.CheckConstraint("input_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_research_packages_valid_input_hash')),
    sa.CheckConstraint('package_version > 0', name=op.f('ck_research_packages_positive_package_version')),
    sa.ForeignKeyConstraint(['ayin_spine_id'], ['content.ayin_spines.id'], name=op.f('fk_research_packages_ayin_spine_id_ayin_spines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['canon_version_id'], ['core.canon_versions.id'], name=op.f('fk_research_packages_canon_version_id_canon_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['research_plan_id'], ['content.research_plans.id'], name=op.f('fk_research_packages_research_plan_id_research_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['research_project_id'], ['content.research_projects.id'], name=op.f('fk_research_packages_research_project_id_research_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['retrieval_configuration_id'], ['retrieval.configurations.id'], name=op.f('fk_research_packages_retrieval_configuration_id_configurations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_packages')),
    sa.UniqueConstraint('research_project_id', 'package_version', name=op.f('uq_research_packages_research_project_id_package_version')),
    schema='content'
    )
    op.create_index(op.f('ix_research_packages_research_project_id'), 'research_packages', ['research_project_id'], unique=False, schema='content')
    op.create_table('research_plan_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('research_plan_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', postgresql.ENUM('AYIN', 'EMPIRICAL', 'PHILOSOPHICAL', 'EXTERNAL_CONCEPT', 'COUNTEREVIDENCE', 'MANASEK', name='research_question_kind', schema='content'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('retrieval_text', sa.Text(), nullable=False),
    sa.Column('requires_counterevidence', sa.Boolean(), nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'ANSWERED', 'UNRESOLVED', 'DEFERRED', name='research_question_status', schema='content'), nullable=False),
    sa.CheckConstraint('ordinal > 0', name=op.f('ck_research_plan_questions_positive_ordinal')),
    sa.ForeignKeyConstraint(['research_plan_id'], ['content.research_plans.id'], name=op.f('fk_research_plan_questions_research_plan_id_research_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_plan_questions')),
    sa.UniqueConstraint('research_plan_id', 'ordinal', name=op.f('uq_research_plan_questions_research_plan_id_ordinal')),
    schema='content'
    )
    op.create_index(op.f('ix_research_plan_questions_research_plan_id'), 'research_plan_questions', ['research_plan_id'], unique=False, schema='content')
    op.create_table('ayin_spine_passages',
    sa.Column('ayin_spine_id', sa.Uuid(), nullable=False),
    sa.Column('passage_id', sa.Uuid(), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ayin_spine_id'], ['content.ayin_spines.id'], name=op.f('fk_ayin_spine_passages_ayin_spine_id_ayin_spines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passage_id', 'canon_version_id'], ['core.canon_passages.id', 'core.canon_passages.canon_version_id'], name=op.f('fk_ayin_spine_passages_passage_id_canon_version_id_canon_passages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ayin_spine_id', 'passage_id', name=op.f('pk_ayin_spine_passages')),
    schema='content'
    )
    op.create_table('research_package_ayin_passages',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('passage_id', sa.Uuid(), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_research_package_ayin_passages_package_id_research_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passage_id', 'canon_version_id'], ['core.canon_passages.id', 'core.canon_passages.canon_version_id'], name=op.f('fk_research_package_ayin_passages_passage_id_canon_version_id_canon_passages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('package_id', 'passage_id', name=op.f('pk_research_package_ayin_passages')),
    schema='content'
    )
    op.create_table('research_package_external_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('selection_role', postgresql.ENUM('AYIN_GROUNDING', 'EXTERNAL_EVIDENCE', 'COUNTEREVIDENCE', 'ALTERNATIVE_EXPLANATION', 'CONCEPTUAL_PARALLEL', 'TENSION', 'UNRESOLVED', 'RITUAL_CONTEXT', name='evidence_selection_role', schema='content'), nullable=False),
    sa.Column('retrieval_result_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['retrieval.chunks.id'], name=op.f('fk_research_package_external_chunks_chunk_id_chunks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_research_package_external_chunks_package_id_research_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retrieval_result_id'], ['retrieval.results.id'], name=op.f('fk_research_package_external_chunks_retrieval_result_id_results'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_version_id'], ['knowledge.source_versions.id'], name=op.f('fk_research_package_external_chunks_source_version_id_source_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_package_external_chunks')),
    sa.UniqueConstraint('package_id', 'chunk_id', name=op.f('uq_research_package_external_chunks_package_id_chunk_id')),
    schema='content'
    )
    op.create_index(op.f('ix_research_package_external_chunks_package_id'), 'research_package_external_chunks', ['package_id'], unique=False, schema='content')
    op.create_table('research_package_external_claims',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_segment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id', 'source_version_id', 'source_segment_id'], ['knowledge.external_claims.id', 'knowledge.external_claims.source_version_id', 'knowledge.external_claims.source_segment_id'], name=op.f('fk_research_package_external_claims_claim_id_source_version_id_source_segment_id_external_claims'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_research_package_external_claims_package_id_research_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', 'claim_id', name=op.f('pk_research_package_external_claims')),
    schema='content'
    )
    op.create_table('research_package_external_people',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_research_package_external_people_package_id_research_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['knowledge.people.id'], name=op.f('fk_research_package_external_people_person_id_people'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('package_id', 'person_id', name=op.f('pk_research_package_external_people')),
    schema='content'
    )
    op.create_table('research_package_external_works',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_research_package_external_works_package_id_research_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['knowledge.works.id'], name=op.f('fk_research_package_external_works_work_id_works'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('package_id', 'work_id', name=op.f('pk_research_package_external_works')),
    schema='content'
    )
    op.create_table('research_package_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('severity', postgresql.ENUM('INFO', 'WARNING', 'ERROR', name='package_issue_severity', schema='content'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_research_package_issues_package_id_research_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_package_issues')),
    schema='content'
    )
    op.create_index(op.f('ix_research_package_issues_package_id'), 'research_package_issues', ['package_id'], unique=False, schema='content')
    op.create_table('ayin_spine_concepts',
    sa.Column('ayin_spine_id', sa.Uuid(), nullable=False),
    sa.Column('concept_version_id', sa.Uuid(), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.Column('role', postgresql.ENUM('PRIMARY', 'SECONDARY', name='spine_concept_role', schema='content'), nullable=False),
    sa.ForeignKeyConstraint(['ayin_spine_id'], ['content.ayin_spines.id'], name=op.f('fk_ayin_spine_concepts_ayin_spine_id_ayin_spines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_version_id', 'canon_version_id'], ['core.ayin_concept_versions.id', 'core.ayin_concept_versions.canon_version_id'], name=op.f('fk_ayin_spine_concepts_concept_version_id_canon_version_id_ayin_concept_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ayin_spine_id', 'concept_version_id', name=op.f('pk_ayin_spine_concepts')),
    sa.UniqueConstraint('ayin_spine_id', 'concept_version_id', name=op.f('uq_ayin_spine_concepts_ayin_spine_id_concept_version_id')),
    schema='content'
    )
    op.create_unique_constraint(
        'uq_ayin_spine_concepts_ayin_spine_id_concept_version_id',
        'ayin_spine_concepts',
        ['ayin_spine_id', 'concept_version_id'],
        schema='content',
    )
    op.create_table('ayin_spine_distinctions',
    sa.Column('ayin_spine_id', sa.Uuid(), nullable=False),
    sa.Column('distinction_version_id', sa.Uuid(), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ayin_spine_id'], ['content.ayin_spines.id'], name=op.f('fk_ayin_spine_distinctions_ayin_spine_id_ayin_spines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['distinction_version_id', 'canon_version_id'], ['core.ayin_distinction_versions.id', 'core.ayin_distinction_versions.canon_version_id'], name=op.f('fk_ayin_spine_distinctions_distinction_version_id_canon_version_id_ayin_distinction_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ayin_spine_id', 'distinction_version_id', name=op.f('pk_ayin_spine_distinctions')),
    schema='content'
    )
    op.create_table('ayin_spine_open_questions',
    sa.Column('ayin_spine_id', sa.Uuid(), nullable=False),
    sa.Column('open_question_version_id', sa.Uuid(), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ayin_spine_id'], ['content.ayin_spines.id'], name=op.f('fk_ayin_spine_open_questions_ayin_spine_id_ayin_spines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['open_question_version_id', 'canon_version_id'], ['core.ayin_open_question_versions.id', 'core.ayin_open_question_versions.canon_version_id'], name=op.f('fk_ayin_spine_open_questions_open_question_version_id_canon_version_id_ayin_open_question_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ayin_spine_id', 'open_question_version_id', name=op.f('pk_ayin_spine_open_questions')),
    schema='content'
    )
    op.create_table('ayin_spine_principles',
    sa.Column('ayin_spine_id', sa.Uuid(), nullable=False),
    sa.Column('principle_version_id', sa.Uuid(), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ayin_spine_id'], ['content.ayin_spines.id'], name=op.f('fk_ayin_spine_principles_ayin_spine_id_ayin_spines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['principle_version_id', 'canon_version_id'], ['core.ayin_principle_versions.id', 'core.ayin_principle_versions.canon_version_id'], name=op.f('fk_ayin_spine_principles_principle_version_id_canon_version_id_ayin_principle_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ayin_spine_id', 'principle_version_id', name=op.f('pk_ayin_spine_principles')),
    schema='content'
    )
    op.create_table('research_package_ayin_concepts',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('concept_version_id', sa.Uuid(), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['concept_version_id', 'canon_version_id'], ['core.ayin_concept_versions.id', 'core.ayin_concept_versions.canon_version_id'], name=op.f('fk_research_package_ayin_concepts_concept_version_id_canon_version_id_ayin_concept_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_research_package_ayin_concepts_package_id_research_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', 'concept_version_id', name=op.f('pk_research_package_ayin_concepts')),
    schema='content'
    )
    op.create_table('research_package_ayin_distinctions',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('distinction_version_id', sa.Uuid(), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['distinction_version_id', 'canon_version_id'], ['core.ayin_distinction_versions.id', 'core.ayin_distinction_versions.canon_version_id'], name=op.f('fk_research_package_ayin_distinctions_distinction_version_id_canon_version_id_ayin_distinction_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_research_package_ayin_distinctions_package_id_research_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', 'distinction_version_id', name=op.f('pk_research_package_ayin_distinctions')),
    schema='content'
    )
    op.create_table('research_package_ayin_open_questions',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('open_question_version_id', sa.Uuid(), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['open_question_version_id', 'canon_version_id'], ['core.ayin_open_question_versions.id', 'core.ayin_open_question_versions.canon_version_id'], name=op.f('fk_research_package_ayin_open_questions_open_question_version_id_canon_version_id_ayin_open_question_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_research_package_ayin_open_questions_package_id_research_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', 'open_question_version_id', name=op.f('pk_research_package_ayin_open_questions')),
    schema='content'
    )
    op.create_table('research_package_ayin_principles',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('principle_version_id', sa.Uuid(), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_research_package_ayin_principles_package_id_research_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['principle_version_id', 'canon_version_id'], ['core.ayin_principle_versions.id', 'core.ayin_principle_versions.canon_version_id'], name=op.f('fk_research_package_ayin_principles_principle_version_id_canon_version_id_ayin_principle_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('package_id', 'principle_version_id', name=op.f('pk_research_package_ayin_principles')),
    schema='content'
    )
    op.create_table('research_package_ritual_versions',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('ritual_version_id', sa.Uuid(), nullable=False),
    sa.Column('selection_role', postgresql.ENUM('AYIN_GROUNDING', 'EXTERNAL_EVIDENCE', 'COUNTEREVIDENCE', 'ALTERNATIVE_EXPLANATION', 'CONCEPTUAL_PARALLEL', 'TENSION', 'UNRESOLVED', 'RITUAL_CONTEXT', name='evidence_selection_role', schema='content'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_research_package_ritual_versions_package_id_research_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ritual_version_id'], ['ritual.ritual_versions.id'], name=op.f('fk_research_package_ritual_versions_ritual_version_id_ritual_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('package_id', 'ritual_version_id', name=op.f('pk_research_package_ritual_versions')),
    schema='content'
    )
    op.create_table('research_package_dialogue_relations',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('relation_id', sa.Uuid(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('selection_role', postgresql.ENUM('AYIN_GROUNDING', 'EXTERNAL_EVIDENCE', 'COUNTEREVIDENCE', 'ALTERNATIVE_EXPLANATION', 'CONCEPTUAL_PARALLEL', 'TENSION', 'UNRESOLVED', 'RITUAL_CONTEXT', name='evidence_selection_role', schema='content'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_research_package_dialogue_relations_package_id_research_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_id'], ['knowledge.dialogue_relations.id'], name=op.f('fk_research_package_dialogue_relations_relation_id_dialogue_relations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('package_id', 'relation_id', name=op.f('pk_research_package_dialogue_relations')),
    schema='content'
    )
    op.execute("""
    CREATE FUNCTION content.prevent_frozen_research_package_mutation()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
        IF OLD.status = 'FROZEN' AND (TG_OP = 'DELETE' OR NEW.status <> 'FROZEN'
            OR NEW.content_hash <> OLD.content_hash
            OR NEW.input_hash <> OLD.input_hash
            OR NEW.retrieval_snapshot <> OLD.retrieval_snapshot
            OR NEW.unresolved_issues <> OLD.unresolved_issues) THEN
            RAISE EXCEPTION 'frozen ResearchPackage % is immutable', OLD.id;
        END IF;
        RETURN COALESCE(NEW, OLD);
    END;
    $$;
    CREATE TRIGGER research_packages_frozen_immutable
    BEFORE UPDATE OR DELETE ON content.research_packages
    FOR EACH ROW EXECUTE FUNCTION content.prevent_frozen_research_package_mutation();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS research_packages_frozen_immutable ON content.research_packages")
    op.execute("DROP FUNCTION IF EXISTS content.prevent_frozen_research_package_mutation()")
    op.drop_table('research_package_dialogue_relations', schema='content')
    op.drop_table('research_package_ritual_versions', schema='content')
    op.drop_table('research_package_ayin_principles', schema='content')
    op.drop_table('research_package_ayin_open_questions', schema='content')
    op.drop_table('research_package_ayin_distinctions', schema='content')
    op.drop_table('research_package_ayin_concepts', schema='content')
    op.drop_table('ayin_spine_principles', schema='content')
    op.drop_table('ayin_spine_open_questions', schema='content')
    op.drop_table('ayin_spine_distinctions', schema='content')
    op.drop_table('ayin_spine_concepts', schema='content')
    op.drop_index(op.f('ix_research_package_issues_package_id'), table_name='research_package_issues', schema='content')
    op.drop_table('research_package_issues', schema='content')
    op.drop_table('research_package_external_works', schema='content')
    op.drop_table('research_package_external_people', schema='content')
    op.drop_table('research_package_external_claims', schema='content')
    op.drop_index(op.f('ix_research_package_external_chunks_package_id'), table_name='research_package_external_chunks', schema='content')
    op.drop_table('research_package_external_chunks', schema='content')
    op.drop_table('research_package_ayin_passages', schema='content')
    op.drop_table('ayin_spine_passages', schema='content')
    op.drop_index(op.f('ix_research_plan_questions_research_plan_id'), table_name='research_plan_questions', schema='content')
    op.drop_table('research_plan_questions', schema='content')
    op.drop_index(op.f('ix_research_packages_research_project_id'), table_name='research_packages', schema='content')
    op.drop_table('research_packages', schema='content')
    op.drop_index(op.f('ix_research_plans_ayin_spine_id'), table_name='research_plans', schema='content')
    op.drop_table('research_plans', schema='content')
    op.drop_index(op.f('ix_ayin_spines_research_project_id'), table_name='ayin_spines', schema='content')
    op.drop_table('ayin_spines', schema='content')
    op.drop_table('research_projects', schema='content')
    for enum_name in (
        'evidence_selection_role',
        'package_issue_severity',
        'research_package_status',
        'research_plan_status',
        'research_question_status',
        'research_question_kind',
        'spine_concept_role',
        'spine_status',
        'research_project_status',
    ):
        op.execute(f'DROP TYPE IF EXISTS content.{enum_name}')
    # ### end Alembic commands ###
