"""add localization and pronunciation domain

Revision ID: 0aa9c737356c
Revises: 062634e5e65b
Create Date: 2026-09-23 06:47:54.130174
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0aa9c737356c'
down_revision: str | None = '062634e5e65b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronunciation_lexicon_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('language', postgresql.ENUM('fa', 'de', 'en', 'ar', name='language_code', schema='core', create_type=False), nullable=False),
    sa.Column('written_form', sa.String(length=512), nullable=False),
    sa.Column('preferred_pronunciation', sa.String(length=512), nullable=False),
    sa.Column('provider_representation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transliteration', sa.String(length=512), nullable=True),
    sa.Column('ipa', sa.String(length=512), nullable=True),
    sa.Column('ssml', sa.Text(), nullable=True),
    sa.Column('criticality', postgresql.ENUM('CRITICAL', 'IMPORTANT', 'NORMAL', name='pronunciation_criticality', schema='content'), nullable=False),
    sa.Column('status', postgresql.ENUM('PROPOSED', 'APPROVED', 'DEPRECATED', name='pronunciation_lexicon_status', schema='content'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['core.terms.id'], name=op.f('fk_pronunciation_lexicon_entries_term_id_terms'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pronunciation_lexicon_entries')),
    schema='content'
    )
    op.create_table('localization_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lecture_master_version_id', sa.Uuid(), nullable=False),
    sa.Column('language', postgresql.ENUM('fa', 'de', 'en', 'ar', name='publication_language', schema='content'), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SEMANTICALLY_APPROVED', 'NOT_READY_FOR_TTS', 'READY_FOR_TTS', 'APPROVED', 'FAILED', name='localization_status', schema='content'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lecture_master_version_id'], ['content.lecture_master_versions.id'], name=op.f('fk_localization_projects_lecture_master_version_id_lecture_master_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_localization_projects')),
    schema='content'
    )
    op.create_table('localization_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('localization_project_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('display_language', postgresql.ENUM('fa', 'de', 'en', 'ar', name='language_code', schema='core', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SEMANTICALLY_APPROVED', 'NOT_READY_FOR_TTS', 'READY_FOR_TTS', 'APPROVED', 'FAILED', name='localization_status', schema='content'), nullable=False),
    sa.Column('semantic_validation_status', postgresql.ENUM('NOT_VALIDATED', 'PASSED', 'FAILED', name='semantic_validation_status', schema='content'), nullable=False),
    sa.Column('pronunciation_status', postgresql.ENUM('NOT_PREPARED', 'PREPARED', 'VALIDATED', 'FAILED', name='pronunciation_status', schema='content'), nullable=False),
    sa.Column('pronunciation_lexicon_version', sa.Integer(), nullable=True),
    sa.Column('tts_provider_profile', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['localization_project_id'], ['content.localization_projects.id'], name=op.f('fk_localization_versions_localization_project_id_localization_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_localization_versions')),
    schema='content'
    )
    op.create_table('audio_pronunciation_qa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('localization_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('PASSED', 'REVIEW', 'FAILED', name='audio_qa_status', schema='content'), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('audio_asset_id', sa.Uuid(), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['localization_version_id'], ['content.localization_versions.id'], name=op.f('fk_audio_pronunciation_qa_localization_version_id_localization_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_pronunciation_qa')),
    schema='content'
    )
    op.create_table('localization_statements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('localization_version_id', sa.Uuid(), nullable=False),
    sa.Column('lecture_claim_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('display_text', sa.Text(), nullable=False),
    sa.Column('tts_text', sa.Text(), nullable=True),
    sa.Column('claim_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['lecture_claim_id'], ['content.lecture_claims.id'], name=op.f('fk_localization_statements_lecture_claim_id_lecture_claims'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['localization_version_id'], ['content.localization_versions.id'], name=op.f('fk_localization_statements_localization_version_id_localization_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_localization_statements')),
    schema='content'
    )
    op.create_table('localization_validation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('localization_version_id', sa.Uuid(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['localization_version_id'], ['content.localization_versions.id'], name=op.f('fk_localization_validation_runs_localization_version_id_localization_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_localization_validation_runs')),
    schema='content'
    )
    op.create_table('localization_validation_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('validation_run_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['content.localization_validation_runs.id'], name=op.f('fk_localization_validation_findings_validation_run_id_localization_validation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_localization_validation_findings')),
    schema='content'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('localization_validation_findings', schema='content')
    op.drop_table('localization_validation_runs', schema='content')
    op.drop_table('localization_statements', schema='content')
    op.drop_table('audio_pronunciation_qa', schema='content')
    op.drop_table('localization_versions', schema='content')
    op.drop_table('localization_projects', schema='content')
    op.drop_table('pronunciation_lexicon_entries', schema='content')
    for enum_name in (
        'audio_qa_status',
        'pronunciation_status',
        'semantic_validation_status',
        'localization_status',
        'publication_language',
        'pronunciation_lexicon_status',
        'pronunciation_criticality',
    ):
        op.execute(f'DROP TYPE IF EXISTS content.{enum_name}')
    # ### end Alembic commands ###
