"""implement manasek ritual domain

Revision ID: 20260919_0004
Revises: 20260918_0003
Create Date: 2026-09-19 10:36:11.697355
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260919_0004"
down_revision: str | None = "20260918_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column(
            "original_language",
            postgresql.ENUM(
                "fa", "en", "ar", name="language_code", schema="core", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "corpus_zone",
            postgresql.ENUM(
                "AYIN_CANON",
                "AYIN_WORKING",
                "MANASEK_CANON",
                "MANASEK_WORKING",
                "EXTERNAL_PRIMARY",
                "EXTERNAL_DERIVED",
                "GENERATED_CONTENT",
                name="corpus_zone",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "corpus_zone IN ('MANASEK_WORKING', 'MANASEK_CANON')",
            name=op.f("ck_documents_manasek_document_zone"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("slug", name=op.f("uq_documents_slug")),
        schema="ritual",
    )
    op.create_table(
        "families",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=64), nullable=False),
        sa.Column(
            "family_type",
            postgresql.ENUM(
                "GATE", "BETWEEN", "LIFE", name="family_type", schema="ritual"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_families")),
        sa.UniqueConstraint("family_type", name=op.f("uq_families_family_type")),
        sa.UniqueConstraint("stable_key", name=op.f("uq_families_stable_key")),
        schema="ritual",
    )
    op.create_table(
        "gates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "stable_key",
            postgresql.ENUM(
                "EARTH",
                "WATER",
                "FIRE",
                "WIND",
                "PULL",
                name="gate_key",
                schema="ritual",
            ),
            nullable=False,
        ),
        sa.Column("sequence_position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "sequence_position BETWEEN 1 AND 5", name=op.f("ck_gates_five_gate_slots")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gates")),
        sa.UniqueConstraint(
            "sequence_position", name=op.f("uq_gates_sequence_position")
        ),
        sa.UniqueConstraint("stable_key", name=op.f("uq_gates_stable_key")),
        schema="ritual",
    )
    op.create_table(
        "rituals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rituals")),
        sa.UniqueConstraint("stable_key", name=op.f("uq_rituals_stable_key")),
        schema="ritual",
    )
    op.create_table(
        "safety_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=128), nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM(
                "CONSENT",
                "EXIT",
                "TOUCH",
                "MOVEMENT",
                "BREATH",
                "INTENSITY",
                "INTERPRETATION",
                "GROUP_PRESSURE",
                "DISCLOSURE",
                "AFTERCARE",
                "MUSIC",
                "MENTAL_HEALTH_BOUNDARY",
                name="safety_category",
                schema="ritual",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_safety_rules")),
        sa.UniqueConstraint("stable_key", name=op.f("uq_safety_rules_stable_key")),
        schema="ritual",
    )
    op.create_table(
        "versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("designed_against_ayin_version_id", sa.Uuid(), nullable=False),
        sa.Column("supersedes_version_id", sa.Uuid(), nullable=True),
        sa.Column("semantic_version", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "corpus_zone",
            postgresql.ENUM(
                "AYIN_CANON",
                "AYIN_WORKING",
                "MANASEK_CANON",
                "MANASEK_WORKING",
                "EXTERNAL_PRIMARY",
                "EXTERNAL_DERIVED",
                "GENERATED_CONTENT",
                name="corpus_zone",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("source_file_hash", sa.String(length=64), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "((corpus_zone = 'MANASEK_WORKING' AND status IN ('draft', 'review', 'deprecated')) OR (corpus_zone = 'MANASEK_CANON' AND status IN ('approved', 'superseded', 'deprecated')))",
            name=op.f("ck_versions_status_matches_zone"),
        ),
        sa.CheckConstraint(
            "(status <> 'approved') OR (semantic_version IS NOT NULL AND approved_by IS NOT NULL AND approved_at IS NOT NULL AND effective_from IS NOT NULL AND corpus_zone = 'MANASEK_CANON')",
            name=op.f("ck_versions_approved_metadata"),
        ),
        sa.CheckConstraint(
            "source_file_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_versions_valid_hash")
        ),
        sa.ForeignKeyConstraint(
            ["designed_against_ayin_version_id"],
            ["core.canon_versions.id"],
            name=op.f("fk_versions_designed_against_ayin_version_id_canon_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["ritual.documents.id"],
            name=op.f("fk_versions_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_version_id"],
            ["ritual.versions.id"],
            name=op.f("fk_versions_supersedes_version_id_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_versions")),
        schema="ritual",
    )
    op.create_index(
        op.f("ix_versions_document_id"),
        "versions",
        ["document_id"],
        unique=False,
        schema="ritual",
    )
    op.create_index(
        "uq_ritual_versions_source_identity",
        "versions",
        [
            "document_id",
            "source_file_hash",
            "corpus_zone",
            sa.literal_column("COALESCE(semantic_version, '')"),
        ],
        unique=True,
        schema="ritual",
    )
    op.create_table(
        "version_source_assets",
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_asset_id"],
            ["ops.object_assets.id"],
            name=op.f("fk_version_source_assets_source_asset_id_object_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["ritual.versions.id"],
            name=op.f("fk_version_source_assets_source_version_id_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "source_version_id", name=op.f("pk_version_source_assets")
        ),
        sa.UniqueConstraint(
            "source_version_id",
            "source_asset_id",
            name=op.f("uq_version_source_assets_source_version_id_source_asset_id"),
        ),
        schema="ritual",
    )
    op.create_table(
        "extraction_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.Column("importer_version", sa.String(length=64), nullable=False),
        sa.Column("extractor_name", sa.String(length=64), nullable=False),
        sa.Column("extractor_version", sa.String(length=128), nullable=False),
        sa.Column("normalization_version", sa.String(length=64), nullable=False),
        sa.Column("segmentation_version", sa.String(length=64), nullable=False),
        sa.Column(
            "configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("configuration_hash", sa.String(length=64), nullable=False),
        sa.Column("output_hash", sa.String(length=64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("passage_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "configuration_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_extraction_runs_valid_configuration_hash"),
        ),
        sa.CheckConstraint(
            "output_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_extraction_runs_valid_output_hash"),
        ),
        sa.CheckConstraint(
            "page_count > 0", name=op.f("ck_extraction_runs_positive_page_count")
        ),
        sa.CheckConstraint(
            "passage_count > 0", name=op.f("ck_extraction_runs_positive_passage_count")
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id", "source_asset_id"],
            [
                "ritual.version_source_assets.source_version_id",
                "ritual.version_source_assets.source_asset_id",
            ],
            name=op.f(
                "fk_extraction_runs_source_version_id_source_asset_id_version_source_assets"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_runs")),
        sa.UniqueConstraint(
            "id",
            "source_version_id",
            name=op.f("uq_extraction_runs_id_source_version_id"),
        ),
        sa.UniqueConstraint(
            "source_version_id",
            "importer_version",
            "extractor_name",
            "extractor_version",
            "normalization_version",
            "segmentation_version",
            "configuration_hash",
            name=op.f(
                "uq_extraction_runs_source_version_id_importer_version_extractor_name_extractor_version_normalization_version_segmentation_version_configuration_hash"
            ),
        ),
        schema="ritual",
    )
    op.create_index(
        op.f("ix_extraction_runs_source_version_id"),
        "extraction_runs",
        ["source_version_id"],
        unique=False,
        schema="ritual",
    )
    op.create_table(
        "passages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("printed_page_label", sa.String(length=32), nullable=True),
        sa.Column(
            "heading_path", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("paragraph_index", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "language",
            postgresql.ENUM(
                "fa", "en", "ar", name="language_code", schema="core", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_passages_valid_hash")
        ),
        sa.CheckConstraint(
            "page_number > 0", name=op.f("ck_passages_positive_page_number")
        ),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_passages_positive_sequence")),
        sa.ForeignKeyConstraint(
            ["extraction_run_id", "source_version_id"],
            ["ritual.extraction_runs.id", "ritual.extraction_runs.source_version_id"],
            name=op.f(
                "fk_passages_extraction_run_id_source_version_id_extraction_runs"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id", "source_asset_id"],
            [
                "ritual.version_source_assets.source_version_id",
                "ritual.version_source_assets.source_asset_id",
            ],
            name=op.f(
                "fk_passages_source_version_id_source_asset_id_version_source_assets"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passages")),
        sa.UniqueConstraint(
            "extraction_run_id",
            "sequence",
            name=op.f("uq_passages_extraction_run_id_sequence"),
        ),
        sa.UniqueConstraint(
            "id", "extraction_run_id", name=op.f("uq_passages_id_extraction_run_id")
        ),
        sa.UniqueConstraint(
            "id", "source_version_id", name=op.f("uq_passages_id_source_version_id")
        ),
        schema="ritual",
    )
    op.create_index(
        op.f("ix_passages_extraction_run_id"),
        "passages",
        ["extraction_run_id"],
        unique=False,
        schema="ritual",
    )
    op.create_index(
        op.f("ix_passages_source_version_id"),
        "passages",
        ["source_version_id"],
        unique=False,
        schema="ritual",
    )
    op.create_table(
        "preferred_extraction_runs",
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("selected_by", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("selected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["extraction_run_id", "source_version_id"],
            ["ritual.extraction_runs.id", "ritual.extraction_runs.source_version_id"],
            name=op.f(
                "fk_preferred_extraction_runs_extraction_run_id_source_version_id_extraction_runs"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["ritual.versions.id"],
            name=op.f("fk_preferred_extraction_runs_source_version_id_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "source_version_id", name=op.f("pk_preferred_extraction_runs")
        ),
        schema="ritual",
    )
    op.create_table(
        "architecture_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column(
            "mode",
            postgresql.ENUM(
                "INDIVIDUAL", "COLLECTIVE", name="ritual_mode", schema="ritual"
            ),
            nullable=False,
        ),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "source_version_id"],
            ["ritual.passages.id", "ritual.passages.source_version_id"],
            name=op.f(
                "fk_architecture_versions_source_passage_id_source_version_id_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_architecture_versions")),
        sa.UniqueConstraint(
            "id",
            "source_version_id",
            name=op.f("uq_architecture_versions_id_source_version_id"),
        ),
        sa.UniqueConstraint(
            "source_version_id",
            "mode",
            "version_number",
            name=op.f("uq_architecture_versions_source_version_id_mode_version_number"),
        ),
        schema="ritual",
    )
    op.create_table(
        "family_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("title_fa", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["ritual.families.id"],
            name=op.f("fk_family_versions_family_id_families"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "source_version_id"],
            ["ritual.passages.id", "ritual.passages.source_version_id"],
            name=op.f(
                "fk_family_versions_source_passage_id_source_version_id_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_versions")),
        sa.UniqueConstraint(
            "family_id",
            "source_version_id",
            "version_number",
            name=op.f("uq_family_versions_family_id_source_version_id_version_number"),
        ),
        schema="ritual",
    )
    op.create_table(
        "gate_concept_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("gate_id", sa.Uuid(), nullable=False),
        sa.Column("ayin_concept_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation",
            postgresql.ENUM(
                "EXPERIENTIALIZES",
                "ILLUSTRATES",
                "RELATES_TO",
                "PREPARES_FOR",
                "REFLECTS",
                "DOES_NOT_DEFINE",
                name="concept_relation_type",
                schema="ritual",
            ),
            nullable=False,
        ),
        sa.Column(
            "review_status",
            postgresql.ENUM(
                "open",
                "resolved",
                "dismissed",
                name="ayin_review_status",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ayin_concept_version_id"],
            ["core.ayin_concept_versions.id"],
            name=op.f(
                "fk_gate_concept_links_ayin_concept_version_id_ayin_concept_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["gate_id"],
            ["ritual.gates.id"],
            name=op.f("fk_gate_concept_links_gate_id_gates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "source_version_id"],
            ["ritual.passages.id", "ritual.passages.source_version_id"],
            name=op.f(
                "fk_gate_concept_links_source_passage_id_source_version_id_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gate_concept_links")),
        sa.UniqueConstraint(
            "gate_id",
            "ayin_concept_version_id",
            "relation",
            "source_version_id",
            name=op.f(
                "uq_gate_concept_links_gate_id_ayin_concept_version_id_relation_source_version_id"
            ),
        ),
        schema="ritual",
    )
    op.create_table(
        "gate_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("gate_id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("title_fa", sa.String(length=128), nullable=False),
        sa.Column("symbolic_role", sa.Text(), nullable=False),
        sa.Column("is_bon_component", sa.Boolean(), nullable=False),
        sa.Column("is_metaphysical_element", sa.Boolean(), nullable=False),
        sa.Column("is_personality_category", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "is_bon_component = false", name=op.f("ck_gate_versions_not_bon_component")
        ),
        sa.CheckConstraint(
            "is_metaphysical_element = false",
            name=op.f("ck_gate_versions_not_metaphysical_element"),
        ),
        sa.CheckConstraint(
            "is_personality_category = false",
            name=op.f("ck_gate_versions_not_personality_category"),
        ),
        sa.ForeignKeyConstraint(
            ["gate_id"],
            ["ritual.gates.id"],
            name=op.f("fk_gate_versions_gate_id_gates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "source_version_id"],
            ["ritual.passages.id", "ritual.passages.source_version_id"],
            name=op.f("fk_gate_versions_source_passage_id_source_version_id_passages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gate_versions")),
        sa.UniqueConstraint(
            "gate_id",
            "source_version_id",
            "version_number",
            name=op.f("uq_gate_versions_gate_id_source_version_id_version_number"),
        ),
        schema="ritual",
    )
    op.create_table(
        "safety_rule_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "severity",
            postgresql.ENUM(
                "INFO", "WARNING", "BLOCKING", name="safety_severity", schema="ritual"
            ),
            nullable=False,
        ),
        sa.Column("requirement_text", sa.Text(), nullable=False),
        sa.Column("required_capability", sa.String(length=128), nullable=False),
        sa.Column("prohibited_pattern", sa.Text(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["ritual.safety_rules.id"],
            name=op.f("fk_safety_rule_versions_rule_id_safety_rules"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "source_version_id"],
            ["ritual.passages.id", "ritual.passages.source_version_id"],
            name=op.f(
                "fk_safety_rule_versions_source_passage_id_source_version_id_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_safety_rule_versions")),
        sa.UniqueConstraint(
            "rule_id",
            "source_version_id",
            "version_number",
            name=op.f(
                "uq_safety_rule_versions_rule_id_source_version_id_version_number"
            ),
        ),
        schema="ritual",
    )
    op.create_index(
        op.f("ix_safety_rule_versions_rule_id"),
        "safety_rule_versions",
        ["rule_id"],
        unique=False,
        schema="ritual",
    )
    op.create_table(
        "stages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("architecture_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=64), nullable=False),
        sa.Column("sequence_position", sa.Integer(), nullable=False),
        sa.Column("title_fa", sa.String(length=255), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "sequence_position BETWEEN 1 AND 7",
            name=op.f("ck_stages_seven_stage_slots"),
        ),
        sa.ForeignKeyConstraint(
            ["architecture_version_id", "source_version_id"],
            [
                "ritual.architecture_versions.id",
                "ritual.architecture_versions.source_version_id",
            ],
            name=op.f(
                "fk_stages_architecture_version_id_source_version_id_architecture_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "source_version_id"],
            ["ritual.passages.id", "ritual.passages.source_version_id"],
            name=op.f("fk_stages_source_passage_id_source_version_id_passages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stages")),
        sa.UniqueConstraint(
            "architecture_version_id",
            "sequence_position",
            name=op.f("uq_stages_architecture_version_id_sequence_position"),
        ),
        sa.UniqueConstraint(
            "architecture_version_id",
            "stable_key",
            name=op.f("uq_stages_architecture_version_id_stable_key"),
        ),
        sa.UniqueConstraint(
            "id",
            "architecture_version_id",
            name=op.f("uq_stages_id_architecture_version_id"),
        ),
        schema="ritual",
    )
    op.create_table(
        "ritual_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ritual_id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("architecture_version_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("designed_against_ayin_version_id", sa.Uuid(), nullable=False),
        sa.Column("stage_id", sa.Uuid(), nullable=True),
        sa.Column("gate_id", sa.Uuid(), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "piece_type",
            postgresql.ENUM(
                "GATE", "RETURN", "COLLECTIVE", name="piece_type", schema="ritual"
            ),
            nullable=False,
        ),
        sa.Column(
            "mode",
            postgresql.ENUM(
                "INDIVIDUAL", "COLLECTIVE", name="ritual_mode", schema="ritual"
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("estimated_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("preparation", sa.Text(), nullable=True),
        sa.Column("experiential_instructions", sa.Text(), nullable=False),
        sa.Column("safety_notes", sa.Text(), nullable=False),
        sa.Column("exit_instructions", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(piece_type = 'GATE' AND mode = 'INDIVIDUAL' AND stage_id IS NOT NULL AND gate_id IS NOT NULL) OR (piece_type = 'RETURN' AND mode = 'INDIVIDUAL' AND stage_id IS NOT NULL AND gate_id IS NULL) OR (piece_type = 'COLLECTIVE' AND mode = 'COLLECTIVE' AND stage_id IS NULL AND gate_id IS NULL)",
            name=op.f("ck_ritual_versions_piece_shape"),
        ),
        sa.CheckConstraint(
            "estimated_duration_seconds > 0",
            name=op.f("ck_ritual_versions_positive_duration"),
        ),
        sa.ForeignKeyConstraint(
            ["architecture_version_id", "source_version_id"],
            [
                "ritual.architecture_versions.id",
                "ritual.architecture_versions.source_version_id",
            ],
            name=op.f(
                "fk_ritual_versions_architecture_version_id_source_version_id_architecture_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["designed_against_ayin_version_id"],
            ["core.canon_versions.id"],
            name=op.f(
                "fk_ritual_versions_designed_against_ayin_version_id_canon_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["ritual.families.id"],
            name=op.f("fk_ritual_versions_family_id_families"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["gate_id"],
            ["ritual.gates.id"],
            name=op.f("fk_ritual_versions_gate_id_gates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ritual_id"],
            ["ritual.rituals.id"],
            name=op.f("fk_ritual_versions_ritual_id_rituals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "source_version_id"],
            ["ritual.passages.id", "ritual.passages.source_version_id"],
            name=op.f(
                "fk_ritual_versions_source_passage_id_source_version_id_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id", "architecture_version_id"],
            ["ritual.stages.id", "ritual.stages.architecture_version_id"],
            name=op.f("fk_ritual_versions_stage_id_architecture_version_id_stages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ritual_versions")),
        sa.UniqueConstraint(
            "id", "piece_type", name=op.f("uq_ritual_versions_id_piece_type")
        ),
        sa.UniqueConstraint(
            "id",
            "architecture_version_id",
            "piece_type",
            name=op.f("uq_ritual_versions_id_architecture_version_id_piece_type"),
        ),
        sa.UniqueConstraint(
            "ritual_id",
            "source_version_id",
            "version_number",
            name=op.f("uq_ritual_versions_ritual_id_source_version_id_version_number"),
        ),
        schema="ritual",
    )
    op.create_index(
        op.f("ix_ritual_versions_ritual_id"),
        "ritual_versions",
        ["ritual_id"],
        unique=False,
        schema="ritual",
    )
    op.create_table(
        "stage_concept_link_proposals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stage_id", sa.Uuid(), nullable=False),
        sa.Column("proposed_stable_key", sa.String(length=255), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation",
            postgresql.ENUM(
                "EXPERIENTIALIZES",
                "ILLUSTRATES",
                "RELATES_TO",
                "PREPARES_FOR",
                "REFLECTS",
                "DOES_NOT_DEFINE",
                name="concept_relation_type",
                schema="ritual",
            ),
            nullable=False,
        ),
        sa.Column(
            "review_status",
            postgresql.ENUM(
                "open",
                "resolved",
                "dismissed",
                name="ayin_review_status",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("proposed_by", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_stage_concept_link_proposals_valid_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id"],
            ["ritual.passages.id"],
            name=op.f("fk_stage_concept_link_proposals_source_passage_id_passages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["ritual.stages.id"],
            name=op.f("fk_stage_concept_link_proposals_stage_id_stages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_concept_link_proposals")),
        sa.UniqueConstraint(
            "stage_id",
            "proposed_stable_key",
            "relation",
            name=op.f(
                "uq_stage_concept_link_proposals_stage_id_proposed_stable_key_relation"
            ),
        ),
        schema="ritual",
    )
    op.create_table(
        "stage_concept_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stage_id", sa.Uuid(), nullable=False),
        sa.Column("ayin_concept_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation",
            postgresql.ENUM(
                "EXPERIENTIALIZES",
                "ILLUSTRATES",
                "RELATES_TO",
                "PREPARES_FOR",
                "REFLECTS",
                "DOES_NOT_DEFINE",
                name="concept_relation_type",
                schema="ritual",
            ),
            nullable=False,
        ),
        sa.Column(
            "review_status",
            postgresql.ENUM(
                "open",
                "resolved",
                "dismissed",
                name="ayin_review_status",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ayin_concept_version_id"],
            ["core.ayin_concept_versions.id"],
            name=op.f(
                "fk_stage_concept_links_ayin_concept_version_id_ayin_concept_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id"],
            ["ritual.passages.id"],
            name=op.f("fk_stage_concept_links_source_passage_id_passages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["ritual.stages.id"],
            name=op.f("fk_stage_concept_links_stage_id_stages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_concept_links")),
        sa.UniqueConstraint(
            "stage_id",
            "ayin_concept_version_id",
            "relation",
            name=op.f(
                "uq_stage_concept_links_stage_id_ayin_concept_version_id_relation"
            ),
        ),
        schema="ritual",
    )
    op.create_table(
        "concept_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ritual_version_id", sa.Uuid(), nullable=False),
        sa.Column("ayin_concept_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation",
            postgresql.ENUM(
                "EXPERIENTIALIZES",
                "ILLUSTRATES",
                "RELATES_TO",
                "PREPARES_FOR",
                "REFLECTS",
                "DOES_NOT_DEFINE",
                name="concept_relation_type",
                schema="ritual",
            ),
            nullable=False,
        ),
        sa.Column(
            "review_status",
            postgresql.ENUM(
                "open",
                "resolved",
                "dismissed",
                name="ayin_review_status",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("proposed_by", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_concept_links_valid_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["ayin_concept_version_id"],
            ["core.ayin_concept_versions.id"],
            name=op.f("fk_concept_links_ayin_concept_version_id_ayin_concept_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ritual_version_id"],
            ["ritual.ritual_versions.id"],
            name=op.f("fk_concept_links_ritual_version_id_ritual_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id"],
            ["ritual.passages.id"],
            name=op.f("fk_concept_links_source_passage_id_passages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concept_links")),
        sa.UniqueConstraint(
            "ritual_version_id",
            "ayin_concept_version_id",
            "relation",
            name=op.f(
                "uq_concept_links_ritual_version_id_ayin_concept_version_id_relation"
            ),
        ),
        schema="ritual",
    )
    op.create_table(
        "cues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ritual_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "cue_type",
            postgresql.ENUM(
                "narration",
                "whisper",
                "silence",
                "movement",
                "attention",
                "transition",
                "grounding",
                "music_instruction",
                "safety_instruction",
                name="cue_type",
                schema="ritual",
            ),
            nullable=False,
        ),
        sa.Column("start_seconds", sa.Integer(), nullable=True),
        sa.Column("end_seconds", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "language",
            postgresql.ENUM(
                "fa", "en", "ar", name="language_code", schema="core", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("optional", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "end_seconds IS NULL OR (start_seconds IS NOT NULL AND end_seconds > start_seconds)",
            name=op.f("ck_cues_valid_interval"),
        ),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_cues_positive_sequence")),
        sa.CheckConstraint(
            "start_seconds IS NULL OR start_seconds >= 0",
            name=op.f("ck_cues_nonnegative_start"),
        ),
        sa.ForeignKeyConstraint(
            ["ritual_version_id"],
            ["ritual.ritual_versions.id"],
            name=op.f("fk_cues_ritual_version_id_ritual_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id"],
            ["ritual.passages.id"],
            name=op.f("fk_cues_source_passage_id_passages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cues")),
        sa.UniqueConstraint(
            "ritual_version_id",
            "sequence",
            name=op.f("uq_cues_ritual_version_id_sequence"),
        ),
        schema="ritual",
    )
    op.create_index(
        op.f("ix_cues_ritual_version_id"),
        "cues",
        ["ritual_version_id"],
        unique=False,
        schema="ritual",
    )
    op.create_table(
        "localizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ritual_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column(
            "language",
            postgresql.ENUM(
                "fa", "en", "ar", name="language_code", schema="core", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("narration_text", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("safety_language", sa.Text(), nullable=False),
        sa.Column("terminology_version", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ritual_version_id"],
            ["ritual.ritual_versions.id"],
            name=op.f("fk_localizations_ritual_version_id_ritual_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id"],
            ["ritual.passages.id"],
            name=op.f("fk_localizations_source_passage_id_passages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_localizations")),
        sa.UniqueConstraint(
            "ritual_version_id",
            "language",
            "version_number",
            name=op.f("uq_localizations_ritual_version_id_language_version_number"),
        ),
        schema="ritual",
    )
    op.create_index(
        op.f("ix_localizations_ritual_version_id"),
        "localizations",
        ["ritual_version_id"],
        unique=False,
        schema="ritual",
    )
    op.create_table(
        "music_specifications",
        sa.Column("ritual_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("sonic_family", sa.Text(), nullable=False),
        sa.Column("emotional_arc", sa.Text(), nullable=False),
        sa.Column("intensity_profile", sa.Text(), nullable=False),
        sa.Column(
            "prohibited_features",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("transition_requirements", sa.Text(), nullable=False),
        sa.Column("ending_requirements", sa.Text(), nullable=False),
        sa.Column("original_prompt", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "duration_seconds > 0",
            name=op.f("ck_music_specifications_positive_duration"),
        ),
        sa.ForeignKeyConstraint(
            ["ritual_version_id"],
            ["ritual.ritual_versions.id"],
            name=op.f("fk_music_specifications_ritual_version_id_ritual_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id"],
            ["ritual.passages.id"],
            name=op.f("fk_music_specifications_source_passage_id_passages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "ritual_version_id", name=op.f("pk_music_specifications")
        ),
        schema="ritual",
    )
    op.create_table(
        "returns",
        sa.Column("ritual_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "piece_type",
            postgresql.ENUM(
                "GATE", "RETURN", "COLLECTIVE", name="piece_type", schema="ritual"
            ),
            nullable=False,
        ),
        sa.Column("integration_function", sa.Text(), nullable=False),
        sa.Column("ordinary_reorientation", sa.Boolean(), nullable=False),
        sa.Column("lowers_interpretive_intensity", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "piece_type = 'RETURN'", name=op.f("ck_returns_return_not_gate")
        ),
        sa.ForeignKeyConstraint(
            ["ritual_version_id", "piece_type"],
            ["ritual.ritual_versions.id", "ritual.ritual_versions.piece_type"],
            name=op.f("fk_returns_ritual_version_id_piece_type_ritual_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("ritual_version_id", name=op.f("pk_returns")),
        schema="ritual",
    )
    op.create_table(
        "review_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("ritual_version_id", sa.Uuid(), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            postgresql.ENUM(
                "uncertain_ritual_boundary",
                "uncertain_heading",
                "extraction_corruption",
                "unclear_timing",
                "ambiguous_gate_assignment",
                "uncertain_stage_assignment",
                "uncertain_ayin_concept_link",
                "safety_concern",
                "music_prompt_parsing_issue",
                "collective_individual_ambiguity",
                name="review_reason",
                schema="ritual",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "open",
                "resolved",
                "dismissed",
                name="ayin_review_status",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'open' AND reviewed_at IS NULL) OR (status IN ('resolved', 'dismissed') AND reviewed_at IS NOT NULL)",
            name=op.f("ck_review_flags_review_completion_metadata"),
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id", "source_version_id"],
            ["ritual.extraction_runs.id", "ritual.extraction_runs.source_version_id"],
            name=op.f(
                "fk_review_flags_extraction_run_id_source_version_id_extraction_runs"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ritual_version_id"],
            ["ritual.ritual_versions.id"],
            name=op.f("fk_review_flags_ritual_version_id_ritual_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id"],
            ["ritual.passages.id"],
            name=op.f("fk_review_flags_source_passage_id_passages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_flags")),
        schema="ritual",
    )
    op.create_index(
        op.f("ix_review_flags_extraction_run_id"),
        "review_flags",
        ["extraction_run_id"],
        unique=False,
        schema="ritual",
    )
    op.create_table(
        "ritual_sequence_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("architecture_version_id", sa.Uuid(), nullable=False),
        sa.Column("stage_id", sa.Uuid(), nullable=True),
        sa.Column("ritual_version_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_position", sa.Integer(), nullable=False),
        sa.Column("stage_sequence_position", sa.Integer(), nullable=True),
        sa.Column(
            "slot_kind",
            postgresql.ENUM(
                "GATE", "RETURN", "COLLECTIVE", name="piece_type", schema="ritual"
            ),
            nullable=False,
        ),
        sa.Column("gate_position", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(slot_kind = 'GATE' AND stage_id IS NOT NULL AND stage_sequence_position BETWEEN 1 AND 5 AND gate_position BETWEEN 1 AND 5) OR (slot_kind = 'RETURN' AND stage_id IS NOT NULL AND stage_sequence_position = 6 AND gate_position IS NULL) OR (slot_kind = 'COLLECTIVE' AND stage_id IS NULL AND stage_sequence_position IS NULL AND gate_position IS NULL)",
            name=op.f("ck_ritual_sequence_items_sequence_slot_shape"),
        ),
        sa.CheckConstraint(
            "sequence_position > 0",
            name=op.f("ck_ritual_sequence_items_positive_sequence"),
        ),
        sa.ForeignKeyConstraint(
            ["ritual_version_id", "architecture_version_id", "slot_kind"],
            [
                "ritual.ritual_versions.id",
                "ritual.ritual_versions.architecture_version_id",
                "ritual.ritual_versions.piece_type",
            ],
            name=op.f(
                "fk_ritual_sequence_items_ritual_version_id_architecture_version_id_slot_kind_ritual_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id", "architecture_version_id"],
            ["ritual.stages.id", "ritual.stages.architecture_version_id"],
            name=op.f(
                "fk_ritual_sequence_items_stage_id_architecture_version_id_stages"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ritual_sequence_items")),
        sa.UniqueConstraint(
            "architecture_version_id",
            "sequence_position",
            name=op.f(
                "uq_ritual_sequence_items_architecture_version_id_sequence_position"
            ),
        ),
        sa.UniqueConstraint(
            "ritual_version_id", name=op.f("uq_ritual_sequence_items_ritual_version_id")
        ),
        sa.UniqueConstraint(
            "stage_id",
            "stage_sequence_position",
            name=op.f("uq_ritual_sequence_items_stage_id_stage_sequence_position"),
        ),
        schema="ritual",
    )
    op.create_index(
        "uq_ritual_sequence_items_one_return_per_stage",
        "ritual_sequence_items",
        ["stage_id"],
        unique=True,
        schema="ritual",
        postgresql_where=sa.text("slot_kind = 'RETURN'"),
    )
    op.create_index(
        "uq_ritual_sequence_items_stage_gate_position",
        "ritual_sequence_items",
        ["stage_id", "gate_position"],
        unique=True,
        schema="ritual",
        postgresql_where=sa.text("slot_kind = 'GATE'"),
    )
    op.create_table(
        "ritual_version_safety_rules",
        sa.Column("ritual_version_id", sa.Uuid(), nullable=False),
        sa.Column("safety_rule_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ritual_version_id"],
            ["ritual.ritual_versions.id"],
            name=op.f(
                "fk_ritual_version_safety_rules_ritual_version_id_ritual_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["safety_rule_version_id"],
            ["ritual.safety_rule_versions.id"],
            name=op.f(
                "fk_ritual_version_safety_rules_safety_rule_version_id_safety_rule_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "ritual_version_id",
            "safety_rule_version_id",
            name=op.f("pk_ritual_version_safety_rules"),
        ),
        schema="ritual",
    )
    op.create_table(
        "safety_validation_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ritual_version_id", sa.Uuid(), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("publishable", sa.Boolean(), nullable=False),
        sa.Column("issues", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validator_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ritual_version_id"],
            ["ritual.ritual_versions.id"],
            name=op.f("fk_safety_validation_results_ritual_version_id_ritual_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_safety_validation_results")),
        schema="ritual",
    )
    op.create_index(
        op.f("ix_safety_validation_results_ritual_version_id"),
        "safety_validation_results",
        ["ritual_version_id"],
        unique=False,
        schema="ritual",
    )
    op.create_table(
        "localization_safety_rules",
        sa.Column("localization_id", sa.Uuid(), nullable=False),
        sa.Column("safety_rule_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["localization_id"],
            ["ritual.localizations.id"],
            name=op.f("fk_localization_safety_rules_localization_id_localizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["safety_rule_version_id"],
            ["ritual.safety_rule_versions.id"],
            name=op.f(
                "fk_localization_safety_rules_safety_rule_version_id_safety_rule_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "localization_id",
            "safety_rule_version_id",
            name=op.f("pk_localization_safety_rules"),
        ),
        schema="ritual",
    )
    op.execute(
        """
        CREATE FUNCTION ritual.assert_architecture_complete(target_id uuid)
        RETURNS void LANGUAGE plpgsql AS $$
        DECLARE
            architecture_mode ritual.ritual_mode;
            architecture_status core.editorial_status;
            source_zone core.corpus_zone;
            stage_total integer;
            item_total integer;
            invalid_stages integer;
            invalid_gate_slots integer;
        BEGIN
            SELECT architecture.mode, architecture.status, source.corpus_zone
            INTO architecture_mode, architecture_status, source_zone
            FROM ritual.architecture_versions architecture
            JOIN ritual.versions source
              ON source.id = architecture.source_version_id
            WHERE architecture.id = target_id;
            IF NOT FOUND OR architecture_status <> 'approved' THEN
                RETURN;
            END IF;
            IF source_zone <> 'MANASEK_CANON' THEN
                RAISE EXCEPTION
                    'approved architecture requires MANASEK_CANON source';
            END IF;

            SELECT count(*) INTO stage_total FROM ritual.stages
            WHERE architecture_version_id = target_id;
            SELECT count(*) INTO item_total FROM ritual.ritual_sequence_items
            WHERE architecture_version_id = target_id;

            IF architecture_mode = 'INDIVIDUAL' THEN
                IF stage_total <> 7 OR item_total <> 42 THEN
                    RAISE EXCEPTION
                        'approved individual architecture requires 7 stages and 42 pieces';
                END IF;
                SELECT count(*) INTO invalid_stages
                FROM ritual.stages s
                WHERE s.architecture_version_id = target_id
                  AND (
                    (SELECT count(*) FROM ritual.ritual_sequence_items i
                     WHERE i.stage_id = s.id AND i.slot_kind = 'GATE') <> 5
                    OR
                    (SELECT count(*) FROM ritual.ritual_sequence_items i
                     WHERE i.stage_id = s.id AND i.slot_kind = 'RETURN') <> 1
                  );
                IF invalid_stages <> 0 THEN
                    RAISE EXCEPTION
                        'each approved individual stage requires five gates and one Return';
                END IF;
                SELECT count(*) INTO invalid_gate_slots
                FROM ritual.ritual_sequence_items i
                JOIN ritual.ritual_versions rv ON rv.id = i.ritual_version_id
                JOIN ritual.gates g ON g.id = rv.gate_id
                WHERE i.architecture_version_id = target_id
                  AND i.slot_kind = 'GATE'
                  AND i.gate_position <> g.sequence_position;
                IF invalid_gate_slots <> 0 THEN
                    RAISE EXCEPTION 'gate slot does not match the gate identity';
                END IF;
            ELSIF architecture_mode = 'COLLECTIVE' THEN
                IF stage_total <> 0 OR item_total < 1 OR EXISTS (
                    SELECT 1 FROM ritual.ritual_sequence_items
                    WHERE architecture_version_id = target_id
                      AND slot_kind <> 'COLLECTIVE'
                ) THEN
                    RAISE EXCEPTION
                        'approved collective architecture must remain structurally separate';
                END IF;
            END IF;
        END;
        $$;

        CREATE FUNCTION ritual.check_architecture_row()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                PERFORM ritual.assert_architecture_complete(OLD.id);
            ELSE
                PERFORM ritual.assert_architecture_complete(NEW.id);
            END IF;
            RETURN NULL;
        END;
        $$;

        CREATE FUNCTION ritual.check_architecture_child()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                PERFORM ritual.assert_architecture_complete(OLD.architecture_version_id);
            ELSE
                PERFORM ritual.assert_architecture_complete(NEW.architecture_version_id);
                IF TG_OP = 'UPDATE'
                   AND OLD.architecture_version_id <> NEW.architecture_version_id THEN
                    PERFORM ritual.assert_architecture_complete(OLD.architecture_version_id);
                END IF;
            END IF;
            RETURN NULL;
        END;
        $$;

        CREATE CONSTRAINT TRIGGER architecture_complete_from_architecture
        AFTER INSERT OR UPDATE ON ritual.architecture_versions
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION ritual.check_architecture_row();

        CREATE CONSTRAINT TRIGGER architecture_complete_from_stages
        AFTER INSERT OR UPDATE OR DELETE ON ritual.stages
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION ritual.check_architecture_child();

        CREATE CONSTRAINT TRIGGER architecture_complete_from_sequence
        AFTER INSERT OR UPDATE OR DELETE ON ritual.ritual_sequence_items
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION ritual.check_architecture_child();

        CREATE FUNCTION ritual.assert_ritual_publishable(target_id uuid)
        RETURNS void LANGUAGE plpgsql AS $$
        DECLARE
            ritual_status core.editorial_status;
            source_zone core.corpus_zone;
            total_rules integer;
            bound_approved_rules integer;
        BEGIN
            SELECT rv.status, sv.corpus_zone INTO ritual_status, source_zone
            FROM ritual.ritual_versions rv
            JOIN ritual.versions sv ON sv.id = rv.source_version_id
            WHERE rv.id = target_id;
            IF NOT FOUND OR ritual_status <> 'approved' THEN
                RETURN;
            END IF;
            IF source_zone <> 'MANASEK_CANON' THEN
                RAISE EXCEPTION 'approved ritual requires MANASEK_CANON source';
            END IF;
            SELECT count(*) INTO total_rules
            FROM ritual.safety_rules rule
            WHERE EXISTS (
                SELECT 1 FROM ritual.safety_rule_versions version
                WHERE version.safety_rule_id = rule.id
                  AND version.status = 'approved'
            );
            SELECT count(DISTINCT version.safety_rule_id)
            INTO bound_approved_rules
            FROM ritual.ritual_version_safety_rules binding
            JOIN ritual.safety_rule_versions version
              ON version.id = binding.safety_rule_version_id
            WHERE binding.ritual_version_id = target_id
              AND version.status = 'approved';
            IF total_rules = 0 OR bound_approved_rules <> total_rules THEN
                RAISE EXCEPTION
                    'approved ritual requires every current approved safety rule version';
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM ritual.safety_validation_results
                WHERE ritual_version_id = target_id AND valid = true
            ) THEN
                RAISE EXCEPTION 'approved ritual requires a passing safety validation';
            END IF;
            IF EXISTS (
                SELECT 1 FROM ritual.review_flags
                WHERE ritual_version_id = target_id
                  AND reason = 'safety_concern' AND status = 'open'
            ) THEN
                RAISE EXCEPTION 'open blocking safety review prevents approval';
            END IF;
        END;
        $$;

        CREATE FUNCTION ritual.check_ritual_publishable_row()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_TABLE_NAME = 'ritual_versions' THEN
                PERFORM ritual.assert_ritual_publishable(
                    CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END
                );
            ELSE
                PERFORM ritual.assert_ritual_publishable(
                    CASE WHEN TG_OP = 'DELETE' THEN OLD.ritual_version_id
                         ELSE NEW.ritual_version_id END
                );
            END IF;
            RETURN NULL;
        END;
        $$;

        CREATE CONSTRAINT TRIGGER ritual_publishable_from_version
        AFTER INSERT OR UPDATE ON ritual.ritual_versions
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION ritual.check_ritual_publishable_row();

        CREATE CONSTRAINT TRIGGER ritual_publishable_from_safety_binding
        AFTER INSERT OR UPDATE OR DELETE ON ritual.ritual_version_safety_rules
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION ritual.check_ritual_publishable_row();

        CREATE CONSTRAINT TRIGGER ritual_publishable_from_validation
        AFTER INSERT OR UPDATE OR DELETE ON ritual.safety_validation_results
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION ritual.check_ritual_publishable_row();

        CREATE CONSTRAINT TRIGGER ritual_publishable_from_review_flag
        AFTER INSERT OR UPDATE OR DELETE ON ritual.review_flags
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION ritual.check_ritual_publishable_row();

        CREATE FUNCTION ritual.check_all_approved_rituals()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            approved_id uuid;
        BEGIN
            FOR approved_id IN
                SELECT id FROM ritual.ritual_versions WHERE status = 'approved'
            LOOP
                PERFORM ritual.assert_ritual_publishable(approved_id);
            END LOOP;
            RETURN NULL;
        END;
        $$;

        CREATE CONSTRAINT TRIGGER approved_rituals_follow_safety_versions
        AFTER INSERT OR UPDATE OR DELETE ON ritual.safety_rule_versions
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION ritual.check_all_approved_rituals();

        CREATE FUNCTION ritual.assert_localization_safe(target_id uuid)
        RETURNS void LANGUAGE plpgsql AS $$
        DECLARE
            localization_status core.editorial_status;
            parent_ritual_id uuid;
        BEGIN
            SELECT status, ritual_version_id
            INTO localization_status, parent_ritual_id
            FROM ritual.localizations WHERE id = target_id;
            IF NOT FOUND OR localization_status <> 'approved' THEN
                RETURN;
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM ritual.ritual_versions
                WHERE id = parent_ritual_id AND status = 'approved'
            ) THEN
                RAISE EXCEPTION
                    'approved localization requires an approved ritual version';
            END IF;
            IF EXISTS (
                (SELECT safety_rule_version_id
                 FROM ritual.ritual_version_safety_rules
                 WHERE ritual_version_id = parent_ritual_id)
                EXCEPT
                (SELECT safety_rule_version_id
                 FROM ritual.localization_safety_rules
                 WHERE localization_id = target_id)
            ) OR EXISTS (
                (SELECT safety_rule_version_id
                 FROM ritual.localization_safety_rules
                 WHERE localization_id = target_id)
                EXCEPT
                (SELECT safety_rule_version_id
                 FROM ritual.ritual_version_safety_rules
                 WHERE ritual_version_id = parent_ritual_id)
            ) THEN
                RAISE EXCEPTION
                    'approved localization must preserve exact ritual safety bindings';
            END IF;
        END;
        $$;

        CREATE FUNCTION ritual.check_localization_safe_row()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_TABLE_NAME = 'localizations' THEN
                PERFORM ritual.assert_localization_safe(
                    CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END
                );
            ELSE
                PERFORM ritual.assert_localization_safe(
                    CASE WHEN TG_OP = 'DELETE' THEN OLD.localization_id
                         ELSE NEW.localization_id END
                );
            END IF;
            RETURN NULL;
        END;
        $$;

        CREATE CONSTRAINT TRIGGER localization_safe_from_localization
        AFTER INSERT OR UPDATE ON ritual.localizations
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION ritual.check_localization_safe_row();

        CREATE CONSTRAINT TRIGGER localization_safe_from_bindings
        AFTER INSERT OR UPDATE OR DELETE ON ritual.localization_safety_rules
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION ritual.check_localization_safe_row();

        CREATE FUNCTION ritual.prevent_approved_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.status = 'approved' THEN
                RAISE EXCEPTION 'approved ritual records are immutable; create a version';
            END IF;
            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE FUNCTION ritual.prevent_source_zone_change()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.corpus_zone <> NEW.corpus_zone THEN
                RAISE EXCEPTION
                    'Canon promotion must create a new source version';
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE FUNCTION ritual.require_canon_for_child_approval()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.status = 'approved' AND NOT EXISTS (
                SELECT 1 FROM ritual.versions
                WHERE id = NEW.source_version_id
                  AND corpus_zone = 'MANASEK_CANON'
                  AND status = 'approved'
            ) THEN
                RAISE EXCEPTION
                    'approved ritual content requires an approved MANASEK_CANON source';
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE FUNCTION ritual.prevent_approved_architecture_child_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            parent_id uuid;
        BEGIN
            parent_id := CASE WHEN TG_OP = 'DELETE'
                THEN OLD.architecture_version_id ELSE NEW.architecture_version_id END;
            IF EXISTS (
                SELECT 1 FROM ritual.architecture_versions
                WHERE id = parent_id AND status = 'approved'
            ) THEN
                RAISE EXCEPTION
                    'approved architecture children are immutable; create a version';
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END;
        $$;

        CREATE FUNCTION ritual.prevent_approved_ritual_child_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            parent_id uuid;
        BEGIN
            parent_id := CASE WHEN TG_OP = 'DELETE'
                THEN OLD.ritual_version_id ELSE NEW.ritual_version_id END;
            IF EXISTS (
                SELECT 1 FROM ritual.ritual_versions
                WHERE id = parent_id AND status = 'approved'
            ) THEN
                RAISE EXCEPTION
                    'approved ritual children are immutable; create a version';
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END;
        $$;

        CREATE FUNCTION ritual.prevent_approved_localization_binding_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            parent_id uuid;
        BEGIN
            parent_id := CASE WHEN TG_OP = 'DELETE'
                THEN OLD.localization_id ELSE NEW.localization_id END;
            IF EXISTS (
                SELECT 1 FROM ritual.localizations
                WHERE id = parent_id AND status = 'approved'
            ) THEN
                RAISE EXCEPTION
                    'approved localization safety bindings are immutable; create a version';
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END;
        $$;

        CREATE TRIGGER immutable_approved_source_versions
        BEFORE UPDATE OR DELETE ON ritual.versions FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_approved_mutation();
        CREATE TRIGGER source_zone_is_immutable
        BEFORE UPDATE ON ritual.versions FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_source_zone_change();
        CREATE TRIGGER immutable_approved_ritual_versions
        BEFORE UPDATE OR DELETE ON ritual.ritual_versions FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_approved_mutation();
        CREATE TRIGGER immutable_approved_architecture_versions
        BEFORE UPDATE OR DELETE ON ritual.architecture_versions FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_approved_mutation();
        CREATE TRIGGER immutable_approved_localizations
        BEFORE UPDATE OR DELETE ON ritual.localizations FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_approved_mutation();
        CREATE TRIGGER immutable_approved_safety_rule_versions
        BEFORE UPDATE OR DELETE ON ritual.safety_rule_versions FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_approved_mutation();
        CREATE TRIGGER immutable_approved_gate_versions
        BEFORE UPDATE OR DELETE ON ritual.gate_versions FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_approved_mutation();
        CREATE TRIGGER immutable_approved_family_versions
        BEFORE UPDATE OR DELETE ON ritual.family_versions FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_approved_mutation();
        CREATE TRIGGER family_approval_requires_canon
        BEFORE INSERT OR UPDATE ON ritual.family_versions FOR EACH ROW
        EXECUTE FUNCTION ritual.require_canon_for_child_approval();
        CREATE TRIGGER gate_approval_requires_canon
        BEFORE INSERT OR UPDATE ON ritual.gate_versions FOR EACH ROW
        EXECUTE FUNCTION ritual.require_canon_for_child_approval();
        CREATE TRIGGER safety_approval_requires_canon
        BEFORE INSERT OR UPDATE ON ritual.safety_rule_versions FOR EACH ROW
        EXECUTE FUNCTION ritual.require_canon_for_child_approval();
        CREATE TRIGGER immutable_approved_architecture_stages
        BEFORE INSERT OR UPDATE OR DELETE ON ritual.stages FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_approved_architecture_child_mutation();
        CREATE TRIGGER immutable_approved_architecture_sequence
        BEFORE INSERT OR UPDATE OR DELETE ON ritual.ritual_sequence_items FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_approved_architecture_child_mutation();
        CREATE TRIGGER immutable_approved_ritual_cues
        BEFORE INSERT OR UPDATE OR DELETE ON ritual.cues FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_approved_ritual_child_mutation();
        CREATE TRIGGER immutable_approved_ritual_music
        BEFORE INSERT OR UPDATE OR DELETE ON ritual.music_specifications FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_approved_ritual_child_mutation();
        CREATE TRIGGER immutable_approved_ritual_safety_bindings
        BEFORE INSERT OR UPDATE OR DELETE ON ritual.ritual_version_safety_rules
        FOR EACH ROW EXECUTE FUNCTION ritual.prevent_approved_ritual_child_mutation();
        CREATE TRIGGER immutable_approved_localization_safety_bindings
        BEFORE INSERT OR UPDATE OR DELETE ON ritual.localization_safety_rules
        FOR EACH ROW
        EXECUTE FUNCTION ritual.prevent_approved_localization_binding_mutation();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP TRIGGER IF EXISTS immutable_approved_family_versions
            ON ritual.family_versions;
        DROP TRIGGER IF EXISTS immutable_approved_localization_safety_bindings
            ON ritual.localization_safety_rules;
        DROP TRIGGER IF EXISTS immutable_approved_ritual_safety_bindings
            ON ritual.ritual_version_safety_rules;
        DROP TRIGGER IF EXISTS immutable_approved_ritual_music
            ON ritual.music_specifications;
        DROP TRIGGER IF EXISTS immutable_approved_ritual_cues
            ON ritual.cues;
        DROP TRIGGER IF EXISTS immutable_approved_architecture_sequence
            ON ritual.ritual_sequence_items;
        DROP TRIGGER IF EXISTS immutable_approved_architecture_stages
            ON ritual.stages;
        DROP TRIGGER IF EXISTS safety_approval_requires_canon
            ON ritual.safety_rule_versions;
        DROP TRIGGER IF EXISTS gate_approval_requires_canon
            ON ritual.gate_versions;
        DROP TRIGGER IF EXISTS family_approval_requires_canon
            ON ritual.family_versions;
        DROP TRIGGER IF EXISTS immutable_approved_gate_versions
            ON ritual.gate_versions;
        DROP TRIGGER IF EXISTS immutable_approved_safety_rule_versions
            ON ritual.safety_rule_versions;
        DROP TRIGGER IF EXISTS immutable_approved_ritual_versions
            ON ritual.ritual_versions;
        DROP TRIGGER IF EXISTS immutable_approved_localizations
            ON ritual.localizations;
        DROP TRIGGER IF EXISTS immutable_approved_architecture_versions
            ON ritual.architecture_versions;
        DROP TRIGGER IF EXISTS immutable_approved_source_versions
            ON ritual.versions;
        DROP TRIGGER IF EXISTS source_zone_is_immutable
            ON ritual.versions;
        DROP TRIGGER IF EXISTS ritual_publishable_from_validation
            ON ritual.safety_validation_results;
        DROP TRIGGER IF EXISTS approved_rituals_follow_safety_versions
            ON ritual.safety_rule_versions;
        DROP TRIGGER IF EXISTS ritual_publishable_from_review_flag
            ON ritual.review_flags;
        DROP TRIGGER IF EXISTS localization_safe_from_bindings
            ON ritual.localization_safety_rules;
        DROP TRIGGER IF EXISTS localization_safe_from_localization
            ON ritual.localizations;
        DROP TRIGGER IF EXISTS ritual_publishable_from_safety_binding
            ON ritual.ritual_version_safety_rules;
        DROP TRIGGER IF EXISTS ritual_publishable_from_version
            ON ritual.ritual_versions;
        DROP TRIGGER IF EXISTS architecture_complete_from_sequence
            ON ritual.ritual_sequence_items;
        DROP TRIGGER IF EXISTS architecture_complete_from_stages
            ON ritual.stages;
        DROP TRIGGER IF EXISTS architecture_complete_from_architecture
            ON ritual.architecture_versions;
        DROP FUNCTION IF EXISTS ritual.prevent_approved_mutation();
        DROP FUNCTION IF EXISTS ritual.prevent_approved_localization_binding_mutation();
        DROP FUNCTION IF EXISTS ritual.prevent_approved_ritual_child_mutation();
        DROP FUNCTION IF EXISTS ritual.prevent_approved_architecture_child_mutation();
        DROP FUNCTION IF EXISTS ritual.require_canon_for_child_approval();
        DROP FUNCTION IF EXISTS ritual.prevent_source_zone_change();
        DROP FUNCTION IF EXISTS ritual.check_localization_safe_row();
        DROP FUNCTION IF EXISTS ritual.assert_localization_safe(uuid);
        DROP FUNCTION IF EXISTS ritual.check_ritual_publishable_row();
        DROP FUNCTION IF EXISTS ritual.check_all_approved_rituals();
        DROP FUNCTION IF EXISTS ritual.assert_ritual_publishable(uuid);
        DROP FUNCTION IF EXISTS ritual.check_architecture_child();
        DROP FUNCTION IF EXISTS ritual.check_architecture_row();
        DROP FUNCTION IF EXISTS ritual.assert_architecture_complete(uuid);
        """
    )
    op.drop_table("localization_safety_rules", schema="ritual")
    op.drop_index(
        op.f("ix_safety_validation_results_ritual_version_id"),
        table_name="safety_validation_results",
        schema="ritual",
    )
    op.drop_table("safety_validation_results", schema="ritual")
    op.drop_table("ritual_version_safety_rules", schema="ritual")
    op.drop_index(
        "uq_ritual_sequence_items_stage_gate_position",
        table_name="ritual_sequence_items",
        schema="ritual",
        postgresql_where=sa.text("slot_kind = 'GATE'"),
    )
    op.drop_index(
        "uq_ritual_sequence_items_one_return_per_stage",
        table_name="ritual_sequence_items",
        schema="ritual",
        postgresql_where=sa.text("slot_kind = 'RETURN'"),
    )
    op.drop_table("ritual_sequence_items", schema="ritual")
    op.drop_index(
        op.f("ix_review_flags_extraction_run_id"),
        table_name="review_flags",
        schema="ritual",
    )
    op.drop_table("review_flags", schema="ritual")
    op.drop_table("returns", schema="ritual")
    op.drop_table("music_specifications", schema="ritual")
    op.drop_index(
        op.f("ix_localizations_ritual_version_id"),
        table_name="localizations",
        schema="ritual",
    )
    op.drop_table("localizations", schema="ritual")
    op.drop_index(op.f("ix_cues_ritual_version_id"), table_name="cues", schema="ritual")
    op.drop_table("cues", schema="ritual")
    op.drop_table("concept_links", schema="ritual")
    op.drop_table("stage_concept_links", schema="ritual")
    op.drop_table("stage_concept_link_proposals", schema="ritual")
    op.drop_index(
        op.f("ix_ritual_versions_ritual_id"),
        table_name="ritual_versions",
        schema="ritual",
    )
    op.drop_table("ritual_versions", schema="ritual")
    op.drop_table("stages", schema="ritual")
    op.drop_index(
        op.f("ix_safety_rule_versions_rule_id"),
        table_name="safety_rule_versions",
        schema="ritual",
    )
    op.drop_table("safety_rule_versions", schema="ritual")
    op.drop_table("gate_versions", schema="ritual")
    op.drop_table("gate_concept_links", schema="ritual")
    op.drop_table("family_versions", schema="ritual")
    op.drop_table("architecture_versions", schema="ritual")
    op.drop_table("preferred_extraction_runs", schema="ritual")
    op.drop_index(
        op.f("ix_passages_source_version_id"), table_name="passages", schema="ritual"
    )
    op.drop_index(
        op.f("ix_passages_extraction_run_id"), table_name="passages", schema="ritual"
    )
    op.drop_table("passages", schema="ritual")
    op.drop_index(
        op.f("ix_extraction_runs_source_version_id"),
        table_name="extraction_runs",
        schema="ritual",
    )
    op.drop_table("extraction_runs", schema="ritual")
    op.drop_table("version_source_assets", schema="ritual")
    op.drop_index(
        "uq_ritual_versions_source_identity", table_name="versions", schema="ritual"
    )
    op.drop_index(
        op.f("ix_versions_document_id"), table_name="versions", schema="ritual"
    )
    op.drop_table("versions", schema="ritual")
    op.drop_table("safety_rules", schema="ritual")
    op.drop_table("rituals", schema="ritual")
    op.drop_table("gates", schema="ritual")
    op.drop_table("families", schema="ritual")
    op.drop_table("documents", schema="ritual")
    op.execute(
        """
        DROP TYPE IF EXISTS ritual.review_reason;
        DROP TYPE IF EXISTS ritual.cue_type;
        DROP TYPE IF EXISTS ritual.piece_type;
        DROP TYPE IF EXISTS ritual.safety_severity;
        DROP TYPE IF EXISTS ritual.concept_relation_type;
        DROP TYPE IF EXISTS ritual.ritual_mode;
        DROP TYPE IF EXISTS ritual.safety_category;
        DROP TYPE IF EXISTS ritual.gate_key;
        DROP TYPE IF EXISTS ritual.family_type;
        """
    )
    # ### end Alembic commands ###
