"""ayin working canon

Revision ID: 20260918_0002
Revises: 20260918_0001
Create Date: 2026-09-18 17:17:04.183630
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260918_0002"
down_revision: str | None = "20260918_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ayin_concepts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ayin_concepts")),
        sa.UniqueConstraint("stable_key", name=op.f("uq_ayin_concepts_stable_key")),
        schema="core",
    )
    op.create_table(
        "ayin_open_questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ayin_open_questions")),
        sa.UniqueConstraint(
            "stable_key", name=op.f("uq_ayin_open_questions_stable_key")
        ),
        schema="core",
    )
    op.create_table(
        "ayin_principles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ayin_principles")),
        sa.UniqueConstraint("stable_key", name=op.f("uq_ayin_principles_stable_key")),
        schema="core",
    )
    op.create_table(
        "canon_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("document_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column(
            "original_language",
            sa.Enum("fa", "en", "ar", name="language_code", schema="core"),
            nullable=False,
        ),
        sa.Column(
            "corpus_zone",
            sa.Enum(
                "AYIN_CANON",
                "AYIN_WORKING",
                "MANASEK_CANON",
                "MANASEK_WORKING",
                "EXTERNAL_PRIMARY",
                "EXTERNAL_DERIVED",
                "GENERATED_CONTENT",
                name="corpus_zone",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "corpus_zone IN ('AYIN_WORKING', 'AYIN_CANON')",
            name=op.f("ck_canon_documents_ayin_document_zone"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canon_documents")),
        sa.UniqueConstraint("slug", name=op.f("uq_canon_documents_slug")),
        schema="core",
    )
    op.create_table(
        "object_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("checksum_algorithm", sa.String(length=16), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("storage_backend", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "checksum_algorithm = 'sha256'",
            name=op.f("ck_object_assets_sha256_algorithm"),
        ),
        sa.CheckConstraint(
            "sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_object_assets_valid_sha256")
        ),
        sa.CheckConstraint(
            "byte_size >= 0", name=op.f("ck_object_assets_nonnegative_byte_size")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_object_assets")),
        sa.UniqueConstraint(
            "checksum_algorithm",
            "sha256",
            name=op.f("uq_object_assets_checksum_algorithm_sha256"),
        ),
        sa.UniqueConstraint("storage_key", name=op.f("uq_object_assets_storage_key")),
        schema="ops",
    )
    op.create_table(
        "ayin_distinctions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=255), nullable=False),
        sa.Column("left_concept_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["left_concept_id"],
            ["core.ayin_concepts.id"],
            name=op.f("fk_ayin_distinctions_left_concept_id_ayin_concepts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ayin_distinctions")),
        sa.UniqueConstraint("stable_key", name=op.f("uq_ayin_distinctions_stable_key")),
        schema="core",
    )
    op.create_table(
        "canon_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("supersedes_version_id", sa.Uuid(), nullable=True),
        sa.Column("semantic_version", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column(
            "corpus_zone",
            sa.Enum(
                "AYIN_CANON",
                "AYIN_WORKING",
                "MANASEK_CANON",
                "MANASEK_WORKING",
                "EXTERNAL_PRIMARY",
                "EXTERNAL_DERIVED",
                "GENERATED_CONTENT",
                name="corpus_zone",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column("source_file_hash", sa.String(length=64), nullable=False),
        sa.Column("importer_version", sa.String(length=64), nullable=False),
        sa.Column("extractor_name", sa.String(length=64), nullable=False),
        sa.Column("extractor_version", sa.String(length=128), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "((corpus_zone = 'AYIN_WORKING' AND status IN ('draft', 'review', 'deprecated')) OR (corpus_zone = 'AYIN_CANON' AND status IN ('approved', 'superseded', 'deprecated')))",
            name=op.f("ck_canon_versions_status_matches_zone"),
        ),
        sa.CheckConstraint(
            "(status <> 'approved') OR (semantic_version IS NOT NULL AND approved_by IS NOT NULL AND approved_at IS NOT NULL AND effective_from IS NOT NULL AND corpus_zone = 'AYIN_CANON')",
            name=op.f("ck_canon_versions_approved_metadata"),
        ),
        sa.CheckConstraint(
            "source_file_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_canon_versions_valid_hash"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["core.canon_documents.id"],
            name=op.f("fk_canon_versions_document_id_canon_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_version_id"],
            ["core.canon_versions.id"],
            name=op.f("fk_canon_versions_supersedes_version_id_canon_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canon_versions")),
        sa.UniqueConstraint(
            "document_id",
            "source_file_hash",
            "importer_version",
            name=op.f(
                "uq_canon_versions_document_id_source_file_hash_importer_version"
            ),
        ),
        schema="core",
    )
    op.create_index(
        op.f("ix_canon_versions_document_id"),
        "canon_versions",
        ["document_id"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "terms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("concept_id", sa.Uuid(), nullable=True),
        sa.Column("stable_key", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["core.ayin_concepts.id"],
            name=op.f("fk_terms_concept_id_ayin_concepts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_terms")),
        sa.UniqueConstraint("stable_key", name=op.f("uq_terms_stable_key")),
        schema="core",
    )
    op.create_table(
        "ayin_review_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canon_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "extraction_ambiguity",
                "structure_ambiguity",
                "seed_provenance",
                name="ayin_review_kind",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "resolved",
                "dismissed",
                name="ayin_review_status",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canon_version_id"],
            ["core.canon_versions.id"],
            name=op.f("fk_ayin_review_items_canon_version_id_canon_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ayin_review_items")),
        schema="core",
    )
    op.create_index(
        op.f("ix_ayin_review_items_canon_version_id"),
        "ayin_review_items",
        ["canon_version_id"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "canon_version_source_assets",
        sa.Column("canon_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canon_version_id"],
            ["core.canon_versions.id"],
            name=op.f("fk_canon_version_source_assets_canon_version_id_canon_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_asset_id"],
            ["ops.object_assets.id"],
            name=op.f("fk_canon_version_source_assets_source_asset_id_object_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "canon_version_id", name=op.f("pk_canon_version_source_assets")
        ),
        sa.UniqueConstraint(
            "canon_version_id",
            "source_asset_id",
            name=op.f(
                "uq_canon_version_source_assets_canon_version_id_source_asset_id"
            ),
        ),
        schema="core",
    )
    op.create_table(
        "canon_passages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canon_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("printed_page_label", sa.String(length=32), nullable=True),
        sa.Column(
            "heading_path", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("paragraph_index", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "language",
            sa.Enum("fa", "en", "ar", name="language_code", schema="core"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_canon_passages_valid_hash")
        ),
        sa.CheckConstraint(
            "page_number > 0", name=op.f("ck_canon_passages_positive_page_number")
        ),
        sa.CheckConstraint(
            "paragraph_index > 0",
            name=op.f("ck_canon_passages_positive_paragraph_index"),
        ),
        sa.CheckConstraint(
            "sequence > 0", name=op.f("ck_canon_passages_positive_sequence")
        ),
        sa.ForeignKeyConstraint(
            ["canon_version_id", "source_asset_id"],
            [
                "core.canon_version_source_assets.canon_version_id",
                "core.canon_version_source_assets.source_asset_id",
            ],
            name=op.f(
                "fk_canon_passages_canon_version_id_source_asset_id_canon_version_source_assets"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canon_passages")),
        sa.UniqueConstraint(
            "canon_version_id",
            "sequence",
            name=op.f("uq_canon_passages_canon_version_id_sequence"),
        ),
        sa.UniqueConstraint(
            "id", "canon_version_id", name=op.f("uq_canon_passages_id_canon_version_id")
        ),
        schema="core",
    )
    op.create_index(
        op.f("ix_canon_passages_canon_version_id"),
        "canon_passages",
        ["canon_version_id"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "ayin_concept_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("concept_id", sa.Uuid(), nullable=False),
        sa.Column("canon_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "approval_status",
            sa.Enum(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_ayin_concept_versions_positive_version")
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["core.ayin_concepts.id"],
            name=op.f("fk_ayin_concept_versions_concept_id_ayin_concepts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "canon_version_id"],
            ["core.canon_passages.id", "core.canon_passages.canon_version_id"],
            name=op.f(
                "fk_ayin_concept_versions_source_passage_id_canon_version_id_canon_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ayin_concept_versions")),
        sa.UniqueConstraint(
            "concept_id",
            "canon_version_id",
            "version_number",
            name=op.f(
                "uq_ayin_concept_versions_concept_id_canon_version_id_version_number"
            ),
        ),
        schema="core",
    )
    op.create_index(
        op.f("ix_ayin_concept_versions_concept_id"),
        "ayin_concept_versions",
        ["concept_id"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "ayin_distinction_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("distinction_id", sa.Uuid(), nullable=False),
        sa.Column("canon_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "relation",
            sa.Enum(
                "IS_NOT",
                "DISTINCT_FROM",
                "DOES_NOT_IMPLY",
                "CAN_COEXIST_WITH",
                "DEPENDS_ON",
                "OPEN_RELATION",
                name="distinction_relation",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column("right_concept_id", sa.Uuid(), nullable=True),
        sa.Column("right_label", sa.String(length=255), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "discourse_type",
            sa.Enum(
                "CONCEPTUAL",
                "DESCRIPTIVE",
                "ETHICAL",
                "OPTIONAL_METAPHYSICAL",
                name="discourse_type",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "num_nonnulls(right_concept_id, right_label) = 1",
            name=op.f("ck_ayin_distinction_versions_one_right_side"),
        ),
        sa.ForeignKeyConstraint(
            ["distinction_id"],
            ["core.ayin_distinctions.id"],
            name=op.f("fk_ayin_distinction_versions_distinction_id_ayin_distinctions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["right_concept_id"],
            ["core.ayin_concepts.id"],
            name=op.f("fk_ayin_distinction_versions_right_concept_id_ayin_concepts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "canon_version_id"],
            ["core.canon_passages.id", "core.canon_passages.canon_version_id"],
            name=op.f(
                "fk_ayin_distinction_versions_source_passage_id_canon_version_id_canon_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ayin_distinction_versions")),
        sa.UniqueConstraint(
            "distinction_id",
            "canon_version_id",
            "version_number",
            name=op.f(
                "uq_ayin_distinction_versions_distinction_id_canon_version_id_version_number"
            ),
        ),
        schema="core",
    )
    op.create_table(
        "ayin_relations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_concept_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum(
                "IS_NOT",
                "DISTINCT_FROM",
                "DOES_NOT_IMPLY",
                "CAN_COEXIST_WITH",
                "DEPENDS_ON",
                "OPEN_RELATION",
                name="distinction_relation",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column("object_concept_id", sa.Uuid(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "discourse_type",
            sa.Enum(
                "CONCEPTUAL",
                "DESCRIPTIVE",
                "ETHICAL",
                "OPTIONAL_METAPHYSICAL",
                name="discourse_type",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column("canon_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "subject_concept_id <> object_concept_id",
            name=op.f("ck_ayin_relations_distinct_concepts"),
        ),
        sa.ForeignKeyConstraint(
            ["object_concept_id"],
            ["core.ayin_concepts.id"],
            name=op.f("fk_ayin_relations_object_concept_id_ayin_concepts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "canon_version_id"],
            ["core.canon_passages.id", "core.canon_passages.canon_version_id"],
            name=op.f(
                "fk_ayin_relations_source_passage_id_canon_version_id_canon_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subject_concept_id"],
            ["core.ayin_concepts.id"],
            name=op.f("fk_ayin_relations_subject_concept_id_ayin_concepts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ayin_relations")),
        sa.UniqueConstraint(
            "subject_concept_id",
            "relation_type",
            "object_concept_id",
            "canon_version_id",
            name=op.f(
                "uq_ayin_relations_subject_concept_id_relation_type_object_concept_id_canon_version_id"
            ),
        ),
        schema="core",
    )
    op.create_index(
        op.f("ix_ayin_relations_object_concept_id"),
        "ayin_relations",
        ["object_concept_id"],
        unique=False,
        schema="core",
    )
    op.create_index(
        op.f("ix_ayin_relations_subject_concept_id"),
        "ayin_relations",
        ["subject_concept_id"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "ayin_open_question_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("open_question_id", sa.Uuid(), nullable=False),
        sa.Column("canon_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column(
            "discourse_type",
            sa.Enum(
                "CONCEPTUAL",
                "DESCRIPTIVE",
                "ETHICAL",
                "OPTIONAL_METAPHYSICAL",
                name="discourse_type",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "under_review",
                "partially_addressed",
                "retired",
                name="open_question_status",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["open_question_id"],
            ["core.ayin_open_questions.id"],
            name=op.f(
                "fk_ayin_open_question_versions_open_question_id_ayin_open_questions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "canon_version_id"],
            ["core.canon_passages.id", "core.canon_passages.canon_version_id"],
            name=op.f(
                "fk_ayin_open_question_versions_source_passage_id_canon_version_id_canon_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ayin_open_question_versions")),
        sa.UniqueConstraint(
            "open_question_id",
            "canon_version_id",
            "version_number",
            name=op.f(
                "uq_ayin_open_question_versions_open_question_id_canon_version_id_version_number"
            ),
        ),
        schema="core",
    )
    op.create_table(
        "ayin_passage_reviews",
        sa.Column("review_item_id", sa.Uuid(), nullable=False),
        sa.Column("passage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["core.canon_passages.id"],
            name=op.f("fk_ayin_passage_reviews_passage_id_canon_passages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["review_item_id"],
            ["core.ayin_review_items.id"],
            name=op.f("fk_ayin_passage_reviews_review_item_id_ayin_review_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("review_item_id", name=op.f("pk_ayin_passage_reviews")),
        schema="core",
    )
    op.create_index(
        op.f("ix_ayin_passage_reviews_passage_id"),
        "ayin_passage_reviews",
        ["passage_id"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "ayin_principle_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("principle_id", sa.Uuid(), nullable=False),
        sa.Column("canon_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "discourse_type",
            sa.Enum(
                "CONCEPTUAL",
                "DESCRIPTIVE",
                "ETHICAL",
                "OPTIONAL_METAPHYSICAL",
                name="discourse_type",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["principle_id"],
            ["core.ayin_principles.id"],
            name=op.f("fk_ayin_principle_versions_principle_id_ayin_principles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "canon_version_id"],
            ["core.canon_passages.id", "core.canon_passages.canon_version_id"],
            name=op.f(
                "fk_ayin_principle_versions_source_passage_id_canon_version_id_canon_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ayin_principle_versions")),
        sa.UniqueConstraint(
            "principle_id",
            "canon_version_id",
            "version_number",
            name=op.f(
                "uq_ayin_principle_versions_principle_id_canon_version_id_version_number"
            ),
        ),
        schema="core",
    )
    op.create_table(
        "term_forms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("canon_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column(
            "language",
            sa.Enum("fa", "en", "ar", name="language_code", schema="core"),
            nullable=False,
        ),
        sa.Column("script", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("form", sa.String(length=512), nullable=False),
        sa.Column(
            "form_type",
            sa.Enum(
                "preferred",
                "transliteration",
                "explanatory_gloss",
                "alias",
                "historical",
                "deprecated",
                "forbidden_equivalent",
                name="term_form_type",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column(
            "approval_status",
            sa.Enum(
                "draft",
                "review",
                "approved",
                "superseded",
                "deprecated",
                name="editorial_status",
                schema="core",
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "approval_status <> 'approved' OR effective_from IS NOT NULL",
            name=op.f("ck_term_forms_approved_effective_from"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from",
            name=op.f("ck_term_forms_valid_effective_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "canon_version_id"],
            ["core.canon_passages.id", "core.canon_passages.canon_version_id"],
            name=op.f(
                "fk_term_forms_source_passage_id_canon_version_id_canon_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["core.terms.id"],
            name=op.f("fk_term_forms_term_id_terms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_term_forms")),
        sa.UniqueConstraint(
            "term_id",
            "language",
            "form",
            "form_type",
            "version",
            name=op.f("uq_term_forms_term_id_language_form_form_type_version"),
        ),
        schema="core",
    )
    op.create_index(
        op.f("ix_term_forms_term_id"),
        "term_forms",
        ["term_id"],
        unique=False,
        schema="core",
    )
    op.create_index(
        "uq_term_forms_approved_preferred",
        "term_forms",
        ["term_id", "language", "scope"],
        unique=True,
        schema="core",
        postgresql_where=sa.text(
            "form_type = 'preferred' AND approval_status = 'approved' "
            "AND effective_to IS NULL"
        ),
    )
    op.execute("""
        CREATE FUNCTION core.prevent_approved_canon_version_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.status = 'approved' THEN
                RAISE EXCEPTION 'approved canon versions are immutable'
                    USING ERRCODE = 'integrity_constraint_violation';
            END IF;
            RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER trg_canon_versions_approved_immutable
        BEFORE UPDATE OR DELETE ON core.canon_versions
        FOR EACH ROW EXECUTE FUNCTION core.prevent_approved_canon_version_mutation()
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER trg_canon_versions_approved_immutable ON core.canon_versions"
    )
    op.execute("DROP FUNCTION core.prevent_approved_canon_version_mutation()")
    op.drop_index(
        "uq_term_forms_approved_preferred",
        table_name="term_forms",
        schema="core",
        postgresql_where=sa.text(
            "form_type = 'preferred' AND approval_status = 'approved' "
            "AND effective_to IS NULL"
        ),
    )
    op.drop_index(op.f("ix_term_forms_term_id"), table_name="term_forms", schema="core")
    op.drop_table("term_forms", schema="core")
    op.drop_table("ayin_principle_versions", schema="core")
    op.drop_index(
        op.f("ix_ayin_passage_reviews_passage_id"),
        table_name="ayin_passage_reviews",
        schema="core",
    )
    op.drop_table("ayin_passage_reviews", schema="core")
    op.drop_table("ayin_open_question_versions", schema="core")
    op.drop_index(
        op.f("ix_ayin_relations_subject_concept_id"),
        table_name="ayin_relations",
        schema="core",
    )
    op.drop_index(
        op.f("ix_ayin_relations_object_concept_id"),
        table_name="ayin_relations",
        schema="core",
    )
    op.drop_table("ayin_relations", schema="core")
    op.drop_table("ayin_distinction_versions", schema="core")
    op.drop_index(
        op.f("ix_ayin_concept_versions_concept_id"),
        table_name="ayin_concept_versions",
        schema="core",
    )
    op.drop_table("ayin_concept_versions", schema="core")
    op.drop_index(
        op.f("ix_canon_passages_canon_version_id"),
        table_name="canon_passages",
        schema="core",
    )
    op.drop_table("canon_passages", schema="core")
    op.drop_table("canon_version_source_assets", schema="core")
    op.drop_index(
        op.f("ix_ayin_review_items_canon_version_id"),
        table_name="ayin_review_items",
        schema="core",
    )
    op.drop_table("ayin_review_items", schema="core")
    op.drop_table("terms", schema="core")
    op.drop_index(
        op.f("ix_canon_versions_document_id"),
        table_name="canon_versions",
        schema="core",
    )
    op.drop_table("canon_versions", schema="core")
    op.drop_table("ayin_distinctions", schema="core")
    op.drop_table("object_assets", schema="ops")
    op.drop_table("canon_documents", schema="core")
    op.drop_table("ayin_principles", schema="core")
    op.drop_table("ayin_open_questions", schema="core")
    op.drop_table("ayin_concepts", schema="core")
    for enum_name in (
        "term_form_type",
        "open_question_status",
        "ayin_review_status",
        "ayin_review_kind",
        "distinction_relation",
        "discourse_type",
        "editorial_status",
        "language_code",
        "corpus_zone",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS core.{enum_name}"))
    # ### end Alembic commands ###
