"""add ayin external dialogue layer

Revision ID: 26a7bca28432
Revises: effbbb690796
Create Date: 2026-09-20 11:27:58.407234
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "26a7bca28432"
down_revision: str | None = "effbbb690796"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Composite foreign keys below require these identity/version constraints first.
    op.create_unique_constraint(
        op.f("uq_ayin_concept_versions_id_canon_version_id"),
        "ayin_concept_versions",
        ["id", "canon_version_id"],
        schema="core",
    )
    op.create_unique_constraint(
        op.f("uq_ayin_distinction_versions_id_canon_version_id"),
        "ayin_distinction_versions",
        ["id", "canon_version_id"],
        schema="core",
    )
    op.create_unique_constraint(
        op.f("uq_ayin_open_question_versions_id_canon_version_id"),
        "ayin_open_question_versions",
        ["id", "canon_version_id"],
        schema="core",
    )
    op.create_unique_constraint(
        op.f("uq_ayin_principle_versions_id_canon_version_id"),
        "ayin_principle_versions",
        ["id", "canon_version_id"],
        schema="core",
    )
    op.create_unique_constraint(
        op.f("uq_external_claims_id_source_version_id_source_segment_id"),
        "external_claims",
        ["id", "source_version_id", "source_segment_id"],
        schema="knowledge",
    )
    op.create_table(
        "dialogue_external_targets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "CLAIM",
                "WORK",
                "CHUNK",
                "EXTERNAL_CONCEPT",
                "PERSON",
                name="dialogue_external_target_kind",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_segment_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("work_id", sa.Uuid(), nullable=True),
        sa.Column("chunk_id", sa.Uuid(), nullable=True),
        sa.Column("external_concept_id", sa.Uuid(), nullable=True),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(kind = 'CLAIM' AND claim_id IS NOT NULL) OR (kind = 'WORK' AND work_id IS NOT NULL) OR (kind = 'CHUNK' AND chunk_id IS NOT NULL) OR (kind = 'EXTERNAL_CONCEPT' AND external_concept_id IS NOT NULL) OR (kind = 'PERSON' AND person_id IS NOT NULL)",
            name=op.f("ck_dialogue_external_targets_external_kind_matches_target"),
        ),
        sa.CheckConstraint(
            "num_nonnulls(claim_id, work_id, chunk_id, external_concept_id, person_id) = 1",
            name=op.f("ck_dialogue_external_targets_one_typed_external_target"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id", "source_segment_id"],
            [
                "retrieval.chunk_external_segments.chunk_id",
                "retrieval.chunk_external_segments.source_segment_id",
            ],
            name=op.f(
                "fk_dialogue_external_targets_chunk_id_source_segment_id_chunk_external_segments"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["claim_id", "source_version_id", "source_segment_id"],
            [
                "knowledge.external_claims.id",
                "knowledge.external_claims.source_version_id",
                "knowledge.external_claims.source_segment_id",
            ],
            name=op.f(
                "fk_dialogue_external_targets_claim_id_source_version_id_source_segment_id_external_claims"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["external_concept_id"],
            ["knowledge.external_concepts.id"],
            name=op.f(
                "fk_dialogue_external_targets_external_concept_id_external_concepts"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["knowledge.people.id"],
            name=op.f("fk_dialogue_external_targets_person_id_people"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_segment_id", "source_version_id"],
            [
                "knowledge.source_segments.id",
                "knowledge.source_segments.source_version_id",
            ],
            name=op.f(
                "fk_dialogue_external_targets_source_segment_id_source_version_id_source_segments"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["knowledge.works.id"],
            name=op.f("fk_dialogue_external_targets_work_id_works"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dialogue_external_targets")),
        schema="knowledge",
    )
    op.create_table(
        "dialogue_ayin_targets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "CONCEPT_VERSION",
                "PRINCIPLE_VERSION",
                "DISTINCTION_VERSION",
                "OPEN_QUESTION_VERSION",
                name="dialogue_ayin_target_kind",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("canon_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_passage_id", sa.Uuid(), nullable=False),
        sa.Column("concept_version_id", sa.Uuid(), nullable=True),
        sa.Column("principle_version_id", sa.Uuid(), nullable=True),
        sa.Column("distinction_version_id", sa.Uuid(), nullable=True),
        sa.Column("open_question_version_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(kind = 'CONCEPT_VERSION' AND concept_version_id IS NOT NULL) OR (kind = 'PRINCIPLE_VERSION' AND principle_version_id IS NOT NULL) OR (kind = 'DISTINCTION_VERSION' AND distinction_version_id IS NOT NULL) OR (kind = 'OPEN_QUESTION_VERSION' AND open_question_version_id IS NOT NULL)",
            name=op.f("ck_dialogue_ayin_targets_ayin_kind_matches_target"),
        ),
        sa.CheckConstraint(
            "num_nonnulls(concept_version_id, principle_version_id, distinction_version_id, open_question_version_id) = 1",
            name=op.f("ck_dialogue_ayin_targets_one_typed_ayin_version"),
        ),
        sa.ForeignKeyConstraint(
            ["concept_version_id", "canon_version_id"],
            [
                "core.ayin_concept_versions.id",
                "core.ayin_concept_versions.canon_version_id",
            ],
            name=op.f(
                "fk_dialogue_ayin_targets_concept_version_id_canon_version_id_ayin_concept_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["distinction_version_id", "canon_version_id"],
            [
                "core.ayin_distinction_versions.id",
                "core.ayin_distinction_versions.canon_version_id",
            ],
            name=op.f(
                "fk_dialogue_ayin_targets_distinction_version_id_canon_version_id_ayin_distinction_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["open_question_version_id", "canon_version_id"],
            [
                "core.ayin_open_question_versions.id",
                "core.ayin_open_question_versions.canon_version_id",
            ],
            name=op.f(
                "fk_dialogue_ayin_targets_open_question_version_id_canon_version_id_ayin_open_question_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["principle_version_id", "canon_version_id"],
            [
                "core.ayin_principle_versions.id",
                "core.ayin_principle_versions.canon_version_id",
            ],
            name=op.f(
                "fk_dialogue_ayin_targets_principle_version_id_canon_version_id_ayin_principle_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_passage_id", "canon_version_id"],
            ["core.canon_passages.id", "core.canon_passages.canon_version_id"],
            name=op.f(
                "fk_dialogue_ayin_targets_source_passage_id_canon_version_id_canon_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dialogue_ayin_targets")),
        sa.UniqueConstraint(
            "concept_version_id",
            name=op.f("uq_dialogue_ayin_targets_concept_version_id"),
        ),
        sa.UniqueConstraint(
            "distinction_version_id",
            name=op.f("uq_dialogue_ayin_targets_distinction_version_id"),
        ),
        sa.UniqueConstraint(
            "open_question_version_id",
            name=op.f("uq_dialogue_ayin_targets_open_question_version_id"),
        ),
        sa.UniqueConstraint(
            "principle_version_id",
            name=op.f("uq_dialogue_ayin_targets_principle_version_id"),
        ),
        schema="knowledge",
    )
    op.create_table(
        "dialogue_external_evidence",
        sa.Column("external_target_id", sa.Uuid(), nullable=False),
        sa.Column("source_segment_id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chunk_id", "source_segment_id"],
            [
                "retrieval.chunk_external_segments.chunk_id",
                "retrieval.chunk_external_segments.source_segment_id",
            ],
            name=op.f(
                "fk_dialogue_external_evidence_chunk_id_source_segment_id_chunk_external_segments"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["external_target_id"],
            ["knowledge.dialogue_external_targets.id"],
            name=op.f(
                "fk_dialogue_external_evidence_external_target_id_dialogue_external_targets"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_segment_id", "source_version_id"],
            [
                "knowledge.source_segments.id",
                "knowledge.source_segments.source_version_id",
            ],
            name=op.f(
                "fk_dialogue_external_evidence_source_segment_id_source_version_id_source_segments"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "external_target_id",
            "source_segment_id",
            name=op.f("pk_dialogue_external_evidence"),
        ),
        schema="knowledge",
    )
    op.create_table(
        "dialogue_ayin_evidence",
        sa.Column("ayin_target_id", sa.Uuid(), nullable=False),
        sa.Column("passage_id", sa.Uuid(), nullable=False),
        sa.Column("canon_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ayin_target_id"],
            ["knowledge.dialogue_ayin_targets.id"],
            name=op.f("fk_dialogue_ayin_evidence_ayin_target_id_dialogue_ayin_targets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["passage_id", "canon_version_id"],
            ["core.canon_passages.id", "core.canon_passages.canon_version_id"],
            name=op.f(
                "fk_dialogue_ayin_evidence_passage_id_canon_version_id_canon_passages"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "ayin_target_id", "passage_id", name=op.f("pk_dialogue_ayin_evidence")
        ),
        schema="knowledge",
    )
    op.create_table(
        "dialogue_proposal_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ayin_target_id", sa.Uuid(), nullable=False),
        sa.Column("retrieval_run_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=512), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("classifier_version", sa.String(length=64), nullable=False),
        sa.Column(
            "retrieval_configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("configuration_hash", sa.String(length=64), nullable=False),
        sa.Column("ayin_input_hash", sa.String(length=64), nullable=False),
        sa.Column("candidate_input_hash", sa.String(length=64), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "RUNNING",
                "SUCCEEDED",
                "PARTIAL",
                "FAILED",
                name="dialogue_proposal_run_status",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ayin_input_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_dialogue_proposal_runs_valid_ayin_input_hash"),
        ),
        sa.CheckConstraint(
            "cache_key ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_dialogue_proposal_runs_valid_cache_key"),
        ),
        sa.CheckConstraint(
            "candidate_input_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_dialogue_proposal_runs_valid_candidate_input_hash"),
        ),
        sa.CheckConstraint(
            "configuration_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_dialogue_proposal_runs_valid_configuration_hash"),
        ),
        sa.CheckConstraint(
            "candidate_count >= 0 AND success_count >= 0 AND failure_count >= 0",
            name=op.f("ck_dialogue_proposal_runs_nonnegative_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["ayin_target_id"],
            ["knowledge.dialogue_ayin_targets.id"],
            name=op.f("fk_dialogue_proposal_runs_ayin_target_id_dialogue_ayin_targets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["retrieval_run_id"],
            ["retrieval.runs.id"],
            name=op.f("fk_dialogue_proposal_runs_retrieval_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dialogue_proposal_runs")),
        sa.UniqueConstraint(
            "cache_key", name=op.f("uq_dialogue_proposal_runs_cache_key")
        ),
        schema="knowledge",
    )
    op.create_table(
        "dialogue_proposal_run_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proposal_run_id", sa.Uuid(), nullable=False),
        sa.Column("external_target_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("chunk_content_hash", sa.String(length=64), nullable=False),
        sa.Column("classifier_cache_key", sa.String(length=64), nullable=False),
        sa.Column(
            "structured_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "classifier_cache_key ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_dialogue_proposal_run_candidates_valid_classifier_cache_key"),
        ),
        sa.CheckConstraint(
            "rank > 0", name=op.f("ck_dialogue_proposal_run_candidates_positive_rank")
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["retrieval.chunks.id"],
            name=op.f("fk_dialogue_proposal_run_candidates_chunk_id_chunks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["external_target_id"],
            ["knowledge.dialogue_external_targets.id"],
            name=op.f(
                "fk_dialogue_proposal_run_candidates_external_target_id_dialogue_external_targets"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_run_id"],
            ["knowledge.dialogue_proposal_runs.id"],
            name=op.f(
                "fk_dialogue_proposal_run_candidates_proposal_run_id_dialogue_proposal_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dialogue_proposal_run_candidates")),
        sa.UniqueConstraint(
            "proposal_run_id",
            "chunk_id",
            name=op.f("uq_dialogue_proposal_run_candidates_proposal_run_id_chunk_id"),
        ),
        schema="knowledge",
    )
    op.create_table(
        "dialogue_proposals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proposal_run_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_id", sa.Uuid(), nullable=True),
        sa.Column("ayin_target_id", sa.Uuid(), nullable=False),
        sa.Column("external_target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation_type",
            postgresql.ENUM(
                "EMPIRICALLY_RELEVANT_TO",
                "SUPPORTS_EMPIRICAL_SUBCLAIM",
                "CONCEPTUAL_PARALLEL",
                "HISTORICAL_PARALLEL",
                "ILLUSTRATES",
                "COMPATIBLE_WITH",
                "TENSION_WITH",
                "CHALLENGES",
                "COUNTEREXAMPLE_TO",
                "ALTERNATIVE_EXPLANATION",
                "NOT_EQUIVALENT_TO",
                "UNRESOLVED_RELATION",
                name="dialogue_relation_type",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column(
            "scope",
            postgresql.ENUM(
                "CONCEPTUAL",
                "EMPIRICAL",
                "DESCRIPTIVE",
                "ETHICAL",
                "METAPHYSICAL",
                "HISTORICAL",
                "ILLUSTRATIVE",
                name="dialogue_relation_scope",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("relation_confidence", sa.Float(), nullable=False),
        sa.Column(
            "evidence_role",
            postgresql.ENUM(
                "EMPIRICAL_EVIDENCE",
                "EMPIRICAL_COUNTEREVIDENCE",
                "PHILOSOPHICAL_ARGUMENT",
                "CONCEPTUAL_ANALOGY",
                "HISTORICAL_CONTEXT",
                "EXAMPLE",
                "ANECDOTE",
                "COMMENTARY",
                "REFERENCE_ONLY",
                "ALTERNATIVE_EXPLANATION",
                "UNKNOWN",
                name="dialogue_evidence_role",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column(
            "claim_testability",
            postgresql.ENUM(
                "CONCEPTUAL",
                "DESCRIPTIVE_TESTABLE",
                "DESCRIPTIVE_NONTESTABLE",
                "ETHICAL",
                "OPTIONAL_METAPHYSICAL",
                "OPEN_QUESTION",
                name="dialogue_claim_testability",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column(
            "proposal_method",
            postgresql.ENUM(
                "MODEL_CLASSIFIER",
                "MANUAL",
                name="dialogue_proposal_method",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column(
            "review_priority",
            postgresql.ENUM(
                "LOW",
                "NORMAL",
                "HIGH",
                "CRITICAL",
                name="dialogue_review_priority",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "validation_issues", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(proposal_method = 'MODEL_CLASSIFIER' AND proposal_run_id IS NOT NULL AND candidate_id IS NOT NULL) OR proposal_method = 'MANUAL'",
            name=op.f("ck_dialogue_proposals_machine_proposal_has_run"),
        ),
        sa.CheckConstraint(
            "relation_confidence >= 0 AND relation_confidence <= 1",
            name=op.f("ck_dialogue_proposals_valid_relation_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["ayin_target_id"],
            ["knowledge.dialogue_ayin_targets.id"],
            name=op.f("fk_dialogue_proposals_ayin_target_id_dialogue_ayin_targets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["knowledge.dialogue_proposal_run_candidates.id"],
            name=op.f(
                "fk_dialogue_proposals_candidate_id_dialogue_proposal_run_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["external_target_id"],
            ["knowledge.dialogue_external_targets.id"],
            name=op.f(
                "fk_dialogue_proposals_external_target_id_dialogue_external_targets"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_run_id"],
            ["knowledge.dialogue_proposal_runs.id"],
            name=op.f("fk_dialogue_proposals_proposal_run_id_dialogue_proposal_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dialogue_proposals")),
        sa.UniqueConstraint(
            "candidate_id",
            "relation_type",
            "scope",
            name=op.f("uq_dialogue_proposals_candidate_id_relation_type_scope"),
        ),
        schema="knowledge",
    )
    op.create_index(
        "ix_dialogue_proposals_ayin_external",
        "dialogue_proposals",
        ["ayin_target_id", "external_target_id"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "dialogue_relations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation_type",
            postgresql.ENUM(
                "EMPIRICALLY_RELEVANT_TO",
                "SUPPORTS_EMPIRICAL_SUBCLAIM",
                "CONCEPTUAL_PARALLEL",
                "HISTORICAL_PARALLEL",
                "ILLUSTRATES",
                "COMPATIBLE_WITH",
                "TENSION_WITH",
                "CHALLENGES",
                "COUNTEREXAMPLE_TO",
                "ALTERNATIVE_EXPLANATION",
                "NOT_EQUIVALENT_TO",
                "UNRESOLVED_RELATION",
                name="dialogue_relation_type",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column(
            "scope",
            postgresql.ENUM(
                "CONCEPTUAL",
                "EMPIRICAL",
                "DESCRIPTIVE",
                "ETHICAL",
                "METAPHYSICAL",
                "HISTORICAL",
                "ILLUSTRATIVE",
                name="dialogue_relation_scope",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "review_status",
            postgresql.ENUM(
                "PROPOSED",
                "IN_REVIEW",
                "APPROVED",
                "REJECTED",
                "SUPERSEDED",
                name="dialogue_review_status",
                schema="knowledge",
            ),
            server_default="PROPOSED",
            nullable=False,
        ),
        sa.Column(
            "review_priority",
            postgresql.ENUM(
                "LOW",
                "NORMAL",
                "HIGH",
                "CRITICAL",
                name="dialogue_review_priority",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(review_status IN ('PROPOSED', 'IN_REVIEW') AND reviewed_at IS NULL) OR (review_status IN ('APPROVED', 'REJECTED', 'SUPERSEDED') AND reviewed_at IS NOT NULL)",
            name=op.f("ck_dialogue_relations_review_completion_metadata"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["knowledge.dialogue_proposals.id"],
            name=op.f("fk_dialogue_relations_proposal_id_dialogue_proposals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dialogue_relations")),
        sa.UniqueConstraint(
            "proposal_id", name=op.f("uq_dialogue_relations_proposal_id")
        ),
        schema="knowledge",
    )
    op.create_index(
        "ix_dialogue_relations_review_queue",
        "dialogue_relations",
        ["review_status", "review_priority"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "dialogue_review_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("relation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            postgresql.ENUM(
                "START_REVIEW",
                "APPROVE",
                "REJECT",
                "SUPERSEDE",
                name="dialogue_review_action",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("reviewer", sa.String(length=255), nullable=False),
        sa.Column(
            "previous_relation_type",
            postgresql.ENUM(
                "EMPIRICALLY_RELEVANT_TO",
                "SUPPORTS_EMPIRICAL_SUBCLAIM",
                "CONCEPTUAL_PARALLEL",
                "HISTORICAL_PARALLEL",
                "ILLUSTRATES",
                "COMPATIBLE_WITH",
                "TENSION_WITH",
                "CHALLENGES",
                "COUNTEREXAMPLE_TO",
                "ALTERNATIVE_EXPLANATION",
                "NOT_EQUIVALENT_TO",
                "UNRESOLVED_RELATION",
                name="dialogue_relation_type",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column(
            "new_relation_type",
            postgresql.ENUM(
                "EMPIRICALLY_RELEVANT_TO",
                "SUPPORTS_EMPIRICAL_SUBCLAIM",
                "CONCEPTUAL_PARALLEL",
                "HISTORICAL_PARALLEL",
                "ILLUSTRATES",
                "COMPATIBLE_WITH",
                "TENSION_WITH",
                "CHALLENGES",
                "COUNTEREXAMPLE_TO",
                "ALTERNATIVE_EXPLANATION",
                "NOT_EQUIVALENT_TO",
                "UNRESOLVED_RELATION",
                name="dialogue_relation_type",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column(
            "previous_scope",
            postgresql.ENUM(
                "CONCEPTUAL",
                "EMPIRICAL",
                "DESCRIPTIVE",
                "ETHICAL",
                "METAPHYSICAL",
                "HISTORICAL",
                "ILLUSTRATIVE",
                name="dialogue_relation_scope",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column(
            "new_scope",
            postgresql.ENUM(
                "CONCEPTUAL",
                "EMPIRICAL",
                "DESCRIPTIVE",
                "ETHICAL",
                "METAPHYSICAL",
                "HISTORICAL",
                "ILLUSTRATIVE",
                name="dialogue_relation_scope",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("previous_explanation", sa.Text(), nullable=False),
        sa.Column("new_explanation", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["relation_id"],
            ["knowledge.dialogue_relations.id"],
            name=op.f("fk_dialogue_review_decisions_relation_id_dialogue_relations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dialogue_review_decisions")),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_dialogue_review_decisions_relation_id"),
        "dialogue_review_decisions",
        ["relation_id"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "dialogue_review_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("relation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reason",
            postgresql.ENUM(
                "RELATION_AMBIGUITY",
                "DISCOURSE_MISMATCH",
                "EMPIRICAL_SCOPE_UNCLEAR",
                "POTENTIAL_FALSE_EQUIVALENCE",
                "INSUFFICIENT_EXTERNAL_EVIDENCE",
                "CONFLICTING_EXTERNAL_EVIDENCE",
                "METAPHYSICAL_OVERREACH",
                "UNSUPPORTED_SCIENTIFIC_FRAMING",
                "ALTERNATIVE_EXPLANATION_PRESENT",
                "UNCERTAIN_AYIN_TARGET",
                "STALE_AFTER_AYIN_REVISION",
                "STALE_AFTER_EXTERNAL_REVISION",
                name="dialogue_review_reason",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            postgresql.ENUM(
                "LOW",
                "NORMAL",
                "HIGH",
                "CRITICAL",
                name="dialogue_review_priority",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["relation_id"],
            ["knowledge.dialogue_relations.id"],
            name=op.f("fk_dialogue_review_flags_relation_id_dialogue_relations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dialogue_review_flags")),
        sa.UniqueConstraint(
            "relation_id",
            "reason",
            name=op.f("uq_dialogue_review_flags_relation_id_reason"),
        ),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_dialogue_review_flags_relation_id"),
        "dialogue_review_flags",
        ["relation_id"],
        unique=False,
        schema="knowledge",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dialogue_review_flags_relation_id"),
        table_name="dialogue_review_flags",
        schema="knowledge",
    )
    op.drop_table("dialogue_review_flags", schema="knowledge")
    op.drop_index(
        op.f("ix_dialogue_review_decisions_relation_id"),
        table_name="dialogue_review_decisions",
        schema="knowledge",
    )
    op.drop_table("dialogue_review_decisions", schema="knowledge")
    op.drop_index(
        "ix_dialogue_relations_review_queue",
        table_name="dialogue_relations",
        schema="knowledge",
    )
    op.drop_table("dialogue_relations", schema="knowledge")
    op.drop_index(
        "ix_dialogue_proposals_ayin_external",
        table_name="dialogue_proposals",
        schema="knowledge",
    )
    op.drop_table("dialogue_proposals", schema="knowledge")
    op.drop_table("dialogue_proposal_run_candidates", schema="knowledge")
    op.drop_table("dialogue_proposal_runs", schema="knowledge")
    op.drop_table("dialogue_ayin_evidence", schema="knowledge")
    op.drop_table("dialogue_external_evidence", schema="knowledge")
    op.drop_table("dialogue_ayin_targets", schema="knowledge")
    op.drop_table("dialogue_external_targets", schema="knowledge")
    op.drop_constraint(
        op.f("uq_external_claims_id_source_version_id_source_segment_id"),
        "external_claims",
        schema="knowledge",
        type_="unique",
    )
    op.drop_constraint(
        op.f("uq_ayin_principle_versions_id_canon_version_id"),
        "ayin_principle_versions",
        schema="core",
        type_="unique",
    )
    op.drop_constraint(
        op.f("uq_ayin_open_question_versions_id_canon_version_id"),
        "ayin_open_question_versions",
        schema="core",
        type_="unique",
    )
    op.drop_constraint(
        op.f("uq_ayin_distinction_versions_id_canon_version_id"),
        "ayin_distinction_versions",
        schema="core",
        type_="unique",
    )
    op.drop_constraint(
        op.f("uq_ayin_concept_versions_id_canon_version_id"),
        "ayin_concept_versions",
        schema="core",
        type_="unique",
    )
    for enum_name in (
        "dialogue_review_reason",
        "dialogue_review_action",
        "dialogue_review_status",
        "dialogue_proposal_method",
        "dialogue_review_priority",
        "dialogue_claim_testability",
        "dialogue_evidence_role",
        "dialogue_relation_scope",
        "dialogue_relation_type",
        "dialogue_proposal_run_status",
        "dialogue_ayin_target_kind",
        "dialogue_external_target_kind",
    ):
        op.execute(sa.text(f"DROP TYPE knowledge.{enum_name}"))
    # ### end Alembic commands ###
