"""add external knowledge ingestion

Revision ID: 2d874648966b
Revises: 20260919_0004
Create Date: 2026-09-19 15:11:15.247758
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "2d874648966b"
down_revision: str | None = "20260919_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channels")),
        sa.UniqueConstraint(
            "platform", "external_id", name=op.f("uq_channels_platform_external_id")
        ),
        schema="knowledge",
    )
    op.create_table(
        "external_concepts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=512), nullable=False),
        sa.Column("normalized_name", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_concepts")),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_external_concepts_normalized_name"),
        "external_concepts",
        ["normalized_name"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=512), nullable=False),
        sa.Column("normalized_name", sa.String(length=512), nullable=False),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_organizations_normalized_name"),
        "organizations",
        ["normalized_name"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "people",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=512), nullable=False),
        sa.Column("normalized_name", sa.String(length=512), nullable=False),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_people_normalized_name"),
        "people",
        ["normalized_name"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "works",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "work_type",
            postgresql.ENUM(
                "book",
                "paper",
                "study",
                "article",
                "chapter",
                "report",
                "lecture",
                "other",
                name="work_type",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("canonical_title", sa.String(length=1024), nullable=False),
        sa.Column("normalized_title", sa.String(length=1024), nullable=False),
        sa.Column("original_title", sa.String(length=1024), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("publisher", sa.String(length=512), nullable=True),
        sa.Column("journal", sa.String(length=512), nullable=True),
        sa.Column("volume", sa.String(length=64), nullable=True),
        sa.Column("issue", sa.String(length=64), nullable=True),
        sa.Column("pages", sa.String(length=64), nullable=True),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_works")),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_works_normalized_title"),
        "works",
        ["normalized_title"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "creators",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=512), nullable=False),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["knowledge.people.id"],
            name=op.f("fk_creators_person_id_people"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_creators")),
        schema="knowledge",
    )
    op.create_table(
        "entity_labels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("work_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("concept_id", sa.Uuid(), nullable=True),
        sa.Column("label", sa.String(length=1024), nullable=False),
        sa.Column("normalized_label", sa.String(length=1024), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "canonical",
                "alias",
                "translation",
                "transliteration",
                name="label_kind",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "num_nonnulls(person_id, work_id, organization_id, concept_id) = 1",
            name=op.f("ck_entity_labels_one_typed_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["knowledge.external_concepts.id"],
            name=op.f("fk_entity_labels_concept_id_external_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["knowledge.organizations.id"],
            name=op.f("fk_entity_labels_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["knowledge.people.id"],
            name=op.f("fk_entity_labels_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["knowledge.works.id"],
            name=op.f("fk_entity_labels_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_labels")),
        sa.UniqueConstraint(
            "normalized_label",
            "language",
            "concept_id",
            name=op.f("uq_entity_labels_normalized_label_language_concept_id"),
        ),
        sa.UniqueConstraint(
            "normalized_label",
            "language",
            "organization_id",
            name=op.f("uq_entity_labels_normalized_label_language_organization_id"),
        ),
        sa.UniqueConstraint(
            "normalized_label",
            "language",
            "person_id",
            name=op.f("uq_entity_labels_normalized_label_language_person_id"),
        ),
        sa.UniqueConstraint(
            "normalized_label",
            "language",
            "work_id",
            name=op.f("uq_entity_labels_normalized_label_language_work_id"),
        ),
        schema="knowledge",
    )
    op.create_table(
        "external_identifiers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "scheme",
            postgresql.ENUM(
                "doi",
                "isbn",
                "openalex",
                "openlibrary",
                "wikidata",
                "orcid",
                "youtube",
                name="identifier_scheme",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("normalized_value", sa.String(length=512), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("work_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("concept_id", sa.Uuid(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "num_nonnulls(person_id, work_id, organization_id, concept_id) = 1",
            name=op.f("ck_external_identifiers_one_typed_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["knowledge.external_concepts.id"],
            name=op.f("fk_external_identifiers_concept_id_external_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["knowledge.organizations.id"],
            name=op.f("fk_external_identifiers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["knowledge.people.id"],
            name=op.f("fk_external_identifiers_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["knowledge.works.id"],
            name=op.f("fk_external_identifiers_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_identifiers")),
        sa.UniqueConstraint(
            "scheme",
            "normalized_value",
            name=op.f("uq_external_identifiers_scheme_normalized_value"),
        ),
        schema="knowledge",
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("object_asset_id", sa.Uuid(), nullable=True),
        sa.Column(
            "media_type",
            postgresql.ENUM(
                "cover",
                "paper_pdf",
                "first_page",
                "portrait",
                "thumbnail",
                name="media_type",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("license", sa.String(length=255), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("rights_status", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "available",
                "unknown_rights",
                "no_accessible_pdf_found",
                "invalid",
                "failed",
                name="media_status",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status <> 'available' OR object_asset_id IS NOT NULL",
            name=op.f("ck_media_assets_available_requires_object"),
        ),
        sa.ForeignKeyConstraint(
            ["object_asset_id"],
            ["ops.object_assets.id"],
            name=op.f("fk_media_assets_object_asset_id_object_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint(
            "object_asset_id",
            "media_type",
            name=op.f("uq_media_assets_object_asset_id_media_type"),
        ),
        sa.UniqueConstraint(
            "source_url",
            "media_type",
            name=op.f("uq_media_assets_source_url_media_type"),
        ),
        schema="knowledge",
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            postgresql.ENUM(
                "youtube_video",
                "podcast_episode",
                "pdf",
                "book",
                "paper",
                "article",
                "webpage",
                "lecture",
                "manual_upload",
                name="source_type",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "raw_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "ingestion_status",
            postgresql.ENUM(
                "discovered",
                "ingested",
                "partial",
                "failed",
                name="ingestion_status",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["knowledge.channels.id"],
            name=op.f("fk_sources_channel_id_channels"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint(
            "platform", "external_id", name=op.f("uq_sources_platform_external_id")
        ),
        schema="knowledge",
    )
    op.create_table(
        "work_authors",
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["knowledge.people.id"],
            name=op.f("fk_work_authors_person_id_people"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["knowledge.works.id"],
            name=op.f("fk_work_authors_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("work_id", "person_id", name=op.f("pk_work_authors")),
        sa.UniqueConstraint(
            "work_id", "position", name=op.f("uq_work_authors_work_id_position")
        ),
        schema="knowledge",
    )
    op.create_table(
        "channel_creators",
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("attribution_role", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["knowledge.channels.id"],
            name=op.f("fk_channel_creators_channel_id_channels"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["knowledge.creators.id"],
            name=op.f("fk_channel_creators_creator_id_creators"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "channel_id", "creator_id", name=op.f("pk_channel_creators")
        ),
        schema="knowledge",
    )
    op.create_table(
        "person_media_assets",
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("media_asset_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["knowledge.media_assets.id"],
            name=op.f("fk_person_media_assets_media_asset_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["knowledge.people.id"],
            name=op.f("fk_person_media_assets_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "person_id", "media_asset_id", name=op.f("pk_person_media_assets")
        ),
        schema="knowledge",
    )
    op.create_table(
        "source_media_assets",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("media_asset_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["knowledge.media_assets.id"],
            name=op.f("fk_source_media_assets_media_asset_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["knowledge.sources.id"],
            name=op.f("fk_source_media_assets_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "source_id", "media_asset_id", name=op.f("pk_source_media_assets")
        ),
        schema="knowledge",
    )
    op.create_table(
        "source_quality",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("publication_type", sa.String(length=128), nullable=False),
        sa.Column("peer_reviewed", sa.Boolean(), nullable=True),
        sa.Column("primary_or_secondary", sa.String(length=32), nullable=False),
        sa.Column("retraction_status", sa.String(length=64), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("retrieval_weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["knowledge.sources.id"],
            name=op.f("fk_source_quality_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("source_id", name=op.f("pk_source_quality")),
        schema="knowledge",
    )
    op.create_table(
        "source_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("transcript_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "corpus_zone",
            postgresql.ENUM(
                "AYIN_CANON",
                "AYIN_WORKING",
                "MANASEK_CANON",
                "MANASEK_WORKING",
                "EXTERNAL_PRIMARY",
                "EXTERNAL_DERIVED",
                "GENERATED_CONTENT",
                name="corpus_zone",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "provider_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("acquisition_tool", sa.String(length=128), nullable=False),
        sa.Column("acquisition_version", sa.String(length=128), nullable=False),
        sa.Column("normalization_version", sa.String(length=128), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_versions_valid_content_hash"),
        ),
        sa.CheckConstraint(
            "corpus_zone = 'EXTERNAL_PRIMARY'",
            name=op.f("ck_source_versions_external_primary_only"),
        ),
        sa.CheckConstraint(
            "transcript_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_versions_valid_transcript_hash"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["knowledge.sources.id"],
            name=op.f("fk_source_versions_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_versions")),
        sa.UniqueConstraint(
            "id", "source_id", name=op.f("uq_source_versions_id_source_id")
        ),
        sa.UniqueConstraint(
            "source_id",
            "content_hash",
            name=op.f("uq_source_versions_source_id_content_hash"),
        ),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_source_versions_source_id"),
        "source_versions",
        ["source_id"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "work_media_assets",
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("media_asset_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["knowledge.media_assets.id"],
            name=op.f("fk_work_media_assets_media_asset_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["knowledge.works.id"],
            name=op.f("fk_work_media_assets_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "work_id", "media_asset_id", name=op.f("pk_work_media_assets")
        ),
        schema="knowledge",
    )
    op.create_table(
        "extraction_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("task", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column(
            "configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("configuration_hash", sa.String(length=64), nullable=False),
        sa.Column("window_size", sa.Integer(), nullable=False),
        sa.Column("overlap", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "running",
                "partial",
                "succeeded",
                "failed",
                name="run_status",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "configuration_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_extraction_runs_valid_configuration_hash"),
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["knowledge.source_versions.id"],
            name=op.f("fk_extraction_runs_source_version_id_source_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_runs")),
        sa.UniqueConstraint(
            "id",
            "source_version_id",
            name=op.f("uq_extraction_runs_id_source_version_id"),
        ),
        sa.UniqueConstraint(
            "source_version_id",
            "task",
            "provider",
            "model",
            "prompt_version",
            "configuration_hash",
            name=op.f(
                "uq_extraction_runs_source_version_id_task_provider_model_prompt_version_configuration_hash"
            ),
        ),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_extraction_runs_source_version_id"),
        "extraction_runs",
        ["source_version_id"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "extraction_windows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("window_size", sa.Integer(), nullable=False),
        sa.Column("overlap", sa.Integer(), nullable=False),
        sa.Column("start_seconds", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("end_seconds", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_extraction_windows_valid_content_hash"),
        ),
        sa.CheckConstraint(
            "overlap >= 0 AND overlap < window_size",
            name=op.f("ck_extraction_windows_valid_overlap"),
        ),
        sa.CheckConstraint(
            "sequence > 0", name=op.f("ck_extraction_windows_positive_sequence")
        ),
        sa.CheckConstraint(
            "window_size > 0", name=op.f("ck_extraction_windows_positive_window_size")
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["knowledge.source_versions.id"],
            name=op.f("fk_extraction_windows_source_version_id_source_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_windows")),
        sa.UniqueConstraint(
            "id",
            "source_version_id",
            name=op.f("uq_extraction_windows_id_source_version_id"),
        ),
        sa.UniqueConstraint(
            "source_version_id",
            "sequence",
            "window_size",
            "overlap",
            name=op.f(
                "uq_extraction_windows_source_version_id_sequence_window_size_overlap"
            ),
        ),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_extraction_windows_source_version_id"),
        "extraction_windows",
        ["source_version_id"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "source_segments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("start_seconds", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("end_seconds", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("speaker_person_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_segments_valid_content_hash"),
        ),
        sa.CheckConstraint(
            "end_seconds > start_seconds",
            name=op.f("ck_source_segments_valid_interval"),
        ),
        sa.CheckConstraint(
            "sequence > 0", name=op.f("ck_source_segments_positive_sequence")
        ),
        sa.CheckConstraint(
            "start_seconds >= 0", name=op.f("ck_source_segments_nonnegative_start")
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["knowledge.source_versions.id"],
            name=op.f("fk_source_segments_source_version_id_source_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["speaker_person_id"],
            ["knowledge.people.id"],
            name=op.f("fk_source_segments_speaker_person_id_people"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_segments")),
        sa.UniqueConstraint(
            "id",
            "source_version_id",
            name=op.f("uq_source_segments_id_source_version_id"),
        ),
        sa.UniqueConstraint(
            "source_version_id",
            "sequence",
            name=op.f("uq_source_segments_source_version_id_sequence"),
        ),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_source_segments_source_version_id"),
        "source_segments",
        ["source_version_id"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "external_claims",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_segment_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("claimant_person_id", sa.Uuid(), nullable=True),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("normalized_claim_text", sa.Text(), nullable=False),
        sa.Column("claim_domain", sa.String(length=255), nullable=False),
        sa.Column("claim_type", sa.String(length=128), nullable=False),
        sa.Column("extraction_confidence", sa.Float(), nullable=False),
        sa.Column(
            "verification_status",
            postgresql.ENUM(
                "unverified",
                "attributed_only",
                "supported",
                "mixed",
                "contradicted",
                "insufficient",
                "not_applicable",
                name="verification_status",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "extraction_confidence >= 0 AND extraction_confidence <= 1",
            name=op.f("ck_external_claims_valid_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["claimant_person_id"],
            ["knowledge.people.id"],
            name=op.f("fk_external_claims_claimant_person_id_people"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id", "source_version_id"],
            [
                "knowledge.extraction_runs.id",
                "knowledge.extraction_runs.source_version_id",
            ],
            name=op.f(
                "fk_external_claims_extraction_run_id_source_version_id_extraction_runs"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_segment_id", "source_version_id"],
            [
                "knowledge.source_segments.id",
                "knowledge.source_segments.source_version_id",
            ],
            name=op.f(
                "fk_external_claims_source_segment_id_source_version_id_source_segments"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_claims")),
        sa.UniqueConstraint(
            "extraction_run_id",
            "source_segment_id",
            "normalized_claim_text",
            name=op.f(
                "uq_external_claims_extraction_run_id_source_segment_id_normalized_claim_text"
            ),
        ),
        schema="knowledge",
    )
    op.create_table(
        "extraction_window_segments",
        sa.Column("window_id", sa.Uuid(), nullable=False),
        sa.Column("source_segment_id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_in_window", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_segment_id", "source_version_id"],
            [
                "knowledge.source_segments.id",
                "knowledge.source_segments.source_version_id",
            ],
            name=op.f(
                "fk_extraction_window_segments_source_segment_id_source_version_id_source_segments"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["window_id", "source_version_id"],
            [
                "knowledge.extraction_windows.id",
                "knowledge.extraction_windows.source_version_id",
            ],
            name=op.f(
                "fk_extraction_window_segments_window_id_source_version_id_extraction_windows"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "window_id", "source_segment_id", name=op.f("pk_extraction_window_segments")
        ),
        sa.UniqueConstraint(
            "window_id",
            "sequence_in_window",
            name=op.f("uq_extraction_window_segments_window_id_sequence_in_window"),
        ),
        schema="knowledge",
    )
    op.create_table(
        "mentions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_segment_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "entity_type",
            postgresql.ENUM(
                "person",
                "work",
                "organization",
                "concept",
                name="entity_type",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("surface_text", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "resolution_status",
            postgresql.ENUM(
                "resolved",
                "review",
                "unresolved",
                "rejected",
                name="resolution_status",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("work_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("concept_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_mentions_valid_confidence"),
        ),
        sa.CheckConstraint(
            "num_nonnulls(person_id, work_id, organization_id, concept_id) <= 1",
            name=op.f("ck_mentions_at_most_one_resolution"),
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["knowledge.external_concepts.id"],
            name=op.f("fk_mentions_concept_id_external_concepts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id", "source_version_id"],
            [
                "knowledge.extraction_runs.id",
                "knowledge.extraction_runs.source_version_id",
            ],
            name=op.f(
                "fk_mentions_extraction_run_id_source_version_id_extraction_runs"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["knowledge.organizations.id"],
            name=op.f("fk_mentions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["knowledge.people.id"],
            name=op.f("fk_mentions_person_id_people"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_segment_id", "source_version_id"],
            [
                "knowledge.source_segments.id",
                "knowledge.source_segments.source_version_id",
            ],
            name=op.f(
                "fk_mentions_source_segment_id_source_version_id_source_segments"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["knowledge.works.id"],
            name=op.f("fk_mentions_work_id_works"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mentions")),
        sa.UniqueConstraint(
            "extraction_run_id",
            "source_segment_id",
            "entity_type",
            "surface_text",
            name=op.f(
                "uq_mentions_extraction_run_id_source_segment_id_entity_type_surface_text"
            ),
        ),
        schema="knowledge",
    )
    op.create_index(
        "ix_knowledge_mentions_resolution",
        "mentions",
        ["resolution_status", "entity_type"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "window_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("window_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "succeeded",
                "failed",
                name="window_status",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column(
            "structured_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("output_hash", sa.String(length=64), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("diagnostics", sa.Text(), nullable=True),
        sa.Column("elapsed_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "output_hash IS NULL OR output_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_window_results_valid_output_hash"),
        ),
        sa.CheckConstraint(
            "attempt_count > 0", name=op.f("ck_window_results_positive_attempt_count")
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["knowledge.extraction_runs.id"],
            name=op.f("fk_window_results_extraction_run_id_extraction_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["window_id"],
            ["knowledge.extraction_windows.id"],
            name=op.f("fk_window_results_window_id_extraction_windows"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_window_results")),
        sa.UniqueConstraint(
            "extraction_run_id",
            "window_id",
            name=op.f("uq_window_results_extraction_run_id_window_id"),
        ),
        schema="knowledge",
    )
    op.create_index(
        "ix_knowledge_window_results_retry",
        "window_results",
        ["extraction_run_id", "status"],
        unique=False,
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_window_results_extraction_run_id"),
        "window_results",
        ["extraction_run_id"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "claim_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation",
            postgresql.ENUM(
                "supports",
                "contradicts",
                "contextualizes",
                "mentions",
                "background",
                "unclear",
                name="evidence_relation",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("work_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("source_segment_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "num_nonnulls(work_id, source_id, source_segment_id) = 1",
            name=op.f("ck_claim_evidence_one_typed_evidence_target"),
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["knowledge.external_claims.id"],
            name=op.f("fk_claim_evidence_claim_id_external_claims"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["knowledge.sources.id"],
            name=op.f("fk_claim_evidence_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_segment_id"],
            ["knowledge.source_segments.id"],
            name=op.f("fk_claim_evidence_source_segment_id_source_segments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["knowledge.works.id"],
            name=op.f("fk_claim_evidence_work_id_works"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_evidence")),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_claim_evidence_claim_id"),
        "claim_evidence",
        ["claim_id"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "resolution_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mention_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            postgresql.ENUM(
                "crossref",
                "openalex",
                "openlibrary",
                "wikidata",
                name="resolution_provider",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("candidate_key", sa.String(length=512), nullable=False),
        sa.Column(
            "candidate_type",
            postgresql.ENUM(
                "person",
                "work",
                "organization",
                "concept",
                name="entity_type",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("candidate_name", sa.String(length=1024), nullable=False),
        sa.Column(
            "candidate_identifiers",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("candidate_url", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "resolved",
                "review",
                "unresolved",
                "rejected",
                name="resolution_status",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "score >= 0 AND score <= 100",
            name=op.f("ck_resolution_candidates_valid_score"),
        ),
        sa.ForeignKeyConstraint(
            ["mention_id"],
            ["knowledge.mentions.id"],
            name=op.f("fk_resolution_candidates_mention_id_mentions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resolution_candidates")),
        sa.UniqueConstraint(
            "mention_id",
            "provider",
            "candidate_key",
            name=op.f("uq_resolution_candidates_mention_id_provider_candidate_key"),
        ),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_resolution_candidates_mention_id"),
        "resolution_candidates",
        ["mention_id"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "review_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reason",
            postgresql.ENUM(
                "ambiguous_person",
                "ambiguous_work",
                "uncertain_title",
                "unresolved_reference",
                "multiple_high_scoring_matches",
                "potential_duplicate_entity",
                "transcript_anomaly",
                "extraction_anomaly",
                "unsupported_metadata",
                "media_rights_uncertainty",
                name="review_reason",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "open",
                "in_review",
                "resolved",
                "rejected",
                name="knowledge_review_status",
                schema="knowledge",
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("mention_id", sa.Uuid(), nullable=True),
        sa.Column("window_result_id", sa.Uuid(), nullable=True),
        sa.Column("resolution_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("media_asset_id", sa.Uuid(), nullable=True),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status IN ('open', 'in_review') AND reviewed_at IS NULL) OR (status IN ('resolved', 'rejected') AND reviewed_at IS NOT NULL)",
            name=op.f("ck_review_flags_review_completion_metadata"),
        ),
        sa.CheckConstraint(
            "num_nonnulls(mention_id, window_result_id, resolution_candidate_id, media_asset_id) <= 1",
            name=op.f("ck_review_flags_at_most_one_specific_target"),
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["knowledge.media_assets.id"],
            name=op.f("fk_review_flags_media_asset_id_media_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mention_id"],
            ["knowledge.mentions.id"],
            name=op.f("fk_review_flags_mention_id_mentions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolution_candidate_id"],
            ["knowledge.resolution_candidates.id"],
            name=op.f("fk_review_flags_resolution_candidate_id_resolution_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["knowledge.source_versions.id"],
            name=op.f("fk_review_flags_source_version_id_source_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["window_result_id"],
            ["knowledge.window_results.id"],
            name=op.f("fk_review_flags_window_result_id_window_results"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_flags")),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_review_flags_source_version_id"),
        "review_flags",
        ["source_version_id"],
        unique=False,
        schema="knowledge",
    )
    op.execute(
        """
        CREATE FUNCTION knowledge.reject_external_provenance_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'external source versions and raw segments are immutable';
        END;
        $$;
        CREATE TRIGGER source_versions_immutable
          BEFORE UPDATE OR DELETE ON knowledge.source_versions
          FOR EACH ROW EXECUTE FUNCTION knowledge.reject_external_provenance_mutation();
        CREATE TRIGGER source_segments_immutable
          BEFORE UPDATE OR DELETE ON knowledge.source_segments
          FOR EACH ROW EXECUTE FUNCTION knowledge.reject_external_provenance_mutation();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER source_segments_immutable ON knowledge.source_segments")
    op.execute("DROP TRIGGER source_versions_immutable ON knowledge.source_versions")
    op.execute("DROP FUNCTION knowledge.reject_external_provenance_mutation()")
    op.drop_index(
        op.f("ix_review_flags_source_version_id"),
        table_name="review_flags",
        schema="knowledge",
    )
    op.drop_table("review_flags", schema="knowledge")
    op.drop_index(
        op.f("ix_resolution_candidates_mention_id"),
        table_name="resolution_candidates",
        schema="knowledge",
    )
    op.drop_table("resolution_candidates", schema="knowledge")
    op.drop_index(
        op.f("ix_claim_evidence_claim_id"),
        table_name="claim_evidence",
        schema="knowledge",
    )
    op.drop_table("claim_evidence", schema="knowledge")
    op.drop_index(
        op.f("ix_window_results_extraction_run_id"),
        table_name="window_results",
        schema="knowledge",
    )
    op.drop_index(
        "ix_knowledge_window_results_retry",
        table_name="window_results",
        schema="knowledge",
    )
    op.drop_table("window_results", schema="knowledge")
    op.drop_index(
        "ix_knowledge_mentions_resolution", table_name="mentions", schema="knowledge"
    )
    op.drop_table("mentions", schema="knowledge")
    op.drop_table("extraction_window_segments", schema="knowledge")
    op.drop_table("external_claims", schema="knowledge")
    op.drop_index(
        op.f("ix_source_segments_source_version_id"),
        table_name="source_segments",
        schema="knowledge",
    )
    op.drop_table("source_segments", schema="knowledge")
    op.drop_index(
        op.f("ix_extraction_windows_source_version_id"),
        table_name="extraction_windows",
        schema="knowledge",
    )
    op.drop_table("extraction_windows", schema="knowledge")
    op.drop_index(
        op.f("ix_extraction_runs_source_version_id"),
        table_name="extraction_runs",
        schema="knowledge",
    )
    op.drop_table("extraction_runs", schema="knowledge")
    op.drop_table("work_media_assets", schema="knowledge")
    op.drop_index(
        op.f("ix_source_versions_source_id"),
        table_name="source_versions",
        schema="knowledge",
    )
    op.drop_table("source_versions", schema="knowledge")
    op.drop_table("source_quality", schema="knowledge")
    op.drop_table("source_media_assets", schema="knowledge")
    op.drop_table("person_media_assets", schema="knowledge")
    op.drop_table("channel_creators", schema="knowledge")
    op.drop_table("work_authors", schema="knowledge")
    op.drop_table("sources", schema="knowledge")
    op.drop_table("media_assets", schema="knowledge")
    op.drop_table("external_identifiers", schema="knowledge")
    op.drop_table("entity_labels", schema="knowledge")
    op.drop_table("creators", schema="knowledge")
    op.drop_index(
        op.f("ix_works_normalized_title"), table_name="works", schema="knowledge"
    )
    op.drop_table("works", schema="knowledge")
    op.drop_index(
        op.f("ix_people_normalized_name"), table_name="people", schema="knowledge"
    )
    op.drop_table("people", schema="knowledge")
    op.drop_index(
        op.f("ix_organizations_normalized_name"),
        table_name="organizations",
        schema="knowledge",
    )
    op.drop_table("organizations", schema="knowledge")
    op.drop_index(
        op.f("ix_external_concepts_normalized_name"),
        table_name="external_concepts",
        schema="knowledge",
    )
    op.drop_table("external_concepts", schema="knowledge")
    op.drop_table("channels", schema="knowledge")
    for enum_name in (
        "knowledge_review_status",
        "review_reason",
        "resolution_provider",
        "evidence_relation",
        "window_status",
        "resolution_status",
        "entity_type",
        "verification_status",
        "run_status",
        "ingestion_status",
        "source_type",
        "media_status",
        "media_type",
        "identifier_scheme",
        "label_kind",
        "work_type",
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS knowledge."{enum_name}"'))
    # ### end Alembic commands ###
