"""add lecture project creator

Revision ID: 621e48994058
Revises: 7ccde9741dbf
Create Date: 2026-09-23 00:53:00.567474
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '621e48994058'
down_revision: str | None = '7ccde9741dbf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_projects', sa.Column('created_by', sa.String(length=255), nullable=False), schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_projects', 'created_by', schema='content')
    # ### end Alembic commands ###
