"""add content strategy and publication packages

Revision ID: 6338422a845d
Revises: 9ed8d9eeddf0
Create Date: 2026-09-23 07:57:10.099616
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6338422a845d"
down_revision: str | None = "9ed8d9eeddf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_series",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PLANNED",
                "IN_PRODUCTION",
                "READY",
                "ARCHIVED",
                name="content_status",
                schema="content",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_series")),
        sa.UniqueConstraint("stable_key", name=op.f("uq_content_series_stable_key")),
        schema="content",
    )
    op.create_table(
        "content_topics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("human_question", sa.Text(), nullable=False),
        sa.Column("primary_concept_key", sa.String(length=255), nullable=False),
        sa.Column("life_domain", sa.String(length=64), nullable=False),
        sa.Column(
            "lecture_angle",
            postgresql.ENUM(
                "foundation",
                "distinction",
                "human_question",
                "application",
                "dialogue",
                "critique",
                "open_question",
                "reference_deep_dive",
                name="lecture_angle",
                schema="content",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PLANNED",
                "IN_PRODUCTION",
                "READY",
                "ARCHIVED",
                name="content_status",
                schema="content",
            ),
            nullable=False,
        ),
        sa.Column("semantic_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_topics")),
        sa.UniqueConstraint("stable_key", name=op.f("uq_content_topics_stable_key")),
        schema="content",
    )
    op.create_table(
        "content_pathways",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("series_id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PLANNED",
                "IN_PRODUCTION",
                "READY",
                "ARCHIVED",
                name="content_status",
                schema="content",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["content.content_series.id"],
            name=op.f("fk_content_pathways_series_id_content_series"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_pathways")),
        sa.UniqueConstraint("stable_key", name=op.f("uq_content_pathways_stable_key")),
        schema="content",
    )
    op.create_table(
        "content_topic_relations",
        sa.Column("from_topic_id", sa.Uuid(), nullable=False),
        sa.Column("to_topic_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation_type",
            postgresql.ENUM(
                "PRECEDES",
                "FOLLOWS",
                "RELATED",
                "DEEPENS",
                "CONTRASTS",
                name="topic_relation_type",
                schema="content",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_topic_id"],
            ["content.content_topics.id"],
            name=op.f("fk_content_topic_relations_from_topic_id_content_topics"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_topic_id"],
            ["content.content_topics.id"],
            name=op.f("fk_content_topic_relations_to_topic_id_content_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "from_topic_id", "to_topic_id", name=op.f("pk_content_topic_relations")
        ),
        schema="content",
    )
    op.create_table(
        "content_coverage",
        sa.Column("lecture_master_version_id", sa.Uuid(), nullable=False),
        sa.Column("concept_key", sa.String(length=255), nullable=False),
        sa.Column("distinction_key", sa.String(length=255), nullable=True),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lecture_master_version_id"],
            ["content.lecture_master_versions.id"],
            name=op.f(
                "fk_content_coverage_lecture_master_version_id_lecture_master_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "lecture_master_version_id",
            "concept_key",
            "distinction_key",
            name=op.f("pk_content_coverage"),
        ),
        schema="content",
    )
    op.create_table(
        "content_lecture_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lecture_master_version_id", sa.Uuid(), nullable=False),
        sa.Column("series_id", sa.Uuid(), nullable=False),
        sa.Column("pathway_id", sa.Uuid(), nullable=True),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PLANNED",
                "IN_PRODUCTION",
                "READY",
                "ARCHIVED",
                name="content_status",
                schema="content",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lecture_master_version_id"],
            ["content.lecture_master_versions.id"],
            name=op.f(
                "fk_content_lecture_links_lecture_master_version_id_lecture_master_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pathway_id"],
            ["content.content_pathways.id"],
            name=op.f("fk_content_lecture_links_pathway_id_content_pathways"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["content.content_series.id"],
            name=op.f("fk_content_lecture_links_series_id_content_series"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["content.content_topics.id"],
            name=op.f("fk_content_lecture_links_topic_id_content_topics"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_lecture_links")),
        sa.UniqueConstraint(
            "lecture_master_version_id",
            name=op.f("uq_content_lecture_links_lecture_master_version_id"),
        ),
        schema="content",
    )
    op.create_table(
        "content_repetition_assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lecture_master_version_id", sa.Uuid(), nullable=False),
        sa.Column("compared_lecture_master_version_id", sa.Uuid(), nullable=False),
        sa.Column("overlap_score", sa.Float(), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "decision",
            postgresql.ENUM(
                "ALLOW_DEEPENING",
                "REVIEW_REQUIRED",
                "BLOCK_DUPLICATE",
                name="repetition_decision",
                schema="content",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["compared_lecture_master_version_id"],
            ["content.lecture_master_versions.id"],
            name=op.f(
                "fk_content_repetition_assessments_compared_lecture_master_version_id_lecture_master_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lecture_master_version_id"],
            ["content.lecture_master_versions.id"],
            name=op.f(
                "fk_content_repetition_assessments_lecture_master_version_id_lecture_master_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_repetition_assessments")),
        schema="content",
    )
    op.create_table(
        "publication_package_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lecture_master_version_id", sa.Uuid(), nullable=False),
        sa.Column("package_version", sa.Integer(), nullable=False),
        sa.Column("root_path", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "CREATED",
                "VALIDATED",
                "FAILED",
                name="publication_package_status",
                schema="content",
            ),
            nullable=False,
        ),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lecture_master_version_id"],
            ["content.lecture_master_versions.id"],
            name=op.f(
                "fk_publication_package_records_lecture_master_version_id_lecture_master_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publication_package_records")),
        schema="content",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("publication_package_records", schema="content")
    op.drop_table("content_repetition_assessments", schema="content")
    op.drop_table("content_lecture_links", schema="content")
    op.drop_table("content_coverage", schema="content")
    op.drop_table("content_topic_relations", schema="content")
    op.drop_table("content_pathways", schema="content")
    op.drop_table("content_topics", schema="content")
    op.drop_table("content_series", schema="content")
    for enum_name in (
        "publication_package_status",
        "repetition_decision",
        "topic_relation_type",
        "lecture_angle",
        "content_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS content.{enum_name}")
    # ### end Alembic commands ###
