"""add semantic lecture master

Revision ID: 7ccde9741dbf
Revises: 0551b352aefb
Create Date: 2026-09-23 00:51:33.140188
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7ccde9741dbf'
down_revision: str | None = '0551b352aefb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('research_package_id', sa.Uuid(), nullable=False),
    sa.Column('lecture_type', postgresql.ENUM('FOUNDATION', 'HUMAN_QUESTION', 'DIALOGUE', 'APPLICATION', 'OPEN_QUESTION', 'CRITIQUE', 'RITUAL_COMPANION', 'REFERENCE_DEEP_DIVE', name='lecture_type', schema='content'), nullable=False),
    sa.Column('working_title', sa.String(length=512), nullable=False),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'ARCHITECTED', 'READY', 'FAILED', 'STALE', 'SUPERSEDED', name='lecture_project_status', schema='content'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_package_id'], ['content.research_packages.id'], name=op.f('fk_lecture_projects_research_package_id_research_packages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecture_projects')),
    schema='content'
    )
    op.create_table('lecture_master_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lecture_project_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('research_package_id', sa.Uuid(), nullable=False),
    sa.Column('research_package_version', sa.Integer(), nullable=False),
    sa.Column('research_package_content_hash', sa.String(length=64), nullable=False),
    sa.Column('canon_version_id', sa.Uuid(), nullable=False),
    sa.Column('manasek_version_id', sa.Uuid(), nullable=True),
    sa.Column('package_authority', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('central_human_question', sa.Text(), nullable=False),
    sa.Column('ending_mode', sa.String(length=32), nullable=False),
    sa.Column('architecture', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prohibited_conflations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uncertainty_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'ARCHITECTED', 'VALIDATING', 'READY', 'FAILED', 'STALE', 'SUPERSEDED', name='lecture_master_status', schema='content'), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_project_id'], ['content.lecture_projects.id'], name=op.f('fk_lecture_master_versions_lecture_project_id_lecture_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['research_package_id'], ['content.research_packages.id'], name=op.f('fk_lecture_master_versions_research_package_id_research_packages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecture_master_versions')),
    schema='content'
    )
    op.create_table('lecture_ritual_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lecture_master_version_id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('ritual_version_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('safety_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['lecture_master_version_id'], ['content.lecture_master_versions.id'], name=op.f('fk_lecture_ritual_links_lecture_master_version_id_lecture_master_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_lecture_ritual_links_package_id_research_packages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecture_ritual_links')),
    schema='content'
    )
    op.create_table('lecture_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lecture_master_version_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('role', postgresql.ENUM('HUMAN_ENTRY', 'AYIN_FRAME', 'CONCEPT_DEFINITION', 'DISTINCTION', 'EXTERNAL_DIALOGUE', 'EMPIRICAL_EVIDENCE', 'PHILOSOPHICAL_DIALOGUE', 'COUNTERARGUMENT', 'LIMITATION', 'OPEN_QUESTION', 'LIFE_RETURN', 'RITUAL_BRIDGE', 'CONCLUSION', name='lecture_section_role', schema='content'), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('rhetorical_function', sa.Text(), nullable=False),
    sa.Column('transition_intent', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('required_terminology', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prohibited_formulations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['lecture_master_version_id'], ['content.lecture_master_versions.id'], name=op.f('fk_lecture_sections_lecture_master_version_id_lecture_master_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecture_sections')),
    schema='content'
    )
    op.create_table('master_exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lecture_master_version_id', sa.Uuid(), nullable=False),
    sa.Column('export_version', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lecture_master_version_id'], ['content.lecture_master_versions.id'], name=op.f('fk_master_exports_lecture_master_version_id_lecture_master_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_exports')),
    schema='content'
    )
    op.create_table('validation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lecture_master_version_id', sa.Uuid(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lecture_master_version_id'], ['content.lecture_master_versions.id'], name=op.f('fk_validation_runs_lecture_master_version_id_lecture_master_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_runs')),
    schema='content'
    )
    op.create_table('lecture_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lecture_master_version_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('stable_key', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('claim_intent', sa.Text(), nullable=False),
    sa.Column('claim_origin', postgresql.ENUM('AYIN', 'EXTERNAL', 'SYNTHESIS', 'OPEN_QUESTION', 'RITUAL_CONTEXT', 'EXAMPLE', name='claim_origin', schema='content'), nullable=False),
    sa.Column('discourse_type', postgresql.ENUM('CONCEPTUAL', 'DESCRIPTIVE', 'ETHICAL', 'OPTIONAL_METAPHYSICAL', name='lecture_discourse_type', schema='content'), nullable=True),
    sa.Column('epistemic_status', postgresql.ENUM('AYIN_DEFINITION', 'AYIN_PRINCIPLE', 'AYIN_DISTINCTION', 'AYIN_ETHICAL_ORIENTATION', 'AYIN_DESCRIPTIVE_STATEMENT', 'OPTIONAL_METAPHYSICAL_INTERPRETATION', 'EXTERNAL_EMPIRICAL_CLAIM', 'EXTERNAL_PHILOSOPHICAL_ARGUMENT', 'EXTERNAL_ATTRIBUTED_CLAIM', 'CONCEPTUAL_PARALLEL', 'NON_EQUIVALENCE', 'COUNTEREVIDENCE', 'ALTERNATIVE_EXPLANATION', 'SYNTHESIS_INFERENCE', 'OPEN_QUESTION', 'ILLUSTRATIVE_EXAMPLE', 'RITUAL_CONTEXT', name='claim_epistemic_status', schema='content'), nullable=False),
    sa.Column('certainty', sa.String(length=32), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('formulation_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['lecture_master_version_id'], ['content.lecture_master_versions.id'], name=op.f('fk_lecture_claims_lecture_master_version_id_lecture_master_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['content.lecture_sections.id'], name=op.f('fk_lecture_claims_section_id_lecture_sections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecture_claims')),
    schema='content'
    )
    op.create_table('validation_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('validation_run_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', postgresql.ENUM('AYIN_FIDELITY', 'EPISTEMIC_INTEGRITY', 'CITATION_COVERAGE', 'DIALOGUE_STATUS', 'COUNTEREVIDENCE_HANDLING', 'OPEN_QUESTION_PRESERVATION', 'RITUAL_BOUNDARY', 'PACKAGE_TRACEABILITY', name='lecture_validation_dimension', schema='content'), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['content.validation_runs.id'], name=op.f('fk_validation_findings_validation_run_id_validation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_findings')),
    schema='content'
    )
    op.create_table('lecture_citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lecture_master_version_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('kind', postgresql.ENUM('AYIN', 'MANASEK', 'EXTERNAL', name='citation_kind', schema='content'), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('citation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['content.lecture_claims.id'], name=op.f('fk_lecture_citations_claim_id_lecture_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lecture_master_version_id'], ['content.lecture_master_versions.id'], name=op.f('fk_lecture_citations_lecture_master_version_id_lecture_master_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_lecture_citations_package_id_research_packages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecture_citations')),
    schema='content'
    )
    op.create_table('lecture_claim_dependencies',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('premise_claim_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['content.lecture_claims.id'], name=op.f('fk_lecture_claim_dependencies_claim_id_lecture_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['premise_claim_id'], ['content.lecture_claims.id'], name=op.f('fk_lecture_claim_dependencies_premise_claim_id_lecture_claims'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('claim_id', 'premise_claim_id', name=op.f('pk_lecture_claim_dependencies')),
    schema='content'
    )
    op.create_table('lecture_claim_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_kind', postgresql.ENUM('AYIN_PASSAGE', 'AYIN_CONCEPT', 'AYIN_PRINCIPLE', 'AYIN_DISTINCTION', 'AYIN_OPEN_QUESTION', 'EXTERNAL_CHUNK', 'DIALOGUE_RELATION', 'RITUAL_VERSION', name='lecture_evidence_kind', schema='content'), nullable=False),
    sa.Column('evidence_item_id', sa.String(length=255), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('binding_role', postgresql.ENUM('PRIMARY', 'SUPPORTING', 'COUNTEREVIDENCE', 'PREMISE', 'CONTEXT', name='evidence_binding_role', schema='content'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['content.lecture_claims.id'], name=op.f('fk_lecture_claim_evidence_claim_id_lecture_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['content.research_packages.id'], name=op.f('fk_lecture_claim_evidence_package_id_research_packages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecture_claim_evidence')),
    schema='content'
    )
    op.execute("""
    CREATE FUNCTION content.prevent_ready_lecture_master_mutation()
    RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF OLD.status = 'READY' AND (TG_OP = 'DELETE' OR NEW.status <> 'READY'
            OR NEW.input_hash <> OLD.input_hash
            OR NEW.research_package_content_hash <> OLD.research_package_content_hash
            OR NEW.architecture <> OLD.architecture) THEN
            RAISE EXCEPTION 'READY LectureMasterVersion % is immutable', OLD.id;
        END IF;
        RETURN COALESCE(NEW, OLD);
    END;
    $$;
    CREATE TRIGGER lecture_master_ready_immutable
    BEFORE UPDATE OR DELETE ON content.lecture_master_versions
    FOR EACH ROW EXECUTE FUNCTION content.prevent_ready_lecture_master_mutation();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS lecture_master_ready_immutable ON content.lecture_master_versions")
    op.execute("DROP FUNCTION IF EXISTS content.prevent_ready_lecture_master_mutation()")
    op.drop_table('lecture_claim_evidence', schema='content')
    op.drop_table('lecture_claim_dependencies', schema='content')
    op.drop_table('lecture_citations', schema='content')
    op.drop_table('validation_findings', schema='content')
    op.drop_table('lecture_claims', schema='content')
    op.drop_table('validation_runs', schema='content')
    op.drop_table('master_exports', schema='content')
    op.drop_table('lecture_sections', schema='content')
    op.drop_table('lecture_ritual_links', schema='content')
    op.drop_table('lecture_master_versions', schema='content')
    op.drop_table('lecture_projects', schema='content')
    for enum_name in (
        'evidence_binding_role', 'lecture_evidence_kind', 'citation_kind',
        'lecture_validation_dimension', 'claim_epistemic_status',
        'lecture_discourse_type', 'claim_origin', 'lecture_section_role',
        'lecture_master_status', 'lecture_project_status', 'lecture_type',
    ):
        op.execute(f'DROP TYPE IF EXISTS content.{enum_name}')
    # ### end Alembic commands ###
