"""add semantic lecture claim payload

Revision ID: 9ed8d9eeddf0
Revises: 2fbe8fb75b5a
Create Date: 2026-09-23 07:23:05.894289
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9ed8d9eeddf0"
down_revision: str | None = "2fbe8fb75b5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lecture_claims",
        sa.Column("semantic_proposition", sa.Text(), nullable=True),
        schema="content",
    )
    op.add_column(
        "lecture_claims",
        sa.Column("plain_meaning", sa.Text(), nullable=True),
        schema="content",
    )
    op.add_column(
        "lecture_claims",
        sa.Column(
            "required_concepts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        schema="content",
    )
    op.add_column(
        "lecture_claims",
        sa.Column(
            "required_qualifiers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        schema="content",
    )
    op.add_column(
        "lecture_claims",
        sa.Column(
            "prohibited_overstatements",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        schema="content",
    )
    op.add_column(
        "lecture_claims",
        sa.Column("source_support_summary", sa.Text(), nullable=True),
        schema="content",
    )
    op.add_column(
        "lecture_claims",
        sa.Column(
            "source_evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        schema="content",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lecture_claims", "source_evidence", schema="content")
    op.drop_column("lecture_claims", "source_support_summary", schema="content")
    op.drop_column("lecture_claims", "prohibited_overstatements", schema="content")
    op.drop_column("lecture_claims", "required_qualifiers", schema="content")
    op.drop_column("lecture_claims", "required_concepts", schema="content")
    op.drop_column("lecture_claims", "plain_meaning", schema="content")
    op.drop_column("lecture_claims", "semantic_proposition", schema="content")
    # ### end Alembic commands ###
