"""add hybrid retrieval infrastructure

Revision ID: effbbb690796
Revises: 2d874648966b
Create Date: 2026-09-19 21:19:27.084202
"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "effbbb690796"
down_revision: str | None = "2d874648966b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE retrieval.build_status AS ENUM ('pending', 'running', 'succeeded', 'partial', 'failed')"
    )
    op.execute("CREATE TYPE retrieval.distance_metric AS ENUM ('cosine')")
    op.execute("CREATE TYPE retrieval.query_language AS ENUM ('fa', 'en', 'ar')")
    op.execute(
        "CREATE TYPE retrieval.retrieval_lane AS ENUM ('ayin', 'manasek', 'external')"
    )
    op.execute(
        "CREATE TYPE retrieval.retrieval_source_kind AS ENUM ('ayin_passage', 'ritual_passage', 'ritual_content', 'external_segment')"
    )
    op.execute(
        "CREATE TYPE retrieval.evaluation_query_type AS ENUM ('exact_concept', 'paraphrase', 'name_or_title', 'cross_language', 'distinction_trap', 'metaphysical_trap', 'ritual_safety', 'external_evidence')"
    )
    op.create_table(
        "chunking_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("configuration_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("normalization_version", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "running",
                "succeeded",
                "partial",
                "failed",
                name="build_status",
                schema="retrieval",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("output_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "configuration_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_chunking_runs_valid_configuration_hash"),
        ),
        sa.CheckConstraint(
            "input_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_chunking_runs_valid_input_hash"),
        ),
        sa.CheckConstraint(
            "output_hash IS NULL OR output_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_chunking_runs_valid_output_hash"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunking_runs")),
        sa.UniqueConstraint(
            "input_hash",
            "configuration_hash",
            name=op.f("uq_chunking_runs_input_hash_configuration_hash"),
        ),
        schema="retrieval",
    )
    op.create_table(
        "configurations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column(
            "parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("configuration_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "configuration_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_configurations_valid_configuration_hash"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configurations")),
        sa.UniqueConstraint(
            "configuration_hash", name=op.f("uq_configurations_configuration_hash")
        ),
        sa.UniqueConstraint(
            "name", "version", name=op.f("uq_configurations_name_version")
        ),
        schema="retrieval",
    )
    op.create_table(
        "embedding_models",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=128), nullable=False),
        sa.Column("model_name", sa.String(length=512), nullable=False),
        sa.Column("revision", sa.String(length=128), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column(
            "distance_metric",
            postgresql.ENUM(
                "cosine", name="distance_metric", schema="retrieval", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "language_capabilities",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("license", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "dimensions > 0 AND dimensions <= 2000",
            name=op.f("ck_embedding_models_valid_dimensions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embedding_models")),
        sa.UniqueConstraint(
            "provider",
            "model_name",
            "revision",
            name=op.f("uq_embedding_models_provider_model_name_revision"),
        ),
        schema="retrieval",
    )
    op.create_table(
        "evaluation_queries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=255), nullable=False),
        sa.Column(
            "language",
            postgresql.ENUM(
                "fa",
                "en",
                "ar",
                name="query_language",
                schema="retrieval",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column(
            "query_type",
            postgresql.ENUM(
                "exact_concept",
                "paraphrase",
                "name_or_title",
                "cross_language",
                "distinction_trap",
                "metaphysical_trap",
                "ritual_safety",
                "external_evidence",
                name="evaluation_query_type",
                schema="retrieval",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "expected_lane",
            postgresql.ENUM(
                "ayin",
                "manasek",
                "external",
                name="retrieval_lane",
                schema="retrieval",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_queries")),
        sa.UniqueConstraint(
            "stable_key",
            "language",
            name=op.f("uq_evaluation_queries_stable_key_language"),
        ),
        schema="retrieval",
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chunking_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "corpus_zone",
            postgresql.ENUM(
                "AYIN_CANON",
                "AYIN_WORKING",
                "MANASEK_CANON",
                "MANASEK_WORKING",
                "EXTERNAL_PRIMARY",
                "EXTERNAL_DERIVED",
                "GENERATED_CONTENT",
                name="corpus_zone",
                schema="core",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "lane",
            postgresql.ENUM(
                "ayin",
                "manasek",
                "external",
                name="retrieval_lane",
                schema="retrieval",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_kind",
            postgresql.ENUM(
                "ayin_passage",
                "ritual_passage",
                "ritual_content",
                "external_segment",
                name="retrieval_source_kind",
                schema="retrieval",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("section_title", sa.String(length=1024), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple', coalesce(normalized_text, ''))", persisted=True
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(lane = 'ayin' AND corpus_zone IN ('AYIN_WORKING', 'AYIN_CANON')) OR (lane = 'manasek' AND corpus_zone IN ('MANASEK_WORKING', 'MANASEK_CANON')) OR (lane = 'external' AND corpus_zone IN ('EXTERNAL_PRIMARY', 'EXTERNAL_DERIVED'))",
            name=op.f("ck_chunks_lane_matches_authority"),
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_chunks_valid_content_hash")
        ),
        sa.CheckConstraint("ordinal > 0", name=op.f("ck_chunks_positive_ordinal")),
        sa.CheckConstraint(
            "token_count > 0", name=op.f("ck_chunks_positive_token_count")
        ),
        sa.ForeignKeyConstraint(
            ["chunking_run_id"],
            ["retrieval.chunking_runs.id"],
            name=op.f("fk_chunks_chunking_run_id_chunking_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint(
            "chunking_run_id", "ordinal", name=op.f("uq_chunks_chunking_run_id_ordinal")
        ),
        sa.UniqueConstraint(
            "id", "chunking_run_id", name=op.f("uq_chunks_id_chunking_run_id")
        ),
        schema="retrieval",
    )
    op.create_index(
        op.f("ix_chunks_chunking_run_id"),
        "chunks",
        ["chunking_run_id"],
        unique=False,
        schema="retrieval",
    )
    op.create_index(
        "ix_retrieval_chunks_lane_language",
        "chunks",
        ["lane", "language"],
        unique=False,
        schema="retrieval",
    )
    op.create_index(
        "ix_retrieval_chunks_search_vector",
        "chunks",
        ["search_vector"],
        unique=False,
        schema="retrieval",
        postgresql_using="gin",
    )
    op.create_table(
        "embedding_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chunking_run_id", sa.Uuid(), nullable=False),
        sa.Column("embedding_model_id", sa.Uuid(), nullable=False),
        sa.Column("configuration_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "running",
                "succeeded",
                "partial",
                "failed",
                name="build_status",
                schema="retrieval",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("embedded_count", sa.Integer(), nullable=False),
        sa.Column("cache_hit_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "configuration_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_embedding_runs_valid_configuration_hash"),
        ),
        sa.ForeignKeyConstraint(
            ["chunking_run_id"],
            ["retrieval.chunking_runs.id"],
            name=op.f("fk_embedding_runs_chunking_run_id_chunking_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["embedding_model_id"],
            ["retrieval.embedding_models.id"],
            name=op.f("fk_embedding_runs_embedding_model_id_embedding_models"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embedding_runs")),
        sa.UniqueConstraint(
            "chunking_run_id",
            "embedding_model_id",
            "configuration_hash",
            name=op.f(
                "uq_embedding_runs_chunking_run_id_embedding_model_id_configuration_hash"
            ),
        ),
        schema="retrieval",
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chunking_run_id", sa.Uuid(), nullable=False),
        sa.Column("embedding_model_id", sa.Uuid(), nullable=False),
        sa.Column("configuration_id", sa.Uuid(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("query_count", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunking_run_id"],
            ["retrieval.chunking_runs.id"],
            name=op.f("fk_evaluation_runs_chunking_run_id_chunking_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["retrieval.configurations.id"],
            name=op.f("fk_evaluation_runs_configuration_id_configurations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["embedding_model_id"],
            ["retrieval.embedding_models.id"],
            name=op.f("fk_evaluation_runs_embedding_model_id_embedding_models"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
        schema="retrieval",
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chunking_run_id", sa.Uuid(), nullable=False),
        sa.Column("embedding_model_id", sa.Uuid(), nullable=False),
        sa.Column("configuration_id", sa.Uuid(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("normalized_query", sa.Text(), nullable=False),
        sa.Column(
            "language",
            postgresql.ENUM(
                "fa",
                "en",
                "ar",
                name="query_language",
                schema="retrieval",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunking_run_id"],
            ["retrieval.chunking_runs.id"],
            name=op.f("fk_runs_chunking_run_id_chunking_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["retrieval.configurations.id"],
            name=op.f("fk_runs_configuration_id_configurations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["embedding_model_id"],
            ["retrieval.embedding_models.id"],
            name=op.f("fk_runs_embedding_model_id_embedding_models"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        schema="retrieval",
    )
    op.create_table(
        "chunk_ayin_concepts",
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("concept_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["retrieval.chunks.id"],
            name=op.f("fk_chunk_ayin_concepts_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["core.ayin_concepts.id"],
            name=op.f("fk_chunk_ayin_concepts_concept_id_ayin_concepts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "chunk_id", "concept_id", name=op.f("pk_chunk_ayin_concepts")
        ),
        schema="retrieval",
    )
    op.create_table(
        "chunk_embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("embedding_model_id", sa.Uuid(), nullable=False),
        sa.Column("embedding_run_id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding", VECTOR(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_chunk_embeddings_valid_content_hash"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["retrieval.chunks.id"],
            name=op.f("fk_chunk_embeddings_chunk_id_chunks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["embedding_model_id"],
            ["retrieval.embedding_models.id"],
            name=op.f("fk_chunk_embeddings_embedding_model_id_embedding_models"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["embedding_run_id"],
            ["retrieval.embedding_runs.id"],
            name=op.f("fk_chunk_embeddings_embedding_run_id_embedding_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunk_embeddings")),
        sa.UniqueConstraint(
            "chunk_id",
            "embedding_model_id",
            "content_hash",
            name=op.f("uq_chunk_embeddings_chunk_id_embedding_model_id_content_hash"),
        ),
        schema="retrieval",
    )
    op.create_index(
        op.f("ix_chunk_embeddings_chunk_id"),
        "chunk_embeddings",
        ["chunk_id"],
        unique=False,
        schema="retrieval",
    )
    op.create_index(
        op.f("ix_chunk_embeddings_embedding_model_id"),
        "chunk_embeddings",
        ["embedding_model_id"],
        unique=False,
        schema="retrieval",
    )
    op.create_table(
        "chunk_external_entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("work_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("concept_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "num_nonnulls(person_id, work_id, organization_id, concept_id) = 1",
            name=op.f("ck_chunk_external_entities_one_typed_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["retrieval.chunks.id"],
            name=op.f("fk_chunk_external_entities_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["knowledge.external_concepts.id"],
            name=op.f("fk_chunk_external_entities_concept_id_external_concepts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["knowledge.organizations.id"],
            name=op.f("fk_chunk_external_entities_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["knowledge.people.id"],
            name=op.f("fk_chunk_external_entities_person_id_people"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["knowledge.works.id"],
            name=op.f("fk_chunk_external_entities_work_id_works"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunk_external_entities")),
        sa.UniqueConstraint(
            "chunk_id",
            "concept_id",
            name=op.f("uq_chunk_external_entities_chunk_id_concept_id"),
        ),
        sa.UniqueConstraint(
            "chunk_id",
            "organization_id",
            name=op.f("uq_chunk_external_entities_chunk_id_organization_id"),
        ),
        sa.UniqueConstraint(
            "chunk_id",
            "person_id",
            name=op.f("uq_chunk_external_entities_chunk_id_person_id"),
        ),
        sa.UniqueConstraint(
            "chunk_id",
            "work_id",
            name=op.f("uq_chunk_external_entities_chunk_id_work_id"),
        ),
        schema="retrieval",
    )
    op.create_index(
        op.f("ix_chunk_external_entities_chunk_id"),
        "chunk_external_entities",
        ["chunk_id"],
        unique=False,
        schema="retrieval",
    )
    op.create_table(
        "evaluation_judgments",
        sa.Column("evaluation_query_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("relevance", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "relevance >= 0 AND relevance <= 3",
            name=op.f("ck_evaluation_judgments_valid_relevance"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["retrieval.chunks.id"],
            name=op.f("fk_evaluation_judgments_chunk_id_chunks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_query_id"],
            ["retrieval.evaluation_queries.id"],
            name=op.f("fk_evaluation_judgments_evaluation_query_id_evaluation_queries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "evaluation_query_id", "chunk_id", name=op.f("pk_evaluation_judgments")
        ),
        schema="retrieval",
    )
    op.create_table(
        "results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("retrieval_run_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("lexical_rank", sa.Integer(), nullable=True),
        sa.Column("lexical_score", sa.Float(), nullable=True),
        sa.Column("dense_rank", sa.Integer(), nullable=True),
        sa.Column("dense_score", sa.Float(), nullable=True),
        sa.Column("entity_rank", sa.Integer(), nullable=True),
        sa.Column("entity_score", sa.Float(), nullable=True),
        sa.Column("fusion_score", sa.Float(), nullable=False),
        sa.Column("reranker_score", sa.Float(), nullable=False),
        sa.Column("final_rank", sa.Integer(), nullable=False),
        sa.Column(
            "expanded_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.CheckConstraint(
            "final_rank > 0", name=op.f("ck_results_positive_final_rank")
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["retrieval.chunks.id"],
            name=op.f("fk_results_chunk_id_chunks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["retrieval_run_id"],
            ["retrieval.runs.id"],
            name=op.f("fk_results_retrieval_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_results")),
        sa.UniqueConstraint(
            "retrieval_run_id",
            "chunk_id",
            name=op.f("uq_results_retrieval_run_id_chunk_id"),
        ),
        schema="retrieval",
    )
    op.create_index(
        op.f("ix_results_retrieval_run_id"),
        "results",
        ["retrieval_run_id"],
        unique=False,
        schema="retrieval",
    )
    op.create_table(
        "chunking_run_external_sources",
        sa.Column("chunking_run_id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunking_run_id"],
            ["retrieval.chunking_runs.id"],
            name=op.f("fk_chunking_run_external_sources_chunking_run_id_chunking_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["knowledge.source_versions.id"],
            name=op.f(
                "fk_chunking_run_external_sources_source_version_id_source_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "chunking_run_id",
            "source_version_id",
            name=op.f("pk_chunking_run_external_sources"),
        ),
        schema="retrieval",
    )
    op.create_table(
        "chunk_external_segments",
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("source_segment_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_in_chunk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["retrieval.chunks.id"],
            name=op.f("fk_chunk_external_segments_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_segment_id"],
            ["knowledge.source_segments.id"],
            name=op.f("fk_chunk_external_segments_source_segment_id_source_segments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "chunk_id", "source_segment_id", name=op.f("pk_chunk_external_segments")
        ),
        sa.UniqueConstraint(
            "chunk_id",
            "sequence_in_chunk",
            name=op.f("uq_chunk_external_segments_chunk_id_sequence_in_chunk"),
        ),
        schema="retrieval",
    )
    op.create_table(
        "chunking_run_ayin_sources",
        sa.Column("chunking_run_id", sa.Uuid(), nullable=False),
        sa.Column("canon_version_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunking_run_id"],
            ["retrieval.chunking_runs.id"],
            name=op.f("fk_chunking_run_ayin_sources_chunking_run_id_chunking_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id", "canon_version_id"],
            ["core.extraction_runs.id", "core.extraction_runs.canon_version_id"],
            name=op.f(
                "fk_chunking_run_ayin_sources_extraction_run_id_canon_version_id_extraction_runs"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "chunking_run_id",
            "canon_version_id",
            name=op.f("pk_chunking_run_ayin_sources"),
        ),
        schema="retrieval",
    )
    op.create_table(
        "chunk_canon_passages",
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("canon_passage_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_in_chunk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canon_passage_id"],
            ["core.canon_passages.id"],
            name=op.f("fk_chunk_canon_passages_canon_passage_id_canon_passages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["retrieval.chunks.id"],
            name=op.f("fk_chunk_canon_passages_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "chunk_id", "canon_passage_id", name=op.f("pk_chunk_canon_passages")
        ),
        sa.UniqueConstraint(
            "chunk_id",
            "sequence_in_chunk",
            name=op.f("uq_chunk_canon_passages_chunk_id_sequence_in_chunk"),
        ),
        schema="retrieval",
    )
    op.create_table(
        "chunking_run_ritual_sources",
        sa.Column("chunking_run_id", sa.Uuid(), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunking_run_id"],
            ["retrieval.chunking_runs.id"],
            name=op.f("fk_chunking_run_ritual_sources_chunking_run_id_chunking_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id", "source_version_id"],
            ["ritual.extraction_runs.id", "ritual.extraction_runs.source_version_id"],
            name=op.f(
                "fk_chunking_run_ritual_sources_extraction_run_id_source_version_id_extraction_runs"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "chunking_run_id",
            "source_version_id",
            name=op.f("pk_chunking_run_ritual_sources"),
        ),
        schema="retrieval",
    )
    op.create_table(
        "chunk_ritual_passages",
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("ritual_passage_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_in_chunk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["retrieval.chunks.id"],
            name=op.f("fk_chunk_ritual_passages_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ritual_passage_id"],
            ["ritual.passages.id"],
            name=op.f("fk_chunk_ritual_passages_ritual_passage_id_passages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "chunk_id", "ritual_passage_id", name=op.f("pk_chunk_ritual_passages")
        ),
        sa.UniqueConstraint(
            "chunk_id",
            "sequence_in_chunk",
            name=op.f("uq_chunk_ritual_passages_chunk_id_sequence_in_chunk"),
        ),
        schema="retrieval",
    )
    op.create_table(
        "chunk_ritual_versions",
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("ritual_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["retrieval.chunks.id"],
            name=op.f("fk_chunk_ritual_versions_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ritual_version_id"],
            ["ritual.ritual_versions.id"],
            name=op.f("fk_chunk_ritual_versions_ritual_version_id_ritual_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "chunk_id", "ritual_version_id", name=op.f("pk_chunk_ritual_versions")
        ),
        schema="retrieval",
    )
    op.execute(
        """
        CREATE FUNCTION retrieval.validate_chunk_membership()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            ayin_count integer;
            ritual_passage_count integer;
            ritual_content_count integer;
            external_count integer;
        BEGIN
            SELECT count(*) INTO ayin_count
              FROM retrieval.chunk_canon_passages WHERE chunk_id = NEW.id;
            SELECT count(*) INTO ritual_passage_count
              FROM retrieval.chunk_ritual_passages WHERE chunk_id = NEW.id;
            SELECT count(*) INTO ritual_content_count
              FROM retrieval.chunk_ritual_versions WHERE chunk_id = NEW.id;
            SELECT count(*) INTO external_count
              FROM retrieval.chunk_external_segments WHERE chunk_id = NEW.id;
            IF (NEW.source_kind = 'ayin_passage' AND ayin_count > 0
                AND ritual_passage_count = 0 AND ritual_content_count = 0
                AND external_count = 0)
               OR (NEW.source_kind = 'ritual_passage' AND ayin_count = 0
                AND ritual_passage_count > 0
                AND external_count = 0)
               OR (NEW.source_kind = 'ritual_content' AND ayin_count = 0
                AND ritual_passage_count = 0 AND ritual_content_count > 0
                AND external_count = 0)
               OR (NEW.source_kind = 'external_segment' AND ayin_count = 0
                AND ritual_passage_count = 0 AND ritual_content_count = 0
                AND external_count > 0) THEN
                RETURN NEW;
            END IF;
            RAISE EXCEPTION 'invalid typed membership for retrieval chunk %', NEW.id;
        END;
        $$;
        CREATE CONSTRAINT TRIGGER validate_chunk_membership
        AFTER INSERT ON retrieval.chunks
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION retrieval.validate_chunk_membership();

        CREATE FUNCTION retrieval.reject_immutable_change()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'retrieval source artifacts are immutable';
        END;
        $$;
        CREATE TRIGGER immutable_chunks
        BEFORE UPDATE OR DELETE ON retrieval.chunks
        FOR EACH ROW EXECUTE FUNCTION retrieval.reject_immutable_change();
        CREATE TRIGGER immutable_chunk_embeddings
        BEFORE UPDATE OR DELETE ON retrieval.chunk_embeddings
        FOR EACH ROW EXECUTE FUNCTION retrieval.reject_immutable_change();
        CREATE TRIGGER immutable_chunk_canon_passages
        BEFORE UPDATE OR DELETE ON retrieval.chunk_canon_passages
        FOR EACH ROW EXECUTE FUNCTION retrieval.reject_immutable_change();
        CREATE TRIGGER immutable_chunk_ritual_passages
        BEFORE UPDATE OR DELETE ON retrieval.chunk_ritual_passages
        FOR EACH ROW EXECUTE FUNCTION retrieval.reject_immutable_change();
        CREATE TRIGGER immutable_chunk_ritual_versions
        BEFORE UPDATE OR DELETE ON retrieval.chunk_ritual_versions
        FOR EACH ROW EXECUTE FUNCTION retrieval.reject_immutable_change();
        CREATE TRIGGER immutable_chunk_external_segments
        BEFORE UPDATE OR DELETE ON retrieval.chunk_external_segments
        FOR EACH ROW EXECUTE FUNCTION retrieval.reject_immutable_change();

        CREATE FUNCTION retrieval.validate_embedding_dimensions()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE expected_dimensions integer;
        BEGIN
            SELECT dimensions INTO expected_dimensions
              FROM retrieval.embedding_models WHERE id = NEW.embedding_model_id;
            IF vector_dims(NEW.embedding) <> expected_dimensions THEN
                RAISE EXCEPTION 'embedding dimensions do not match registered model';
            END IF;
            RETURN NEW;
        END;
        $$;
        CREATE TRIGGER validate_embedding_dimensions
        BEFORE INSERT ON retrieval.chunk_embeddings
        FOR EACH ROW EXECUTE FUNCTION retrieval.validate_embedding_dimensions();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION retrieval.validate_embedding_dimensions() CASCADE")
    op.execute("DROP FUNCTION retrieval.reject_immutable_change() CASCADE")
    op.execute("DROP FUNCTION retrieval.validate_chunk_membership() CASCADE")
    op.drop_table("chunk_ritual_versions", schema="retrieval")
    op.drop_table("chunk_ritual_passages", schema="retrieval")
    op.drop_table("chunking_run_ritual_sources", schema="retrieval")
    op.drop_table("chunk_canon_passages", schema="retrieval")
    op.drop_table("chunking_run_ayin_sources", schema="retrieval")
    op.drop_table("chunk_external_segments", schema="retrieval")
    op.drop_table("chunking_run_external_sources", schema="retrieval")
    op.drop_index(
        op.f("ix_results_retrieval_run_id"), table_name="results", schema="retrieval"
    )
    op.drop_table("results", schema="retrieval")
    op.drop_table("evaluation_judgments", schema="retrieval")
    op.drop_index(
        op.f("ix_chunk_external_entities_chunk_id"),
        table_name="chunk_external_entities",
        schema="retrieval",
    )
    op.drop_table("chunk_external_entities", schema="retrieval")
    op.drop_index(
        op.f("ix_chunk_embeddings_embedding_model_id"),
        table_name="chunk_embeddings",
        schema="retrieval",
    )
    op.drop_index(
        op.f("ix_chunk_embeddings_chunk_id"),
        table_name="chunk_embeddings",
        schema="retrieval",
    )
    op.drop_table("chunk_embeddings", schema="retrieval")
    op.drop_table("chunk_ayin_concepts", schema="retrieval")
    op.drop_table("runs", schema="retrieval")
    op.drop_table("evaluation_runs", schema="retrieval")
    op.drop_table("embedding_runs", schema="retrieval")
    op.drop_index(
        "ix_retrieval_chunks_search_vector",
        table_name="chunks",
        schema="retrieval",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_retrieval_chunks_lane_language", table_name="chunks", schema="retrieval"
    )
    op.drop_index(
        op.f("ix_chunks_chunking_run_id"), table_name="chunks", schema="retrieval"
    )
    op.drop_table("chunks", schema="retrieval")
    op.drop_table("evaluation_queries", schema="retrieval")
    op.drop_table("embedding_models", schema="retrieval")
    op.drop_table("configurations", schema="retrieval")
    op.drop_table("chunking_runs", schema="retrieval")
    op.execute("DROP TYPE retrieval.retrieval_source_kind")
    op.execute("DROP TYPE retrieval.evaluation_query_type")
    op.execute("DROP TYPE retrieval.query_language")
    op.execute("DROP TYPE retrieval.distance_metric")
    op.execute("DROP TYPE retrieval.retrieval_lane")
    op.execute("DROP TYPE retrieval.build_status")
    # ### end Alembic commands ###
