"""Closed vocabularies for the language-neutral lecture master."""

from enum import StrEnum


class PublicationLanguage(StrEnum):
    """Language targets handed from Phase 8 to Phase 9 localizers."""

    FA = "fa"
    DE = "de"
    EN = "en"
    AR = "ar"


SUPPORTED_PUBLICATION_LANGUAGES = tuple(PublicationLanguage)


class LectureType(StrEnum):
    FOUNDATION = "FOUNDATION"
    HUMAN_QUESTION = "HUMAN_QUESTION"
    DIALOGUE = "DIALOGUE"
    APPLICATION = "APPLICATION"
    OPEN_QUESTION = "OPEN_QUESTION"
    CRITIQUE = "CRITIQUE"
    RITUAL_COMPANION = "RITUAL_COMPANION"
    REFERENCE_DEEP_DIVE = "REFERENCE_DEEP_DIVE"


class LectureProjectStatus(StrEnum):
    DRAFT = "DRAFT"
    ARCHITECTED = "ARCHITECTED"
    READY = "READY"
    FAILED = "FAILED"
    STALE = "STALE"
    SUPERSEDED = "SUPERSEDED"


class MasterStatus(StrEnum):
    DRAFT = "DRAFT"
    ARCHITECTED = "ARCHITECTED"
    VALIDATING = "VALIDATING"
    READY = "READY"
    FAILED = "FAILED"
    STALE = "STALE"
    SUPERSEDED = "SUPERSEDED"


class SectionRole(StrEnum):
    HUMAN_ENTRY = "HUMAN_ENTRY"
    AYIN_FRAME = "AYIN_FRAME"
    CONCEPT_DEFINITION = "CONCEPT_DEFINITION"
    DISTINCTION = "DISTINCTION"
    EXTERNAL_DIALOGUE = "EXTERNAL_DIALOGUE"
    EMPIRICAL_EVIDENCE = "EMPIRICAL_EVIDENCE"
    PHILOSOPHICAL_DIALOGUE = "PHILOSOPHICAL_DIALOGUE"
    COUNTERARGUMENT = "COUNTERARGUMENT"
    LIMITATION = "LIMITATION"
    OPEN_QUESTION = "OPEN_QUESTION"
    LIFE_RETURN = "LIFE_RETURN"
    RITUAL_BRIDGE = "RITUAL_BRIDGE"
    CONCLUSION = "CONCLUSION"


class ClaimOrigin(StrEnum):
    AYIN = "AYIN"
    EXTERNAL = "EXTERNAL"
    SYNTHESIS = "SYNTHESIS"
    OPEN_QUESTION = "OPEN_QUESTION"
    RITUAL_CONTEXT = "RITUAL_CONTEXT"
    EXAMPLE = "EXAMPLE"


class ClaimEpistemicStatus(StrEnum):
    AYIN_DEFINITION = "AYIN_DEFINITION"
    AYIN_PRINCIPLE = "AYIN_PRINCIPLE"
    AYIN_DISTINCTION = "AYIN_DISTINCTION"
    AYIN_ETHICAL_ORIENTATION = "AYIN_ETHICAL_ORIENTATION"
    AYIN_DESCRIPTIVE_STATEMENT = "AYIN_DESCRIPTIVE_STATEMENT"
    OPTIONAL_METAPHYSICAL_INTERPRETATION = "OPTIONAL_METAPHYSICAL_INTERPRETATION"
    EXTERNAL_EMPIRICAL_CLAIM = "EXTERNAL_EMPIRICAL_CLAIM"
    EXTERNAL_PHILOSOPHICAL_ARGUMENT = "EXTERNAL_PHILOSOPHICAL_ARGUMENT"
    EXTERNAL_ATTRIBUTED_CLAIM = "EXTERNAL_ATTRIBUTED_CLAIM"
    CONCEPTUAL_PARALLEL = "CONCEPTUAL_PARALLEL"
    NON_EQUIVALENCE = "NON_EQUIVALENCE"
    COUNTEREVIDENCE = "COUNTEREVIDENCE"
    ALTERNATIVE_EXPLANATION = "ALTERNATIVE_EXPLANATION"
    SYNTHESIS_INFERENCE = "SYNTHESIS_INFERENCE"
    OPEN_QUESTION = "OPEN_QUESTION"
    ILLUSTRATIVE_EXAMPLE = "ILLUSTRATIVE_EXAMPLE"
    RITUAL_CONTEXT = "RITUAL_CONTEXT"


class DiscourseType(StrEnum):
    CONCEPTUAL = "CONCEPTUAL"
    DESCRIPTIVE = "DESCRIPTIVE"
    ETHICAL = "ETHICAL"
    OPTIONAL_METAPHYSICAL = "OPTIONAL_METAPHYSICAL"


class EvidenceBindingRole(StrEnum):
    PRIMARY = "PRIMARY"
    SUPPORTING = "SUPPORTING"
    COUNTEREVIDENCE = "COUNTEREVIDENCE"
    PREMISE = "PREMISE"
    CONTEXT = "CONTEXT"


class EvidenceKind(StrEnum):
    AYIN_PASSAGE = "AYIN_PASSAGE"
    AYIN_CONCEPT = "AYIN_CONCEPT"
    AYIN_PRINCIPLE = "AYIN_PRINCIPLE"
    AYIN_DISTINCTION = "AYIN_DISTINCTION"
    AYIN_OPEN_QUESTION = "AYIN_OPEN_QUESTION"
    EXTERNAL_CHUNK = "EXTERNAL_CHUNK"
    DIALOGUE_RELATION = "DIALOGUE_RELATION"
    RITUAL_VERSION = "RITUAL_VERSION"


class CitationKind(StrEnum):
    AYIN = "AYIN"
    MANASEK = "MANASEK"
    EXTERNAL = "EXTERNAL"


class ValidationDimension(StrEnum):
    AYIN_FIDELITY = "AYIN_FIDELITY"
    EPISTEMIC_INTEGRITY = "EPISTEMIC_INTEGRITY"
    CITATION_COVERAGE = "CITATION_COVERAGE"
    DIALOGUE_STATUS = "DIALOGUE_STATUS"
    COUNTEREVIDENCE_HANDLING = "COUNTEREVIDENCE_HANDLING"
    OPEN_QUESTION_PRESERVATION = "OPEN_QUESTION_PRESERVATION"
    RITUAL_BOUNDARY = "RITUAL_BOUNDARY"
    PACKAGE_TRACEABILITY = "PACKAGE_TRACEABILITY"
